#include <nanobind/nanobind.h>
#include "pyoptinterface/knitro_model.hpp"

namespace nb = nanobind;

void bind_knitro_constants(nb::module_ &m)
{
	nb::module_ KN = m.def_submodule("KN");

	// Objective goal
	KN.attr("OBJGOAL_MINIMIZE") = KN_OBJGOAL_MINIMIZE;
	KN.attr("OBJGOAL_MAXIMIZE") = KN_OBJGOAL_MAXIMIZE;

	// Variable types
	KN.attr("VARTYPE_CONTINUOUS") = KN_VARTYPE_CONTINUOUS;
	KN.attr("VARTYPE_INTEGER") = KN_VARTYPE_INTEGER;
	KN.attr("VARTYPE_BINARY") = KN_VARTYPE_BINARY;

	// Infinity
	KN.attr("INFINITY") = KN_INFINITY;

	// Return codes - Optimal/Satisfactory
	KN.attr("RC_OPTIMAL_OR_SATISFACTORY") = KN_RC_OPTIMAL_OR_SATISFACTORY;
	KN.attr("RC_OPTIMAL") = KN_RC_OPTIMAL;

	// Return codes - Feasible
	KN.attr("RC_NEAR_OPT") = KN_RC_NEAR_OPT;
	KN.attr("RC_FEAS_XTOL") = KN_RC_FEAS_XTOL;
	KN.attr("RC_FEAS_NO_IMPROVE") = KN_RC_FEAS_NO_IMPROVE;
	KN.attr("RC_FEAS_FTOL") = KN_RC_FEAS_FTOL;
	KN.attr("RC_FEAS_BEST") = KN_RC_FEAS_BEST;
	KN.attr("RC_FEAS_MULTISTART") = KN_RC_FEAS_MULTISTART;

	// Return codes - Infeasible
	KN.attr("RC_INFEASIBLE") = KN_RC_INFEASIBLE;
	KN.attr("RC_INFEAS_XTOL") = KN_RC_INFEAS_XTOL;
	KN.attr("RC_INFEAS_NO_IMPROVE") = KN_RC_INFEAS_NO_IMPROVE;
	KN.attr("RC_INFEAS_MULTISTART") = KN_RC_INFEAS_MULTISTART;
	KN.attr("RC_INFEAS_CON_BOUNDS") = KN_RC_INFEAS_CON_BOUNDS;
	KN.attr("RC_INFEAS_VAR_BOUNDS") = KN_RC_INFEAS_VAR_BOUNDS;

	// Return codes - Unbounded
	KN.attr("RC_UNBOUNDED") = KN_RC_UNBOUNDED;
	KN.attr("RC_UNBOUNDED_OR_INFEAS") = KN_RC_UNBOUNDED_OR_INFEAS;

	// Return codes - Limit exceeded (feasible)
	KN.attr("RC_ITER_LIMIT_FEAS") = KN_RC_ITER_LIMIT_FEAS;
	KN.attr("RC_TIME_LIMIT_FEAS") = KN_RC_TIME_LIMIT_FEAS;
	KN.attr("RC_FEVAL_LIMIT_FEAS") = KN_RC_FEVAL_LIMIT_FEAS;
	KN.attr("RC_MIP_EXH_FEAS") = KN_RC_MIP_EXH_FEAS;
	KN.attr("RC_MIP_TERM_FEAS") = KN_RC_MIP_TERM_FEAS;
	KN.attr("RC_MIP_SOLVE_LIMIT_FEAS") = KN_RC_MIP_SOLVE_LIMIT_FEAS;
	KN.attr("RC_MIP_NODE_LIMIT_FEAS") = KN_RC_MIP_NODE_LIMIT_FEAS;

	// Return codes - Limit exceeded (infeasible)
	KN.attr("RC_ITER_LIMIT_INFEAS") = KN_RC_ITER_LIMIT_INFEAS;
	KN.attr("RC_TIME_LIMIT_INFEAS") = KN_RC_TIME_LIMIT_INFEAS;
	KN.attr("RC_FEVAL_LIMIT_INFEAS") = KN_RC_FEVAL_LIMIT_INFEAS;
	KN.attr("RC_MIP_EXH_INFEAS") = KN_RC_MIP_EXH_INFEAS;
	KN.attr("RC_MIP_SOLVE_LIMIT_INFEAS") = KN_RC_MIP_SOLVE_LIMIT_INFEAS;
	KN.attr("RC_MIP_NODE_LIMIT_INFEAS") = KN_RC_MIP_NODE_LIMIT_INFEAS;

	// Return codes - Other failures
	KN.attr("RC_CALLBACK_ERR") = KN_RC_CALLBACK_ERR;
	KN.attr("RC_LP_SOLVER_ERR") = KN_RC_LP_SOLVER_ERR;
	KN.attr("RC_EVAL_ERR") = KN_RC_EVAL_ERR;
	KN.attr("RC_OUT_OF_MEMORY") = KN_RC_OUT_OF_MEMORY;
	KN.attr("RC_USER_TERMINATION") = KN_RC_USER_TERMINATION;
	KN.attr("RC_OPEN_FILE_ERR") = KN_RC_OPEN_FILE_ERR;

	// Return codes - Problem definition errors
	KN.attr("RC_BAD_N_OR_F") = KN_RC_BAD_N_OR_F;
	KN.attr("RC_BAD_CONSTRAINT") = KN_RC_BAD_CONSTRAINT;
	KN.attr("RC_BAD_JACOBIAN") = KN_RC_BAD_JACOBIAN;
	KN.attr("RC_BAD_HESSIAN") = KN_RC_BAD_HESSIAN;
	KN.attr("RC_BAD_CON_INDEX") = KN_RC_BAD_CON_INDEX;
	KN.attr("RC_BAD_JAC_INDEX") = KN_RC_BAD_JAC_INDEX;
	KN.attr("RC_BAD_HESS_INDEX") = KN_RC_BAD_HESS_INDEX;
	KN.attr("RC_BAD_CON_BOUNDS") = KN_RC_BAD_CON_BOUNDS;
	KN.attr("RC_BAD_VAR_BOUNDS") = KN_RC_BAD_VAR_BOUNDS;
	KN.attr("RC_ILLEGAL_CALL") = KN_RC_ILLEGAL_CALL;
	KN.attr("RC_BAD_KCPTR") = KN_RC_BAD_KCPTR;
	KN.attr("RC_NULL_POINTER") = KN_RC_NULL_POINTER;
	KN.attr("RC_BAD_INIT_VALUE") = KN_RC_BAD_INIT_VALUE;
	KN.attr("RC_LICENSE_ERROR") = KN_RC_LICENSE_ERROR;
	KN.attr("RC_BAD_PARAMINPUT") = KN_RC_BAD_PARAMINPUT;
	KN.attr("RC_LINEAR_SOLVER_ERR") = KN_RC_LINEAR_SOLVER_ERR;
	KN.attr("RC_DERIV_CHECK_FAILED") = KN_RC_DERIV_CHECK_FAILED;
	KN.attr("RC_DERIV_CHECK_TERMINATE") = KN_RC_DERIV_CHECK_TERMINATE;
	KN.attr("RC_OVERFLOW_ERR") = KN_RC_OVERFLOW_ERR;
	KN.attr("RC_BAD_SIZE") = KN_RC_BAD_SIZE;
	KN.attr("RC_BAD_VARIABLE") = KN_RC_BAD_VARIABLE;
	KN.attr("RC_BAD_VAR_INDEX") = KN_RC_BAD_VAR_INDEX;
	KN.attr("RC_BAD_OBJECTIVE") = KN_RC_BAD_OBJECTIVE;
	KN.attr("RC_BAD_OBJ_INDEX") = KN_RC_BAD_OBJ_INDEX;
	KN.attr("RC_BAD_RESIDUAL") = KN_RC_BAD_RESIDUAL;
	KN.attr("RC_BAD_RSD_INDEX") = KN_RC_BAD_RSD_INDEX;
	KN.attr("RC_INTERNAL_ERROR") = KN_RC_INTERNAL_ERROR;

	// Callback request codes
	KN.attr("RC_EVALFC") = KN_RC_EVALFC;
	KN.attr("RC_EVALGA") = KN_RC_EVALGA;
	KN.attr("RC_EVALH") = KN_RC_EVALH;
	KN.attr("RC_EVALHV") = KN_RC_EVALHV;
	KN.attr("RC_EVALH_NO_F") = KN_RC_EVALH_NO_F;
	KN.attr("RC_EVALHV_NO_F") = KN_RC_EVALHV_NO_F;
	KN.attr("RC_EVALR") = KN_RC_EVALR;
	KN.attr("RC_EVALRJ") = KN_RC_EVALRJ;
	KN.attr("RC_EVALFCGA") = KN_RC_EVALFCGA;

	// Parameter types
	KN.attr("PARAMTYPE_INTEGER") = KN_PARAMTYPE_INTEGER;
	KN.attr("PARAMTYPE_FLOAT") = KN_PARAMTYPE_FLOAT;
	KN.attr("PARAMTYPE_STRING") = KN_PARAMTYPE_STRING;
}
