#include <nanobind/nanobind.h>
#include "pyoptinterface/knitro_model.hpp"

namespace nb = nanobind;

void bind_knitro_constants(nb::module_ &m)
{
	nb::module_ KN = m.def_submodule("KN");

	// Objective goal
	KN.attr("OBJGOAL_MINIMIZE") = KN_OBJGOAL_MINIMIZE;
	KN.attr("OBJGOAL_MAXIMIZE") = KN_OBJGOAL_MAXIMIZE;

	// Variable types
	KN.attr("VARTYPE_CONTINUOUS") = KN_VARTYPE_CONTINUOUS;
	KN.attr("VARTYPE_INTEGER") = KN_VARTYPE_INTEGER;
	KN.attr("VARTYPE_BINARY") = KN_VARTYPE_BINARY;

	// Infinity
	KN.attr("INFINITY") = KN_INFINITY;

	// Return codes - Optimal/Satisfactory
	KN.attr("RC_OPTIMAL_OR_SATISFACTORY") = KN_RC_OPTIMAL_OR_SATISFACTORY;
	KN.attr("RC_OPTIMAL") = KN_RC_OPTIMAL;

	// Return codes - Feasible
	KN.attr("RC_NEAR_OPT") = KN_RC_NEAR_OPT;
	KN.attr("RC_FEAS_XTOL") = KN_RC_FEAS_XTOL;
	KN.attr("RC_FEAS_NO_IMPROVE") = KN_RC_FEAS_NO_IMPROVE;
	KN.attr("RC_FEAS_FTOL") = KN_RC_FEAS_FTOL;
	KN.attr("RC_FEAS_BEST") = KN_RC_FEAS_BEST;
	KN.attr("RC_FEAS_MULTISTART") = KN_RC_FEAS_MULTISTART;

	// Return codes - Infeasible
	KN.attr("RC_INFEASIBLE") = KN_RC_INFEASIBLE;
	KN.attr("RC_INFEAS_XTOL") = KN_RC_INFEAS_XTOL;
	KN.attr("RC_INFEAS_NO_IMPROVE") = KN_RC_INFEAS_NO_IMPROVE;
	KN.attr("RC_INFEAS_MULTISTART") = KN_RC_INFEAS_MULTISTART;
	KN.attr("RC_INFEAS_CON_BOUNDS") = KN_RC_INFEAS_CON_BOUNDS;
	KN.attr("RC_INFEAS_VAR_BOUNDS") = KN_RC_INFEAS_VAR_BOUNDS;

	// Return codes - Unbounded
	KN.attr("RC_UNBOUNDED") = KN_RC_UNBOUNDED;
	KN.attr("RC_UNBOUNDED_OR_INFEAS") = KN_RC_UNBOUNDED_OR_INFEAS;

	// Return codes - Limit exceeded (feasible)
	KN.attr("RC_ITER_LIMIT_FEAS") = KN_RC_ITER_LIMIT_FEAS;
	KN.attr("RC_TIME_LIMIT_FEAS") = KN_RC_TIME_LIMIT_FEAS;
	KN.attr("RC_FEVAL_LIMIT_FEAS") = KN_RC_FEVAL_LIMIT_FEAS;
	KN.attr("RC_MIP_EXH_FEAS") = KN_RC_MIP_EXH_FEAS;
	KN.attr("RC_MIP_TERM_FEAS") = KN_RC_MIP_TERM_FEAS;
	KN.attr("RC_MIP_SOLVE_LIMIT_FEAS") = KN_RC_MIP_SOLVE_LIMIT_FEAS;
	KN.attr("RC_MIP_NODE_LIMIT_FEAS") = KN_RC_MIP_NODE_LIMIT_FEAS;

	// Return codes - Limit exceeded (infeasible)
	KN.attr("RC_ITER_LIMIT_INFEAS") = KN_RC_ITER_LIMIT_INFEAS;
	KN.attr("RC_TIME_LIMIT_INFEAS") = KN_RC_TIME_LIMIT_INFEAS;
	KN.attr("RC_FEVAL_LIMIT_INFEAS") = KN_RC_FEVAL_LIMIT_INFEAS;
	KN.attr("RC_MIP_EXH_INFEAS") = KN_RC_MIP_EXH_INFEAS;
	KN.attr("RC_MIP_SOLVE_LIMIT_INFEAS") = KN_RC_MIP_SOLVE_LIMIT_INFEAS;
	KN.attr("RC_MIP_NODE_LIMIT_INFEAS") = KN_RC_MIP_NODE_LIMIT_INFEAS;

	// Return codes - Other failures
	KN.attr("RC_CALLBACK_ERR") = KN_RC_CALLBACK_ERR;
	KN.attr("RC_LP_SOLVER_ERR") = KN_RC_LP_SOLVER_ERR;
	KN.attr("RC_EVAL_ERR") = KN_RC_EVAL_ERR;
	KN.attr("RC_OUT_OF_MEMORY") = KN_RC_OUT_OF_MEMORY;
	KN.attr("RC_USER_TERMINATION") = KN_RC_USER_TERMINATION;
	KN.attr("RC_OPEN_FILE_ERR") = KN_RC_OPEN_FILE_ERR;

	// Return codes - Problem definition errors
	KN.attr("RC_BAD_N_OR_F") = KN_RC_BAD_N_OR_F;
	KN.attr("RC_BAD_CONSTRAINT") = KN_RC_BAD_CONSTRAINT;
	KN.attr("RC_BAD_JACOBIAN") = KN_RC_BAD_JACOBIAN;
	KN.attr("RC_BAD_HESSIAN") = KN_RC_BAD_HESSIAN;
	KN.attr("RC_BAD_CON_INDEX") = KN_RC_BAD_CON_INDEX;
	KN.attr("RC_BAD_JAC_INDEX") = KN_RC_BAD_JAC_INDEX;
	KN.attr("RC_BAD_HESS_INDEX") = KN_RC_BAD_HESS_INDEX;
	KN.attr("RC_BAD_CON_BOUNDS") = KN_RC_BAD_CON_BOUNDS;
	KN.attr("RC_BAD_VAR_BOUNDS") = KN_RC_BAD_VAR_BOUNDS;
	KN.attr("RC_ILLEGAL_CALL") = KN_RC_ILLEGAL_CALL;
	KN.attr("RC_BAD_KCPTR") = KN_RC_BAD_KCPTR;
	KN.attr("RC_NULL_POINTER") = KN_RC_NULL_POINTER;
	KN.attr("RC_BAD_INIT_VALUE") = KN_RC_BAD_INIT_VALUE;
	KN.attr("RC_LICENSE_ERROR") = KN_RC_LICENSE_ERROR;
	KN.attr("RC_BAD_PARAMINPUT") = KN_RC_BAD_PARAMINPUT;
	KN.attr("RC_LINEAR_SOLVER_ERR") = KN_RC_LINEAR_SOLVER_ERR;
	KN.attr("RC_DERIV_CHECK_FAILED") = KN_RC_DERIV_CHECK_FAILED;
	KN.attr("RC_DERIV_CHECK_TERMINATE") = KN_RC_DERIV_CHECK_TERMINATE;
	KN.attr("RC_OVERFLOW_ERR") = KN_RC_OVERFLOW_ERR;
	KN.attr("RC_BAD_SIZE") = KN_RC_BAD_SIZE;
	KN.attr("RC_BAD_VARIABLE") = KN_RC_BAD_VARIABLE;
	KN.attr("RC_BAD_VAR_INDEX") = KN_RC_BAD_VAR_INDEX;
	KN.attr("RC_BAD_OBJECTIVE") = KN_RC_BAD_OBJECTIVE;
	KN.attr("RC_BAD_OBJ_INDEX") = KN_RC_BAD_OBJ_INDEX;
	KN.attr("RC_BAD_RESIDUAL") = KN_RC_BAD_RESIDUAL;
	KN.attr("RC_BAD_RSD_INDEX") = KN_RC_BAD_RSD_INDEX;
	KN.attr("RC_INTERNAL_ERROR") = KN_RC_INTERNAL_ERROR;

	// Callback request codes
	KN.attr("RC_EVALFC") = KN_RC_EVALFC;
	KN.attr("RC_EVALGA") = KN_RC_EVALGA;
	KN.attr("RC_EVALH") = KN_RC_EVALH;
	KN.attr("RC_EVALHV") = KN_RC_EVALHV;
	KN.attr("RC_EVALH_NO_F") = KN_RC_EVALH_NO_F;
	KN.attr("RC_EVALHV_NO_F") = KN_RC_EVALHV_NO_F;
	KN.attr("RC_EVALR") = KN_RC_EVALR;
	KN.attr("RC_EVALRJ") = KN_RC_EVALRJ;
	KN.attr("RC_EVALFCGA") = KN_RC_EVALFCGA;

	// Parameter types
	KN.attr("PARAMTYPE_INTEGER") = KN_PARAMTYPE_INTEGER;
	KN.attr("PARAMTYPE_FLOAT") = KN_PARAMTYPE_FLOAT;
	KN.attr("PARAMTYPE_STRING") = KN_PARAMTYPE_STRING;

	// Parameter IDs
	KN.attr("PARAM_NEWPOINT") = KN_PARAM_NEWPOINT;
	KN.attr("PARAM_HONORBNDS") = KN_PARAM_HONORBNDS;
	KN.attr("PARAM_ALGORITHM") = KN_PARAM_ALGORITHM;
	KN.attr("PARAM_ALG") = KN_PARAM_ALG;
	KN.attr("PARAM_NLP_ALGORITHM") = KN_PARAM_NLP_ALGORITHM;
	KN.attr("PARAM_BAR_MURULE") = KN_PARAM_BAR_MURULE;
	KN.attr("PARAM_BAR_FEASIBLE") = KN_PARAM_BAR_FEASIBLE;
	KN.attr("PARAM_GRADOPT") = KN_PARAM_GRADOPT;
	KN.attr("PARAM_HESSOPT") = KN_PARAM_HESSOPT;
	KN.attr("PARAM_BAR_INITPT") = KN_PARAM_BAR_INITPT;
	KN.attr("PARAM_ACT_LPSOLVER") = KN_PARAM_ACT_LPSOLVER;
	KN.attr("PARAM_CG_MAXIT") = KN_PARAM_CG_MAXIT;
	KN.attr("PARAM_MAXIT") = KN_PARAM_MAXIT;
	KN.attr("PARAM_OUTLEV") = KN_PARAM_OUTLEV;
	KN.attr("PARAM_OUTMODE") = KN_PARAM_OUTMODE;
	KN.attr("PARAM_SCALE") = KN_PARAM_SCALE;
	KN.attr("PARAM_SOC") = KN_PARAM_SOC;
	KN.attr("PARAM_DELTA") = KN_PARAM_DELTA;
	KN.attr("PARAM_BAR_FEASMODETOL") = KN_PARAM_BAR_FEASMODETOL;
	KN.attr("PARAM_FEASTOL") = KN_PARAM_FEASTOL;
	KN.attr("PARAM_FEASTOLABS") = KN_PARAM_FEASTOLABS;
	KN.attr("PARAM_MAXTIMECPU") = KN_PARAM_MAXTIMECPU;
	KN.attr("PARAM_BAR_INITMU") = KN_PARAM_BAR_INITMU;
	KN.attr("PARAM_OBJRANGE") = KN_PARAM_OBJRANGE;
	KN.attr("PARAM_OPTTOL") = KN_PARAM_OPTTOL;
	KN.attr("PARAM_OPTTOLABS") = KN_PARAM_OPTTOLABS;
	KN.attr("PARAM_LINSOLVER_PIVOTTOL") = KN_PARAM_LINSOLVER_PIVOTTOL;
	KN.attr("PARAM_XTOL") = KN_PARAM_XTOL;
	KN.attr("PARAM_DEBUG") = KN_PARAM_DEBUG;
	KN.attr("PARAM_MULTISTART") = KN_PARAM_MULTISTART;
	KN.attr("PARAM_MS_ENABLE") = KN_PARAM_MS_ENABLE;
	KN.attr("PARAM_MS_MAXSOLVES") = KN_PARAM_MS_MAXSOLVES;
	KN.attr("PARAM_MS_MAXBNDRANGE") = KN_PARAM_MS_MAXBNDRANGE;
	KN.attr("PARAM_MS_MAXTIMECPU") = KN_PARAM_MS_MAXTIMECPU;
	KN.attr("PARAM_MS_MAXTIMEREAL") = KN_PARAM_MS_MAXTIMEREAL;
	KN.attr("PARAM_LMSIZE") = KN_PARAM_LMSIZE;
	KN.attr("PARAM_BAR_MAXCROSSIT") = KN_PARAM_BAR_MAXCROSSIT;
	KN.attr("PARAM_MAXTIMEREAL") = KN_PARAM_MAXTIMEREAL;
	KN.attr("PARAM_CG_PRECOND") = KN_PARAM_CG_PRECOND;
	KN.attr("PARAM_BLASOPTION") = KN_PARAM_BLASOPTION;
	KN.attr("PARAM_BAR_MAXREFACTOR") = KN_PARAM_BAR_MAXREFACTOR;
	KN.attr("PARAM_LINESEARCH_MAXTRIALS") = KN_PARAM_LINESEARCH_MAXTRIALS;
	KN.attr("PARAM_BLASOPTIONLIB") = KN_PARAM_BLASOPTIONLIB;
	KN.attr("PARAM_OUTAPPEND") = KN_PARAM_OUTAPPEND;
	KN.attr("PARAM_OUTDIR") = KN_PARAM_OUTDIR;
	KN.attr("PARAM_CPLEXLIB") = KN_PARAM_CPLEXLIB;
	KN.attr("PARAM_BAR_PENRULE") = KN_PARAM_BAR_PENRULE;
	KN.attr("PARAM_BAR_PENCONS") = KN_PARAM_BAR_PENCONS;
	KN.attr("PARAM_MS_NUMTOSAVE") = KN_PARAM_MS_NUMTOSAVE;
	KN.attr("PARAM_MS_SAVETOL") = KN_PARAM_MS_SAVETOL;
	KN.attr("PARAM_MS_TERMINATE") = KN_PARAM_MS_TERMINATE;
	KN.attr("PARAM_MS_STARTPTRANGE") = KN_PARAM_MS_STARTPTRANGE;
	KN.attr("PARAM_INFEASTOL") = KN_PARAM_INFEASTOL;
	KN.attr("PARAM_LINSOLVER") = KN_PARAM_LINSOLVER;
	KN.attr("PARAM_BAR_DIRECTINTERVAL") = KN_PARAM_BAR_DIRECTINTERVAL;
	KN.attr("PARAM_PRESOLVE") = KN_PARAM_PRESOLVE;
	KN.attr("PARAM_PRESOLVE_TOL") = KN_PARAM_PRESOLVE_TOL;
	KN.attr("PARAM_BAR_SWITCHRULE") = KN_PARAM_BAR_SWITCHRULE;
	KN.attr("PARAM_HESSIAN_NO_F") = KN_PARAM_HESSIAN_NO_F;
	KN.attr("PARAM_MA_TERMINATE") = KN_PARAM_MA_TERMINATE;
	KN.attr("PARAM_MA_MAXTIMECPU") = KN_PARAM_MA_MAXTIMECPU;
	KN.attr("PARAM_MA_MAXTIMEREAL") = KN_PARAM_MA_MAXTIMEREAL;
	KN.attr("PARAM_MS_SEED") = KN_PARAM_MS_SEED;
	KN.attr("PARAM_MA_OUTSUB") = KN_PARAM_MA_OUTSUB;
	KN.attr("PARAM_MS_OUTSUB") = KN_PARAM_MS_OUTSUB;
	KN.attr("PARAM_XPRESSLIB") = KN_PARAM_XPRESSLIB;
	KN.attr("PARAM_TUNER") = KN_PARAM_TUNER;
	KN.attr("PARAM_TUNER_OPTIONSFILE") = KN_PARAM_TUNER_OPTIONSFILE;
	KN.attr("PARAM_TUNER_MAXTIMECPU") = KN_PARAM_TUNER_MAXTIMECPU;
	KN.attr("PARAM_TUNER_MAXTIMEREAL") = KN_PARAM_TUNER_MAXTIMEREAL;
	KN.attr("PARAM_TUNER_OUTSUB") = KN_PARAM_TUNER_OUTSUB;
	KN.attr("PARAM_TUNER_TERMINATE") = KN_PARAM_TUNER_TERMINATE;
	KN.attr("PARAM_LINSOLVER_OOC") = KN_PARAM_LINSOLVER_OOC;
	KN.attr("PARAM_BAR_RELAXCONS") = KN_PARAM_BAR_RELAXCONS;
	KN.attr("PARAM_MS_DETERMINISTIC") = KN_PARAM_MS_DETERMINISTIC;
	KN.attr("PARAM_BAR_REFINEMENT") = KN_PARAM_BAR_REFINEMENT;
	KN.attr("PARAM_DERIVCHECK") = KN_PARAM_DERIVCHECK;
	KN.attr("PARAM_DERIVCHECK_TYPE") = KN_PARAM_DERIVCHECK_TYPE;
	KN.attr("PARAM_DERIVCHECK_TOL") = KN_PARAM_DERIVCHECK_TOL;
	KN.attr("PARAM_MAXFEVALS") = KN_PARAM_MAXFEVALS;
	KN.attr("PARAM_FSTOPVAL") = KN_PARAM_FSTOPVAL;
	KN.attr("PARAM_DATACHECK") = KN_PARAM_DATACHECK;
	KN.attr("PARAM_DERIVCHECK_TERMINATE") = KN_PARAM_DERIVCHECK_TERMINATE;
	KN.attr("PARAM_BAR_WATCHDOG") = KN_PARAM_BAR_WATCHDOG;
	KN.attr("PARAM_FTOL") = KN_PARAM_FTOL;
	KN.attr("PARAM_FTOL_ITERS") = KN_PARAM_FTOL_ITERS;
	KN.attr("PARAM_ACT_QPALG") = KN_PARAM_ACT_QPALG;
	KN.attr("PARAM_BAR_INITPI_MPEC") = KN_PARAM_BAR_INITPI_MPEC;
	KN.attr("PARAM_XTOL_ITERS") = KN_PARAM_XTOL_ITERS;
	KN.attr("PARAM_LINESEARCH") = KN_PARAM_LINESEARCH;
	KN.attr("PARAM_OUT_CSVINFO") = KN_PARAM_OUT_CSVINFO;
	KN.attr("PARAM_INITPENALTY") = KN_PARAM_INITPENALTY;
	KN.attr("PARAM_ACT_LPFEASTOL") = KN_PARAM_ACT_LPFEASTOL;
	KN.attr("PARAM_CG_STOPTOL") = KN_PARAM_CG_STOPTOL;
	KN.attr("PARAM_RESTARTS") = KN_PARAM_RESTARTS;
	KN.attr("PARAM_RESTARTS_MAXIT") = KN_PARAM_RESTARTS_MAXIT;
	KN.attr("PARAM_BAR_SLACKBOUNDPUSH") = KN_PARAM_BAR_SLACKBOUNDPUSH;
	KN.attr("PARAM_CG_PMEM") = KN_PARAM_CG_PMEM;
	KN.attr("PARAM_BAR_SWITCHOBJ") = KN_PARAM_BAR_SWITCHOBJ;
	KN.attr("PARAM_OUTNAME") = KN_PARAM_OUTNAME;
	KN.attr("PARAM_OUT_CSVNAME") = KN_PARAM_OUT_CSVNAME;
	KN.attr("PARAM_ACT_PARAMETRIC") = KN_PARAM_ACT_PARAMETRIC;
	KN.attr("PARAM_ACT_LPDUMPMPS") = KN_PARAM_ACT_LPDUMPMPS;
	KN.attr("PARAM_ACT_LPALG") = KN_PARAM_ACT_LPALG;
	KN.attr("PARAM_ACT_LPPRESOLVE") = KN_PARAM_ACT_LPPRESOLVE;
	KN.attr("PARAM_ACT_LPPENALTY") = KN_PARAM_ACT_LPPENALTY;
	KN.attr("PARAM_BNDRANGE") = KN_PARAM_BNDRANGE;
	KN.attr("PARAM_BAR_CONIC_ENABLE") = KN_PARAM_BAR_CONIC_ENABLE;
	KN.attr("PARAM_CONVEX") = KN_PARAM_CONVEX;
	KN.attr("PARAM_OUT_HINTS") = KN_PARAM_OUT_HINTS;
	KN.attr("PARAM_EVAL_FCGA") = KN_PARAM_EVAL_FCGA;
	KN.attr("PARAM_BAR_MAXCORRECTORS") = KN_PARAM_BAR_MAXCORRECTORS;
	KN.attr("PARAM_STRAT_WARM_START") = KN_PARAM_STRAT_WARM_START;
	KN.attr("PARAM_FINDIFF_TERMINATE") = KN_PARAM_FINDIFF_TERMINATE;
	KN.attr("PARAM_CPUPLATFORM") = KN_PARAM_CPUPLATFORM;
	KN.attr("PARAM_PRESOLVE_PASSES") = KN_PARAM_PRESOLVE_PASSES;
	KN.attr("PARAM_PRESOLVE_LEVEL") = KN_PARAM_PRESOLVE_LEVEL;
	KN.attr("PARAM_FINDIFF_RELSTEPSIZE") = KN_PARAM_FINDIFF_RELSTEPSIZE;
	KN.attr("PARAM_INFEASTOL_ITERS") = KN_PARAM_INFEASTOL_ITERS;
	KN.attr("PARAM_PRESOLVEOP_TIGHTEN") = KN_PARAM_PRESOLVEOP_TIGHTEN;
	KN.attr("PARAM_BAR_LINSYS") = KN_PARAM_BAR_LINSYS;
	KN.attr("PARAM_PRESOLVE_INITPT") = KN_PARAM_PRESOLVE_INITPT;
	KN.attr("PARAM_ACT_QPPENALTY") = KN_PARAM_ACT_QPPENALTY;
	KN.attr("PARAM_BAR_LINSYS_STORAGE") = KN_PARAM_BAR_LINSYS_STORAGE;
	KN.attr("PARAM_LINSOLVER_MAXITREF") = KN_PARAM_LINSOLVER_MAXITREF;
	KN.attr("PARAM_BFGS_SCALING") = KN_PARAM_BFGS_SCALING;
	KN.attr("PARAM_BAR_INITSHIFTTOL") = KN_PARAM_BAR_INITSHIFTTOL;
	KN.attr("PARAM_NUMTHREADS") = KN_PARAM_NUMTHREADS;
	KN.attr("PARAM_CONCURRENT_EVALS") = KN_PARAM_CONCURRENT_EVALS;
	KN.attr("PARAM_BLAS_NUMTHREADS") = KN_PARAM_BLAS_NUMTHREADS;
	KN.attr("PARAM_LINSOLVER_NUMTHREADS") = KN_PARAM_LINSOLVER_NUMTHREADS;
	KN.attr("PARAM_MS_NUMTHREADS") = KN_PARAM_MS_NUMTHREADS;
	KN.attr("PARAM_CONIC_NUMTHREADS") = KN_PARAM_CONIC_NUMTHREADS;
	KN.attr("PARAM_NCVX_QCQP_INIT") = KN_PARAM_NCVX_QCQP_INIT;
	KN.attr("PARAM_FINDIFF_ESTNOISE") = KN_PARAM_FINDIFF_ESTNOISE;
	KN.attr("PARAM_FINDIFF_NUMTHREADS") = KN_PARAM_FINDIFF_NUMTHREADS;
	KN.attr("PARAM_BAR_MPEC_HEURISTIC") = KN_PARAM_BAR_MPEC_HEURISTIC;
	KN.attr("PARAM_PRESOLVEOP_REDUNDANT") = KN_PARAM_PRESOLVEOP_REDUNDANT;
	KN.attr("PARAM_LINSOLVER_ORDERING") = KN_PARAM_LINSOLVER_ORDERING;
	KN.attr("PARAM_LINSOLVER_NODEAMALG") = KN_PARAM_LINSOLVER_NODEAMALG;
	KN.attr("PARAM_PRESOLVEOP_SUBSTITUTION") = KN_PARAM_PRESOLVEOP_SUBSTITUTION;
	KN.attr("PARAM_PRESOLVEOP_SUBSTITUTION_TOL") = KN_PARAM_PRESOLVEOP_SUBSTITUTION_TOL;
	KN.attr("PARAM_MS_INITPT_CLUSTER") = KN_PARAM_MS_INITPT_CLUSTER;
	KN.attr("PARAM_SCALE_VARS") = KN_PARAM_SCALE_VARS;
	KN.attr("PARAM_BAR_MAXMU") = KN_PARAM_BAR_MAXMU;
	KN.attr("PARAM_BAR_GLOBALIZE") = KN_PARAM_BAR_GLOBALIZE;
	KN.attr("PARAM_LINSOLVER_SCALING") = KN_PARAM_LINSOLVER_SCALING;
	KN.attr("PARAM_INITPT_STRATEGY") = KN_PARAM_INITPT_STRATEGY;
	KN.attr("PARAM_EVAL_COST") = KN_PARAM_EVAL_COST;
	KN.attr("PARAM_MS_TERMINATERULE_TOL") = KN_PARAM_MS_TERMINATERULE_TOL;
	KN.attr("PARAM_SOLTYPE") = KN_PARAM_SOLTYPE;
	KN.attr("PARAM_MAXTIME") = KN_PARAM_MAXTIME;
	KN.attr("PARAM_LP_ALGORITHM") = KN_PARAM_LP_ALGORITHM;
	KN.attr("PARAM_LP_ALG") = KN_PARAM_LP_ALG;
	KN.attr("PARAM_AL_INITPENALTY") = KN_PARAM_AL_INITPENALTY;
	KN.attr("PARAM_AL_MAXPENALTY") = KN_PARAM_AL_MAXPENALTY;
	KN.attr("PARAM_PRESOLVEOP_PROBING") = KN_PARAM_PRESOLVEOP_PROBING;

	// Algorithm values
	KN.attr("ALG_AUTOMATIC") = KN_ALG_AUTOMATIC;
	KN.attr("ALG_AUTO") = KN_ALG_AUTO;
	KN.attr("ALG_BAR_DIRECT") = KN_ALG_BAR_DIRECT;
	KN.attr("ALG_BAR_CG") = KN_ALG_BAR_CG;
	KN.attr("ALG_ACT_CG") = KN_ALG_ACT_CG;
	KN.attr("ALG_ACT_SQP") = KN_ALG_ACT_SQP;
	KN.attr("ALG_MULTI") = KN_ALG_MULTI;
	KN.attr("ALG_AL") = KN_ALG_AL;

	// NLP Algorithm values
	KN.attr("NLP_ALG_AUTOMATIC") = KN_NLP_ALG_AUTOMATIC;
	KN.attr("NLP_ALG_AUTO") = KN_NLP_ALG_AUTO;
	KN.attr("NLP_ALG_BAR_DIRECT") = KN_NLP_ALG_BAR_DIRECT;
	KN.attr("NLP_ALG_BAR_CG") = KN_NLP_ALG_BAR_CG;
	KN.attr("NLP_ALG_ACT_CG") = KN_NLP_ALG_ACT_CG;
	KN.attr("NLP_ALG_ACT_SQP") = KN_NLP_ALG_ACT_SQP;
	KN.attr("NLP_ALG_MULTI") = KN_NLP_ALG_MULTI;
	KN.attr("NLP_ALG_AL") = KN_NLP_ALG_AL;

	// Bar murule values
	KN.attr("BAR_MURULE_AUTOMATIC") = KN_BAR_MURULE_AUTOMATIC;
	KN.attr("BAR_MURULE_AUTO") = KN_BAR_MURULE_AUTO;
	KN.attr("BAR_MURULE_MONOTONE") = KN_BAR_MURULE_MONOTONE;
	KN.attr("BAR_MURULE_ADAPTIVE") = KN_BAR_MURULE_ADAPTIVE;
	KN.attr("BAR_MURULE_PROBING") = KN_BAR_MURULE_PROBING;
	KN.attr("BAR_MURULE_DAMPMPC") = KN_BAR_MURULE_DAMPMPC;
	KN.attr("BAR_MURULE_FULLMPC") = KN_BAR_MURULE_FULLMPC;
	KN.attr("BAR_MURULE_QUALITY") = KN_BAR_MURULE_QUALITY;

	// Gradient options
	KN.attr("GRADOPT_EXACT") = KN_GRADOPT_EXACT;
	KN.attr("GRADOPT_FORWARD") = KN_GRADOPT_FORWARD;
	KN.attr("GRADOPT_CENTRAL") = KN_GRADOPT_CENTRAL;
	KN.attr("GRADOPT_USER_FORWARD") = KN_GRADOPT_USER_FORWARD;
	KN.attr("GRADOPT_USER_CENTRAL") = KN_GRADOPT_USER_CENTRAL;

	// Hessian options
	KN.attr("HESSOPT_AUTO") = KN_HESSOPT_AUTO;
	KN.attr("HESSOPT_EXACT") = KN_HESSOPT_EXACT;
	KN.attr("HESSOPT_BFGS") = KN_HESSOPT_BFGS;
	KN.attr("HESSOPT_SR1") = KN_HESSOPT_SR1;
	KN.attr("HESSOPT_PRODUCT_FINDIFF") = KN_HESSOPT_PRODUCT_FINDIFF;
	KN.attr("HESSOPT_PRODUCT") = KN_HESSOPT_PRODUCT;
	KN.attr("HESSOPT_LBFGS") = KN_HESSOPT_LBFGS;
	KN.attr("HESSOPT_GAUSS_NEWTON") = KN_HESSOPT_GAUSS_NEWTON;

	// Output level values
	KN.attr("OUTLEV_NONE") = KN_OUTLEV_NONE;
	KN.attr("OUTLEV_SUMMARY") = KN_OUTLEV_SUMMARY;
	KN.attr("OUTLEV_ITER_10") = KN_OUTLEV_ITER_10;
	KN.attr("OUTLEV_ITER") = KN_OUTLEV_ITER;
	KN.attr("OUTLEV_ITER_VERBOSE") = KN_OUTLEV_ITER_VERBOSE;
	KN.attr("OUTLEV_ITER_X") = KN_OUTLEV_ITER_X;
	KN.attr("OUTLEV_ALL") = KN_OUTLEV_ALL;

	// Linear solver values
	KN.attr("LINSOLVER_AUTO") = KN_LINSOLVER_AUTO;
	KN.attr("LINSOLVER_INTERNAL") = KN_LINSOLVER_INTERNAL;
	KN.attr("LINSOLVER_HYBRID") = KN_LINSOLVER_HYBRID;
	KN.attr("LINSOLVER_DENSEQR") = KN_LINSOLVER_DENSEQR;
	KN.attr("LINSOLVER_MA27") = KN_LINSOLVER_MA27;
	KN.attr("LINSOLVER_MA57") = KN_LINSOLVER_MA57;
	KN.attr("LINSOLVER_MKLPARDISO") = KN_LINSOLVER_MKLPARDISO;
	KN.attr("LINSOLVER_MA97") = KN_LINSOLVER_MA97;
	KN.attr("LINSOLVER_MA86") = KN_LINSOLVER_MA86;
	KN.attr("LINSOLVER_APPLE") = KN_LINSOLVER_APPLE;

	// Presolve values
	KN.attr("PRESOLVE_NO") = KN_PRESOLVE_NO;
	KN.attr("PRESOLVE_YES") = KN_PRESOLVE_YES;

	// Derivative check values
	KN.attr("DERIVCHECK_NONE") = KN_DERIVCHECK_NONE;
	KN.attr("DERIVCHECK_FIRST") = KN_DERIVCHECK_FIRST;
	KN.attr("DERIVCHECK_SECOND") = KN_DERIVCHECK_SECOND;
	KN.attr("DERIVCHECK_ALL") = KN_DERIVCHECK_ALL;

	// Linesearch values
	KN.attr("LINESEARCH_AUTO") = KN_LINESEARCH_AUTO;
	KN.attr("LINESEARCH_BACKTRACK") = KN_LINESEARCH_BACKTRACK;
	KN.attr("LINESEARCH_INTERPOLATE") = KN_LINESEARCH_INTERPOLATE;
	KN.attr("LINESEARCH_WEAKWOLFE") = KN_LINESEARCH_WEAKWOLFE;

	// LP Algorithm values
	KN.attr("LP_ALG_AUTO") = KN_LP_ALG_AUTO;
	KN.attr("LP_ALG_NLPALGORITHM") = KN_LP_ALG_NLPALGORITHM;
	KN.attr("LP_ALG_PRIMALSIMPLEX") = KN_LP_ALG_PRIMALSIMPLEX;
	KN.attr("LP_ALG_DUALSIMPLEX") = KN_LP_ALG_DUALSIMPLEX;
	KN.attr("LP_ALG_BARRIER") = KN_LP_ALG_BARRIER;
	KN.attr("LP_ALG_PDLP") = KN_LP_ALG_PDLP;

	// MIP parameter IDs
	KN.attr("PARAM_MIP_METHOD") = KN_PARAM_MIP_METHOD;
	KN.attr("PARAM_MIP_BRANCHRULE") = KN_PARAM_MIP_BRANCHRULE;
	KN.attr("PARAM_MIP_SELECTRULE") = KN_PARAM_MIP_SELECTRULE;
	KN.attr("PARAM_MIP_OPTGAPABS") = KN_PARAM_MIP_OPTGAPABS;
	KN.attr("PARAM_MIP_OPTGAPREL") = KN_PARAM_MIP_OPTGAPREL;
	KN.attr("PARAM_MIP_MAXTIMECPU") = KN_PARAM_MIP_MAXTIMECPU;
	KN.attr("PARAM_MIP_MAXTIMEREAL") = KN_PARAM_MIP_MAXTIMEREAL;
	KN.attr("PARAM_MIP_MAXSOLVES") = KN_PARAM_MIP_MAXSOLVES;
	KN.attr("PARAM_MIP_INTEGERTOL") = KN_PARAM_MIP_INTEGERTOL;
	KN.attr("PARAM_MIP_OUTLEVEL") = KN_PARAM_MIP_OUTLEVEL;
	KN.attr("PARAM_MIP_OUTINTERVAL") = KN_PARAM_MIP_OUTINTERVAL;
	KN.attr("PARAM_MIP_OUTSUB") = KN_PARAM_MIP_OUTSUB;
	KN.attr("PARAM_MIP_DEBUG") = KN_PARAM_MIP_DEBUG;
	KN.attr("PARAM_MIP_IMPLICATIONS") = KN_PARAM_MIP_IMPLICATIONS;
	KN.attr("PARAM_MIP_GUB_BRANCH") = KN_PARAM_MIP_GUB_BRANCH;
	KN.attr("PARAM_MIP_KNAPSACK") = KN_PARAM_MIP_KNAPSACK;
	KN.attr("PARAM_MIP_ROUNDING") = KN_PARAM_MIP_ROUNDING;
	KN.attr("PARAM_MIP_ROOT_NLPALG") = KN_PARAM_MIP_ROOT_NLPALG;
	KN.attr("PARAM_MIP_TERMINATE") = KN_PARAM_MIP_TERMINATE;
	KN.attr("PARAM_MIP_MAXNODES") = KN_PARAM_MIP_MAXNODES;
	KN.attr("PARAM_MIP_HEUR_MAXIT") = KN_PARAM_MIP_HEUR_MAXIT;
	KN.attr("PARAM_MIP_PSEUDOINIT") = KN_PARAM_MIP_PSEUDOINIT;
	KN.attr("PARAM_MIP_STRONG_MAXIT") = KN_PARAM_MIP_STRONG_MAXIT;
	KN.attr("PARAM_MIP_STRONG_CANDLIM") = KN_PARAM_MIP_STRONG_CANDLIM;
	KN.attr("PARAM_MIP_STRONG_LEVEL") = KN_PARAM_MIP_STRONG_LEVEL;
	KN.attr("PARAM_MIP_INTVAR_STRATEGY") = KN_PARAM_MIP_INTVAR_STRATEGY;
	KN.attr("PARAM_MIP_RELAXABLE") = KN_PARAM_MIP_RELAXABLE;
	KN.attr("PARAM_MIP_NODE_NLPALG") = KN_PARAM_MIP_NODE_NLPALG;
	KN.attr("PARAM_MIP_HEUR_TERMINATE") = KN_PARAM_MIP_HEUR_TERMINATE;
	KN.attr("PARAM_MIP_SELECTDIR") = KN_PARAM_MIP_SELECTDIR;
	KN.attr("PARAM_MIP_CUTFACTOR") = KN_PARAM_MIP_CUTFACTOR;
	KN.attr("PARAM_MIP_ZEROHALF") = KN_PARAM_MIP_ZEROHALF;
	KN.attr("PARAM_MIP_MIR") = KN_PARAM_MIP_MIR;
	KN.attr("PARAM_MIP_CLIQUE") = KN_PARAM_MIP_CLIQUE;
	KN.attr("PARAM_MIP_HEUR_STRATEGY") = KN_PARAM_MIP_HEUR_STRATEGY;
	KN.attr("PARAM_MIP_HEUR_FEASPUMP") = KN_PARAM_MIP_HEUR_FEASPUMP;
	KN.attr("PARAM_MIP_HEUR_MPEC") = KN_PARAM_MIP_HEUR_MPEC;
	KN.attr("PARAM_MIP_HEUR_DIVING") = KN_PARAM_MIP_HEUR_DIVING;
	KN.attr("PARAM_MIP_CUTTINGPLANE") = KN_PARAM_MIP_CUTTINGPLANE;
	KN.attr("PARAM_MIP_CUTOFF") = KN_PARAM_MIP_CUTOFF;
	KN.attr("PARAM_MIP_HEUR_LNS") = KN_PARAM_MIP_HEUR_LNS;
	KN.attr("PARAM_MIP_MULTISTART") = KN_PARAM_MIP_MULTISTART;
	KN.attr("PARAM_MIP_LIFTPROJECT") = KN_PARAM_MIP_LIFTPROJECT;
	KN.attr("PARAM_MIP_NUMTHREADS") = KN_PARAM_MIP_NUMTHREADS;
	KN.attr("PARAM_MIP_HEUR_MISQP") = KN_PARAM_MIP_HEUR_MISQP;
	KN.attr("PARAM_MIP_RESTART") = KN_PARAM_MIP_RESTART;
	KN.attr("PARAM_MIP_GOMORY") = KN_PARAM_MIP_GOMORY;
	KN.attr("PARAM_MIP_CUT_PROBING") = KN_PARAM_MIP_CUT_PROBING;
	KN.attr("PARAM_MIP_CUT_FLOWCOVER") = KN_PARAM_MIP_CUT_FLOWCOVER;
	KN.attr("PARAM_MIP_HEUR_LOCALSEARCH") = KN_PARAM_MIP_HEUR_LOCALSEARCH;
	KN.attr("PARAM_MIP_ROOT_LPALG") = KN_PARAM_MIP_ROOT_LPALG;
	KN.attr("PARAM_MIP_NODE_LPALG") = KN_PARAM_MIP_NODE_LPALG;

	// MIP method values
	KN.attr("MIP_METHOD_AUTO") = KN_MIP_METHOD_AUTO;
	KN.attr("MIP_METHOD_BB") = KN_MIP_METHOD_BB;
	KN.attr("MIP_METHOD_HQG") = KN_MIP_METHOD_HQG;
	KN.attr("MIP_METHOD_MISQP") = KN_MIP_METHOD_MISQP;

	// MIP branch rule values
	KN.attr("MIP_BRANCH_AUTO") = KN_MIP_BRANCH_AUTO;
	KN.attr("MIP_BRANCH_MOSTFRAC") = KN_MIP_BRANCH_MOSTFRAC;
	KN.attr("MIP_BRANCH_PSEUDOCOST") = KN_MIP_BRANCH_PSEUDOCOST;
	KN.attr("MIP_BRANCH_STRONG") = KN_MIP_BRANCH_STRONG;

	// MIP select rule values
	KN.attr("MIP_SEL_AUTO") = KN_MIP_SEL_AUTO;
	KN.attr("MIP_SEL_DEPTHFIRST") = KN_MIP_SEL_DEPTHFIRST;
	KN.attr("MIP_SEL_BESTBOUND") = KN_MIP_SEL_BESTBOUND;
	KN.attr("MIP_SEL_COMBO_1") = KN_MIP_SEL_COMBO_1;

	// MIP terminate values
	KN.attr("MIP_TERMINATE_OPTIMAL") = KN_MIP_TERMINATE_OPTIMAL;
	KN.attr("MIP_TERMINATE_FEASIBLE") = KN_MIP_TERMINATE_FEASIBLE;

	// MIP output level values
	KN.attr("MIP_OUTLEVEL_NONE") = KN_MIP_OUTLEVEL_NONE;
	KN.attr("MIP_OUTLEVEL_ITERS") = KN_MIP_OUTLEVEL_ITERS;
	KN.attr("MIP_OUTLEVEL_ITERSTIME") = KN_MIP_OUTLEVEL_ITERSTIME;
	KN.attr("MIP_OUTLEVEL_ROOT") = KN_MIP_OUTLEVEL_ROOT;

	// MIP rounding values
	KN.attr("MIP_ROUND_AUTO") = KN_MIP_ROUND_AUTO;
	KN.attr("MIP_ROUND_NONE") = KN_MIP_ROUND_NONE;
	KN.attr("MIP_ROUND_HEURISTIC") = KN_MIP_ROUND_HEURISTIC;
	KN.attr("MIP_ROUND_NLP_SOME") = KN_MIP_ROUND_NLP_SOME;
	KN.attr("MIP_ROUND_NLP_ALWAYS") = KN_MIP_ROUND_NLP_ALWAYS;

	// MIP heuristic strategy values
	KN.attr("MIP_HEUR_STRATEGY_AUTO") = KN_MIP_HEUR_STRATEGY_AUTO;
	KN.attr("MIP_HEUR_STRATEGY_NONE") = KN_MIP_HEUR_STRATEGY_NONE;
	KN.attr("MIP_HEUR_STRATEGY_BASIC") = KN_MIP_HEUR_STRATEGY_BASIC;
	KN.attr("MIP_HEUR_STRATEGY_ADVANCED") = KN_MIP_HEUR_STRATEGY_ADVANCED;
	KN.attr("MIP_HEUR_STRATEGY_EXTENSIVE") = KN_MIP_HEUR_STRATEGY_EXTENSIVE;
}
