#include <nanobind/nanobind.h>

#include "pyoptinterface/xpress_model.hpp"

namespace nb = nanobind;
using namespace xpress;

void bind_xpress_constants(nb::module_ &m)
{
	nb::module_ XPRS = m.def_submodule("XPRS");
	/* useful constants */
	XPRS.attr("PLUSINFINITY") = POI_XPRS_PLUSINFINITY;
	XPRS.attr("MINUSINFINITY") = POI_XPRS_MINUSINFINITY;
	XPRS.attr("MAXINT") = POI_XPRS_MAXINT;
	XPRS.attr("MAXBANNERLENGTH") = POI_XPRS_MAXBANNERLENGTH;
	XPRS.attr("VERSION") = POI_XPVERSION;
	XPRS.attr("VERSION_MAJOR") = POI_XPVERSION_FULL;
	XPRS.attr("VERSION_MINOR") = POI_XPVERSION_BUILD;
	XPRS.attr("VERSION_BUILD") = POI_XPVERSION_MINOR;
	XPRS.attr("VERSION_FULL") = POI_XPVERSION_MAJOR;
	XPRS.attr("MAXMESSAGELENGTH") = POI_XPRS_MAXMESSAGELENGTH;

	/* control parameters for XPRSprob */
	/* String control parameters */
	XPRS.attr("MPSRHSNAME") = POI_XPRS_MPSRHSNAME;
	XPRS.attr("MPSOBJNAME") = POI_XPRS_MPSOBJNAME;
	XPRS.attr("MPSRANGENAME") = POI_XPRS_MPSRANGENAME;
	XPRS.attr("MPSBOUNDNAME") = POI_XPRS_MPSBOUNDNAME;
	XPRS.attr("OUTPUTMASK") = POI_XPRS_OUTPUTMASK;
	XPRS.attr("TUNERMETHODFILE") = POI_XPRS_TUNERMETHODFILE;
	XPRS.attr("TUNEROUTPUTPATH") = POI_XPRS_TUNEROUTPUTPATH;
	XPRS.attr("TUNERSESSIONNAME") = POI_XPRS_TUNERSESSIONNAME;
	XPRS.attr("COMPUTEEXECSERVICE") = POI_XPRS_COMPUTEEXECSERVICE;
	/* Double control parameters */
	XPRS.attr("MAXCUTTIME") = POI_XPRS_MAXCUTTIME;
	XPRS.attr("MAXSTALLTIME") = POI_XPRS_MAXSTALLTIME;
	XPRS.attr("TUNERMAXTIME") = POI_XPRS_TUNERMAXTIME;
	XPRS.attr("MATRIXTOL") = POI_XPRS_MATRIXTOL;
	XPRS.attr("PIVOTTOL") = POI_XPRS_PIVOTTOL;
	XPRS.attr("FEASTOL") = POI_XPRS_FEASTOL;
	XPRS.attr("OUTPUTTOL") = POI_XPRS_OUTPUTTOL;
	XPRS.attr("SOSREFTOL") = POI_XPRS_SOSREFTOL;
	XPRS.attr("OPTIMALITYTOL") = POI_XPRS_OPTIMALITYTOL;
	XPRS.attr("ETATOL") = POI_XPRS_ETATOL;
	XPRS.attr("RELPIVOTTOL") = POI_XPRS_RELPIVOTTOL;
	XPRS.attr("MIPTOL") = POI_XPRS_MIPTOL;
	XPRS.attr("MIPTOLTARGET") = POI_XPRS_MIPTOLTARGET;
	XPRS.attr("BARPERTURB") = POI_XPRS_BARPERTURB;
	XPRS.attr("MIPADDCUTOFF") = POI_XPRS_MIPADDCUTOFF;
	XPRS.attr("MIPABSCUTOFF") = POI_XPRS_MIPABSCUTOFF;
	XPRS.attr("MIPRELCUTOFF") = POI_XPRS_MIPRELCUTOFF;
	XPRS.attr("PSEUDOCOST") = POI_XPRS_PSEUDOCOST;
	XPRS.attr("PENALTY") = POI_XPRS_PENALTY;
	XPRS.attr("BIGM") = POI_XPRS_BIGM;
	XPRS.attr("MIPABSSTOP") = POI_XPRS_MIPABSSTOP;
	XPRS.attr("MIPRELSTOP") = POI_XPRS_MIPRELSTOP;
	XPRS.attr("CROSSOVERACCURACYTOL") = POI_XPRS_CROSSOVERACCURACYTOL;
	XPRS.attr("PRIMALPERTURB") = POI_XPRS_PRIMALPERTURB;
	XPRS.attr("DUALPERTURB") = POI_XPRS_DUALPERTURB;
	XPRS.attr("BAROBJSCALE") = POI_XPRS_BAROBJSCALE;
	XPRS.attr("BARRHSSCALE") = POI_XPRS_BARRHSSCALE;
	XPRS.attr("CHOLESKYTOL") = POI_XPRS_CHOLESKYTOL;
	XPRS.attr("BARGAPSTOP") = POI_XPRS_BARGAPSTOP;
	XPRS.attr("BARDUALSTOP") = POI_XPRS_BARDUALSTOP;
	XPRS.attr("BARPRIMALSTOP") = POI_XPRS_BARPRIMALSTOP;
	XPRS.attr("BARSTEPSTOP") = POI_XPRS_BARSTEPSTOP;
	XPRS.attr("ELIMTOL") = POI_XPRS_ELIMTOL;
	XPRS.attr("MARKOWITZTOL") = POI_XPRS_MARKOWITZTOL;
	XPRS.attr("MIPABSGAPNOTIFY") = POI_XPRS_MIPABSGAPNOTIFY;
	XPRS.attr("MIPRELGAPNOTIFY") = POI_XPRS_MIPRELGAPNOTIFY;
	XPRS.attr("BARLARGEBOUND") = POI_XPRS_BARLARGEBOUND;
	XPRS.attr("PPFACTOR") = POI_XPRS_PPFACTOR;
	XPRS.attr("REPAIRINDEFINITEQMAX") = POI_XPRS_REPAIRINDEFINITEQMAX;
	XPRS.attr("BARGAPTARGET") = POI_XPRS_BARGAPTARGET;
	XPRS.attr("DUMMYCONTROL") = POI_XPRS_DUMMYCONTROL;
	XPRS.attr("BARSTARTWEIGHT") = POI_XPRS_BARSTARTWEIGHT;
	XPRS.attr("BARFREESCALE") = POI_XPRS_BARFREESCALE;
	XPRS.attr("SBEFFORT") = POI_XPRS_SBEFFORT;
	XPRS.attr("HEURDIVERANDOMIZE") = POI_XPRS_HEURDIVERANDOMIZE;
	XPRS.attr("HEURSEARCHEFFORT") = POI_XPRS_HEURSEARCHEFFORT;
	XPRS.attr("CUTFACTOR") = POI_XPRS_CUTFACTOR;
	XPRS.attr("EIGENVALUETOL") = POI_XPRS_EIGENVALUETOL;
	XPRS.attr("INDLINBIGM") = POI_XPRS_INDLINBIGM;
	XPRS.attr("TREEMEMORYSAVINGTARGET") = POI_XPRS_TREEMEMORYSAVINGTARGET;
	XPRS.attr("INDPRELINBIGM") = POI_XPRS_INDPRELINBIGM;
	XPRS.attr("RELAXTREEMEMORYLIMIT") = POI_XPRS_RELAXTREEMEMORYLIMIT;
	XPRS.attr("MIPABSGAPNOTIFYOBJ") = POI_XPRS_MIPABSGAPNOTIFYOBJ;
	XPRS.attr("MIPABSGAPNOTIFYBOUND") = POI_XPRS_MIPABSGAPNOTIFYBOUND;
	XPRS.attr("PRESOLVEMAXGROW") = POI_XPRS_PRESOLVEMAXGROW;
	XPRS.attr("HEURSEARCHTARGETSIZE") = POI_XPRS_HEURSEARCHTARGETSIZE;
	XPRS.attr("CROSSOVERRELPIVOTTOL") = POI_XPRS_CROSSOVERRELPIVOTTOL;
	XPRS.attr("CROSSOVERRELPIVOTTOLSAFE") = POI_XPRS_CROSSOVERRELPIVOTTOLSAFE;
	XPRS.attr("DETLOGFREQ") = POI_XPRS_DETLOGFREQ;
	XPRS.attr("MAXIMPLIEDBOUND") = POI_XPRS_MAXIMPLIEDBOUND;
	XPRS.attr("FEASTOLTARGET") = POI_XPRS_FEASTOLTARGET;
	XPRS.attr("OPTIMALITYTOLTARGET") = POI_XPRS_OPTIMALITYTOLTARGET;
	XPRS.attr("PRECOMPONENTSEFFORT") = POI_XPRS_PRECOMPONENTSEFFORT;
	XPRS.attr("LPLOGDELAY") = POI_XPRS_LPLOGDELAY;
	XPRS.attr("HEURDIVEITERLIMIT") = POI_XPRS_HEURDIVEITERLIMIT;
	XPRS.attr("BARKERNEL") = POI_XPRS_BARKERNEL;
	XPRS.attr("FEASTOLPERTURB") = POI_XPRS_FEASTOLPERTURB;
	XPRS.attr("CROSSOVERFEASWEIGHT") = POI_XPRS_CROSSOVERFEASWEIGHT;
	XPRS.attr("LUPIVOTTOL") = POI_XPRS_LUPIVOTTOL;
	XPRS.attr("MIPRESTARTGAPTHRESHOLD") = POI_XPRS_MIPRESTARTGAPTHRESHOLD;
	XPRS.attr("NODEPROBINGEFFORT") = POI_XPRS_NODEPROBINGEFFORT;
	XPRS.attr("INPUTTOL") = POI_XPRS_INPUTTOL;
	XPRS.attr("MIPRESTARTFACTOR") = POI_XPRS_MIPRESTARTFACTOR;
	XPRS.attr("BAROBJPERTURB") = POI_XPRS_BAROBJPERTURB;
	XPRS.attr("CPIALPHA") = POI_XPRS_CPIALPHA;
	XPRS.attr("GLOBALSPATIALBRANCHPROPAGATIONEFFORT") =
	    POI_XPRS_GLOBALSPATIALBRANCHPROPAGATIONEFFORT;
	XPRS.attr("GLOBALSPATIALBRANCHCUTTINGEFFORT") = POI_XPRS_GLOBALSPATIALBRANCHCUTTINGEFFORT;
	XPRS.attr("GLOBALBOUNDINGBOX") = POI_XPRS_GLOBALBOUNDINGBOX;
	XPRS.attr("TIMELIMIT") = POI_XPRS_TIMELIMIT;
	XPRS.attr("SOLTIMELIMIT") = POI_XPRS_SOLTIMELIMIT;
	XPRS.attr("REPAIRINFEASTIMELIMIT") = POI_XPRS_REPAIRINFEASTIMELIMIT;
	XPRS.attr("BARHGEXTRAPOLATE") = POI_XPRS_BARHGEXTRAPOLATE;
	XPRS.attr("WORKLIMIT") = POI_XPRS_WORKLIMIT;
	XPRS.attr("CALLBACKCHECKTIMEWORKDELAY") = POI_XPRS_CALLBACKCHECKTIMEWORKDELAY;
	XPRS.attr("PREROOTWORKLIMIT") = POI_XPRS_PREROOTWORKLIMIT;
	XPRS.attr("PREROOTEFFORT") = POI_XPRS_PREROOTEFFORT;
	/* Integer control parameters */
	XPRS.attr("EXTRAROWS") = POI_XPRS_EXTRAROWS;
	XPRS.attr("EXTRACOLS") = POI_XPRS_EXTRACOLS;
	XPRS.attr("LPITERLIMIT") = POI_XPRS_LPITERLIMIT;
	XPRS.attr("LPLOG") = POI_XPRS_LPLOG;
	XPRS.attr("SCALING") = POI_XPRS_SCALING;
	XPRS.attr("PRESOLVE") = POI_XPRS_PRESOLVE;
	XPRS.attr("CRASH") = POI_XPRS_CRASH;
	XPRS.attr("PRICINGALG") = POI_XPRS_PRICINGALG;
	XPRS.attr("INVERTFREQ") = POI_XPRS_INVERTFREQ;
	XPRS.attr("INVERTMIN") = POI_XPRS_INVERTMIN;
	XPRS.attr("MAXNODE") = POI_XPRS_MAXNODE;
	XPRS.attr("MAXMIPSOL") = POI_XPRS_MAXMIPSOL;
	XPRS.attr("SIFTPASSES") = POI_XPRS_SIFTPASSES;
	XPRS.attr("DEFAULTALG") = POI_XPRS_DEFAULTALG;
	XPRS.attr("VARSELECTION") = POI_XPRS_VARSELECTION;
	XPRS.attr("NODESELECTION") = POI_XPRS_NODESELECTION;
	XPRS.attr("BACKTRACK") = POI_XPRS_BACKTRACK;
	XPRS.attr("MIPLOG") = POI_XPRS_MIPLOG;
	XPRS.attr("KEEPNROWS") = POI_XPRS_KEEPNROWS;
	XPRS.attr("MPSECHO") = POI_XPRS_MPSECHO;
	XPRS.attr("MAXPAGELINES") = POI_XPRS_MAXPAGELINES;
	XPRS.attr("OUTPUTLOG") = POI_XPRS_OUTPUTLOG;
	XPRS.attr("BARSOLUTION") = POI_XPRS_BARSOLUTION;
	XPRS.attr("CROSSOVER") = POI_XPRS_CROSSOVER;
	XPRS.attr("BARITERLIMIT") = POI_XPRS_BARITERLIMIT;
	XPRS.attr("CHOLESKYALG") = POI_XPRS_CHOLESKYALG;
	XPRS.attr("BAROUTPUT") = POI_XPRS_BAROUTPUT;
	XPRS.attr("EXTRAMIPENTS") = POI_XPRS_EXTRAMIPENTS;
	XPRS.attr("REFACTOR") = POI_XPRS_REFACTOR;
	XPRS.attr("BARTHREADS") = POI_XPRS_BARTHREADS;
	XPRS.attr("KEEPBASIS") = POI_XPRS_KEEPBASIS;
	XPRS.attr("CROSSOVEROPS") = POI_XPRS_CROSSOVEROPS;
	XPRS.attr("VERSION") = POI_XPRS_VERSION;
	XPRS.attr("CROSSOVERTHREADS") = POI_XPRS_CROSSOVERTHREADS;
	XPRS.attr("BIGMMETHOD") = POI_XPRS_BIGMMETHOD;
	XPRS.attr("MPSNAMELENGTH") = POI_XPRS_MPSNAMELENGTH;
	XPRS.attr("ELIMFILLIN") = POI_XPRS_ELIMFILLIN;
	XPRS.attr("PRESOLVEOPS") = POI_XPRS_PRESOLVEOPS;
	XPRS.attr("MIPPRESOLVE") = POI_XPRS_MIPPRESOLVE;
	XPRS.attr("MIPTHREADS") = POI_XPRS_MIPTHREADS;
	XPRS.attr("BARORDER") = POI_XPRS_BARORDER;
	XPRS.attr("BREADTHFIRST") = POI_XPRS_BREADTHFIRST;
	XPRS.attr("AUTOPERTURB") = POI_XPRS_AUTOPERTURB;
	XPRS.attr("DENSECOLLIMIT") = POI_XPRS_DENSECOLLIMIT;
	XPRS.attr("CALLBACKFROMMAINTHREAD") = POI_XPRS_CALLBACKFROMMAINTHREAD;
	XPRS.attr("MAXMCOEFFBUFFERELEMS") = POI_XPRS_MAXMCOEFFBUFFERELEMS;
	XPRS.attr("REFINEOPS") = POI_XPRS_REFINEOPS;
	XPRS.attr("LPREFINEITERLIMIT") = POI_XPRS_LPREFINEITERLIMIT;
	XPRS.attr("MIPREFINEITERLIMIT") = POI_XPRS_MIPREFINEITERLIMIT;
	XPRS.attr("DUALIZEOPS") = POI_XPRS_DUALIZEOPS;
	XPRS.attr("CROSSOVERITERLIMIT") = POI_XPRS_CROSSOVERITERLIMIT;
	XPRS.attr("PREBASISRED") = POI_XPRS_PREBASISRED;
	XPRS.attr("PRESORT") = POI_XPRS_PRESORT;
	XPRS.attr("PREPERMUTE") = POI_XPRS_PREPERMUTE;
	XPRS.attr("PREPERMUTESEED") = POI_XPRS_PREPERMUTESEED;
	XPRS.attr("MAXMEMORYSOFT") = POI_XPRS_MAXMEMORYSOFT;
	XPRS.attr("CUTFREQ") = POI_XPRS_CUTFREQ;
	XPRS.attr("SYMSELECT") = POI_XPRS_SYMSELECT;
	XPRS.attr("SYMMETRY") = POI_XPRS_SYMMETRY;
	XPRS.attr("MAXMEMORYHARD") = POI_XPRS_MAXMEMORYHARD;
	XPRS.attr("MIQCPALG") = POI_XPRS_MIQCPALG;
	XPRS.attr("QCCUTS") = POI_XPRS_QCCUTS;
	XPRS.attr("QCROOTALG") = POI_XPRS_QCROOTALG;
	XPRS.attr("PRECONVERTSEPARABLE") = POI_XPRS_PRECONVERTSEPARABLE;
	XPRS.attr("ALGAFTERNETWORK") = POI_XPRS_ALGAFTERNETWORK;
	XPRS.attr("TRACE") = POI_XPRS_TRACE;
	XPRS.attr("MAXIIS") = POI_XPRS_MAXIIS;
	XPRS.attr("CPUTIME") = POI_XPRS_CPUTIME;
	XPRS.attr("COVERCUTS") = POI_XPRS_COVERCUTS;
	XPRS.attr("GOMCUTS") = POI_XPRS_GOMCUTS;
	XPRS.attr("LPFOLDING") = POI_XPRS_LPFOLDING;
	XPRS.attr("MPSFORMAT") = POI_XPRS_MPSFORMAT;
	XPRS.attr("CUTSTRATEGY") = POI_XPRS_CUTSTRATEGY;
	XPRS.attr("CUTDEPTH") = POI_XPRS_CUTDEPTH;
	XPRS.attr("TREECOVERCUTS") = POI_XPRS_TREECOVERCUTS;
	XPRS.attr("TREEGOMCUTS") = POI_XPRS_TREEGOMCUTS;
	XPRS.attr("CUTSELECT") = POI_XPRS_CUTSELECT;
	XPRS.attr("TREECUTSELECT") = POI_XPRS_TREECUTSELECT;
	XPRS.attr("DUALIZE") = POI_XPRS_DUALIZE;
	XPRS.attr("DUALGRADIENT") = POI_XPRS_DUALGRADIENT;
	XPRS.attr("SBITERLIMIT") = POI_XPRS_SBITERLIMIT;
	XPRS.attr("SBBEST") = POI_XPRS_SBBEST;
	XPRS.attr("BARINDEFLIMIT") = POI_XPRS_BARINDEFLIMIT;
	XPRS.attr("HEURFREQ") = POI_XPRS_HEURFREQ;
	XPRS.attr("HEURDEPTH") = POI_XPRS_HEURDEPTH;
	XPRS.attr("HEURMAXSOL") = POI_XPRS_HEURMAXSOL;
	XPRS.attr("HEURNODES") = POI_XPRS_HEURNODES;
	XPRS.attr("LNPBEST") = POI_XPRS_LNPBEST;
	XPRS.attr("LNPITERLIMIT") = POI_XPRS_LNPITERLIMIT;
	XPRS.attr("BRANCHCHOICE") = POI_XPRS_BRANCHCHOICE;
	XPRS.attr("BARREGULARIZE") = POI_XPRS_BARREGULARIZE;
	XPRS.attr("SBSELECT") = POI_XPRS_SBSELECT;
	XPRS.attr("IISLOG") = POI_XPRS_IISLOG;
	XPRS.attr("LOCALCHOICE") = POI_XPRS_LOCALCHOICE;
	XPRS.attr("LOCALBACKTRACK") = POI_XPRS_LOCALBACKTRACK;
	XPRS.attr("DUALSTRATEGY") = POI_XPRS_DUALSTRATEGY;
	XPRS.attr("HEURDIVESTRATEGY") = POI_XPRS_HEURDIVESTRATEGY;
	XPRS.attr("HEURSELECT") = POI_XPRS_HEURSELECT;
	XPRS.attr("BARSTART") = POI_XPRS_BARSTART;
	XPRS.attr("PRESOLVEPASSES") = POI_XPRS_PRESOLVEPASSES;
	XPRS.attr("BARORDERTHREADS") = POI_XPRS_BARORDERTHREADS;
	XPRS.attr("EXTRASETS") = POI_XPRS_EXTRASETS;
	XPRS.attr("FEASIBILITYPUMP") = POI_XPRS_FEASIBILITYPUMP;
	XPRS.attr("PRECOEFELIM") = POI_XPRS_PRECOEFELIM;
	XPRS.attr("PREDOMCOL") = POI_XPRS_PREDOMCOL;
	XPRS.attr("HEURSEARCHFREQ") = POI_XPRS_HEURSEARCHFREQ;
	XPRS.attr("HEURDIVESPEEDUP") = POI_XPRS_HEURDIVESPEEDUP;
	XPRS.attr("SBESTIMATE") = POI_XPRS_SBESTIMATE;
	XPRS.attr("BARCORES") = POI_XPRS_BARCORES;
	XPRS.attr("MAXCHECKSONMAXTIME") = POI_XPRS_MAXCHECKSONMAXTIME;
	XPRS.attr("MAXCHECKSONMAXCUTTIME") = POI_XPRS_MAXCHECKSONMAXCUTTIME;
	XPRS.attr("HISTORYCOSTS") = POI_XPRS_HISTORYCOSTS;
	XPRS.attr("ALGAFTERCROSSOVER") = POI_XPRS_ALGAFTERCROSSOVER;
	XPRS.attr("MUTEXCALLBACKS") = POI_XPRS_MUTEXCALLBACKS;
	XPRS.attr("BARCRASH") = POI_XPRS_BARCRASH;
	XPRS.attr("HEURDIVESOFTROUNDING") = POI_XPRS_HEURDIVESOFTROUNDING;
	XPRS.attr("HEURSEARCHROOTSELECT") = POI_XPRS_HEURSEARCHROOTSELECT;
	XPRS.attr("HEURSEARCHTREESELECT") = POI_XPRS_HEURSEARCHTREESELECT;
	XPRS.attr("MPS18COMPATIBLE") = POI_XPRS_MPS18COMPATIBLE;
	XPRS.attr("ROOTPRESOLVE") = POI_XPRS_ROOTPRESOLVE;
	XPRS.attr("CROSSOVERDRP") = POI_XPRS_CROSSOVERDRP;
	XPRS.attr("FORCEOUTPUT") = POI_XPRS_FORCEOUTPUT;
	XPRS.attr("PRIMALOPS") = POI_XPRS_PRIMALOPS;
	XPRS.attr("DETERMINISTIC") = POI_XPRS_DETERMINISTIC;
	XPRS.attr("PREPROBING") = POI_XPRS_PREPROBING;
	XPRS.attr("TREEMEMORYLIMIT") = POI_XPRS_TREEMEMORYLIMIT;
	XPRS.attr("TREECOMPRESSION") = POI_XPRS_TREECOMPRESSION;
	XPRS.attr("TREEDIAGNOSTICS") = POI_XPRS_TREEDIAGNOSTICS;
	XPRS.attr("MAXTREEFILESIZE") = POI_XPRS_MAXTREEFILESIZE;
	XPRS.attr("PRECLIQUESTRATEGY") = POI_XPRS_PRECLIQUESTRATEGY;
	XPRS.attr("IFCHECKCONVEXITY") = POI_XPRS_IFCHECKCONVEXITY;
	XPRS.attr("PRIMALUNSHIFT") = POI_XPRS_PRIMALUNSHIFT;
	XPRS.attr("REPAIRINDEFINITEQ") = POI_XPRS_REPAIRINDEFINITEQ;
	XPRS.attr("MIPRAMPUP") = POI_XPRS_MIPRAMPUP;
	XPRS.attr("MAXLOCALBACKTRACK") = POI_XPRS_MAXLOCALBACKTRACK;
	XPRS.attr("USERSOLHEURISTIC") = POI_XPRS_USERSOLHEURISTIC;
	XPRS.attr("PRECONVERTOBJTOCONS") = POI_XPRS_PRECONVERTOBJTOCONS;
	XPRS.attr("FORCEPARALLELDUAL") = POI_XPRS_FORCEPARALLELDUAL;
	XPRS.attr("BACKTRACKTIE") = POI_XPRS_BACKTRACKTIE;
	XPRS.attr("BRANCHDISJ") = POI_XPRS_BRANCHDISJ;
	XPRS.attr("MIPFRACREDUCE") = POI_XPRS_MIPFRACREDUCE;
	XPRS.attr("CONCURRENTTHREADS") = POI_XPRS_CONCURRENTTHREADS;
	XPRS.attr("MAXSCALEFACTOR") = POI_XPRS_MAXSCALEFACTOR;
	XPRS.attr("HEURTHREADS") = POI_XPRS_HEURTHREADS;
	XPRS.attr("THREADS") = POI_XPRS_THREADS;
	XPRS.attr("HEURBEFORELP") = POI_XPRS_HEURBEFORELP;
	XPRS.attr("PREDOMROW") = POI_XPRS_PREDOMROW;
	XPRS.attr("BRANCHSTRUCTURAL") = POI_XPRS_BRANCHSTRUCTURAL;
	XPRS.attr("QUADRATICUNSHIFT") = POI_XPRS_QUADRATICUNSHIFT;
	XPRS.attr("BARPRESOLVEOPS") = POI_XPRS_BARPRESOLVEOPS;
	XPRS.attr("QSIMPLEXOPS") = POI_XPRS_QSIMPLEXOPS;
	XPRS.attr("MIPRESTART") = POI_XPRS_MIPRESTART;
	XPRS.attr("CONFLICTCUTS") = POI_XPRS_CONFLICTCUTS;
	XPRS.attr("PREPROTECTDUAL") = POI_XPRS_PREPROTECTDUAL;
	XPRS.attr("CORESPERCPU") = POI_XPRS_CORESPERCPU;
	XPRS.attr("RESOURCESTRATEGY") = POI_XPRS_RESOURCESTRATEGY;
	XPRS.attr("CLAMPING") = POI_XPRS_CLAMPING;
	XPRS.attr("PREDUPROW") = POI_XPRS_PREDUPROW;
	XPRS.attr("CPUPLATFORM") = POI_XPRS_CPUPLATFORM;
	XPRS.attr("BARALG") = POI_XPRS_BARALG;
	XPRS.attr("SIFTING") = POI_XPRS_SIFTING;
	XPRS.attr("BARKEEPLASTSOL") = POI_XPRS_BARKEEPLASTSOL;
	XPRS.attr("LPLOGSTYLE") = POI_XPRS_LPLOGSTYLE;
	XPRS.attr("RANDOMSEED") = POI_XPRS_RANDOMSEED;
	XPRS.attr("TREEQCCUTS") = POI_XPRS_TREEQCCUTS;
	XPRS.attr("PRELINDEP") = POI_XPRS_PRELINDEP;
	XPRS.attr("DUALTHREADS") = POI_XPRS_DUALTHREADS;
	XPRS.attr("PREOBJCUTDETECT") = POI_XPRS_PREOBJCUTDETECT;
	XPRS.attr("PREBNDREDQUAD") = POI_XPRS_PREBNDREDQUAD;
	XPRS.attr("PREBNDREDCONE") = POI_XPRS_PREBNDREDCONE;
	XPRS.attr("PRECOMPONENTS") = POI_XPRS_PRECOMPONENTS;
	XPRS.attr("MAXMIPTASKS") = POI_XPRS_MAXMIPTASKS;
	XPRS.attr("MIPTERMINATIONMETHOD") = POI_XPRS_MIPTERMINATIONMETHOD;
	XPRS.attr("PRECONEDECOMP") = POI_XPRS_PRECONEDECOMP;
	XPRS.attr("HEURFORCESPECIALOBJ") = POI_XPRS_HEURFORCESPECIALOBJ;
	XPRS.attr("HEURSEARCHROOTCUTFREQ") = POI_XPRS_HEURSEARCHROOTCUTFREQ;
	XPRS.attr("PREELIMQUAD") = POI_XPRS_PREELIMQUAD;
	XPRS.attr("PREIMPLICATIONS") = POI_XPRS_PREIMPLICATIONS;
	XPRS.attr("TUNERMODE") = POI_XPRS_TUNERMODE;
	XPRS.attr("TUNERMETHOD") = POI_XPRS_TUNERMETHOD;
	XPRS.attr("TUNERTARGET") = POI_XPRS_TUNERTARGET;
	XPRS.attr("TUNERTHREADS") = POI_XPRS_TUNERTHREADS;
	XPRS.attr("TUNERHISTORY") = POI_XPRS_TUNERHISTORY;
	XPRS.attr("TUNERPERMUTE") = POI_XPRS_TUNERPERMUTE;
	XPRS.attr("TUNERVERBOSE") = POI_XPRS_TUNERVERBOSE;
	XPRS.attr("TUNEROUTPUT") = POI_XPRS_TUNEROUTPUT;
	XPRS.attr("PREANALYTICCENTER") = POI_XPRS_PREANALYTICCENTER;
	XPRS.attr("LPFLAGS") = POI_XPRS_LPFLAGS;
	XPRS.attr("MIPKAPPAFREQ") = POI_XPRS_MIPKAPPAFREQ;
	XPRS.attr("OBJSCALEFACTOR") = POI_XPRS_OBJSCALEFACTOR;
	XPRS.attr("TREEFILELOGINTERVAL") = POI_XPRS_TREEFILELOGINTERVAL;
	XPRS.attr("IGNORECONTAINERCPULIMIT") = POI_XPRS_IGNORECONTAINERCPULIMIT;
	XPRS.attr("IGNORECONTAINERMEMORYLIMIT") = POI_XPRS_IGNORECONTAINERMEMORYLIMIT;
	XPRS.attr("MIPDUALREDUCTIONS") = POI_XPRS_MIPDUALREDUCTIONS;
	XPRS.attr("GENCONSDUALREDUCTIONS") = POI_XPRS_GENCONSDUALREDUCTIONS;
	XPRS.attr("PWLDUALREDUCTIONS") = POI_XPRS_PWLDUALREDUCTIONS;
	XPRS.attr("BARFAILITERLIMIT") = POI_XPRS_BARFAILITERLIMIT;
	XPRS.attr("AUTOSCALING") = POI_XPRS_AUTOSCALING;
	XPRS.attr("GENCONSABSTRANSFORMATION") = POI_XPRS_GENCONSABSTRANSFORMATION;
	XPRS.attr("COMPUTEJOBPRIORITY") = POI_XPRS_COMPUTEJOBPRIORITY;
	XPRS.attr("PREFOLDING") = POI_XPRS_PREFOLDING;
	XPRS.attr("COMPUTE") = POI_XPRS_COMPUTE;
	XPRS.attr("NETSTALLLIMIT") = POI_XPRS_NETSTALLLIMIT;
	XPRS.attr("SERIALIZEPREINTSOL") = POI_XPRS_SERIALIZEPREINTSOL;
	XPRS.attr("NUMERICALEMPHASIS") = POI_XPRS_NUMERICALEMPHASIS;
	XPRS.attr("PWLNONCONVEXTRANSFORMATION") = POI_XPRS_PWLNONCONVEXTRANSFORMATION;
	XPRS.attr("MIPCOMPONENTS") = POI_XPRS_MIPCOMPONENTS;
	XPRS.attr("MIPCONCURRENTNODES") = POI_XPRS_MIPCONCURRENTNODES;
	XPRS.attr("MIPCONCURRENTSOLVES") = POI_XPRS_MIPCONCURRENTSOLVES;
	XPRS.attr("OUTPUTCONTROLS") = POI_XPRS_OUTPUTCONTROLS;
	XPRS.attr("SIFTSWITCH") = POI_XPRS_SIFTSWITCH;
	XPRS.attr("HEUREMPHASIS") = POI_XPRS_HEUREMPHASIS;
	XPRS.attr("BARREFITER") = POI_XPRS_BARREFITER;
	XPRS.attr("COMPUTELOG") = POI_XPRS_COMPUTELOG;
	XPRS.attr("SIFTPRESOLVEOPS") = POI_XPRS_SIFTPRESOLVEOPS;
	XPRS.attr("CHECKINPUTDATA") = POI_XPRS_CHECKINPUTDATA;
	XPRS.attr("ESCAPENAMES") = POI_XPRS_ESCAPENAMES;
	XPRS.attr("IOTIMEOUT") = POI_XPRS_IOTIMEOUT;
	XPRS.attr("AUTOCUTTING") = POI_XPRS_AUTOCUTTING;
	XPRS.attr("GLOBALNUMINITNLPCUTS") = POI_XPRS_GLOBALNUMINITNLPCUTS;
	XPRS.attr("CALLBACKCHECKTIMEDELAY") = POI_XPRS_CALLBACKCHECKTIMEDELAY;
	XPRS.attr("MULTIOBJOPS") = POI_XPRS_MULTIOBJOPS;
	XPRS.attr("MULTIOBJLOG") = POI_XPRS_MULTIOBJLOG;
	XPRS.attr("BACKGROUNDMAXTHREADS") = POI_XPRS_BACKGROUNDMAXTHREADS;
	XPRS.attr("GLOBALLSHEURSTRATEGY") = POI_XPRS_GLOBALLSHEURSTRATEGY;
	XPRS.attr("GLOBALSPATIALBRANCHIFPREFERORIG") = POI_XPRS_GLOBALSPATIALBRANCHIFPREFERORIG;
	XPRS.attr("PRECONFIGURATION") = POI_XPRS_PRECONFIGURATION;
	XPRS.attr("FEASIBILITYJUMP") = POI_XPRS_FEASIBILITYJUMP;
	XPRS.attr("IISOPS") = POI_XPRS_IISOPS;
	XPRS.attr("RLTCUTS") = POI_XPRS_RLTCUTS;
	XPRS.attr("ALTERNATIVEREDCOSTS") = POI_XPRS_ALTERNATIVEREDCOSTS;
	XPRS.attr("HEURSHIFTPROP") = POI_XPRS_HEURSHIFTPROP;
	XPRS.attr("HEURSEARCHCOPYCONTROLS") = POI_XPRS_HEURSEARCHCOPYCONTROLS;
	XPRS.attr("GLOBALNLPCUTS") = POI_XPRS_GLOBALNLPCUTS;
	XPRS.attr("GLOBALTREENLPCUTS") = POI_XPRS_GLOBALTREENLPCUTS;
	XPRS.attr("BARHGOPS") = POI_XPRS_BARHGOPS;
	XPRS.attr("BARHGMAXRESTARTS") = POI_XPRS_BARHGMAXRESTARTS;
	XPRS.attr("MCFCUTSTRATEGY") = POI_XPRS_MCFCUTSTRATEGY;
	XPRS.attr("PREROOTTHREADS") = POI_XPRS_PREROOTTHREADS;
	XPRS.attr("BARITERATIVE") = POI_XPRS_BARITERATIVE;
	/* Integer control parameters that support 64-bit values  */
	XPRS.attr("EXTRAELEMS") = POI_XPRS_EXTRAELEMS;
	XPRS.attr("EXTRASETELEMS") = POI_XPRS_EXTRASETELEMS;
	XPRS.attr("BACKGROUNDSELECT") = POI_XPRS_BACKGROUNDSELECT;
	XPRS.attr("HEURSEARCHBACKGROUNDSELECT") = POI_XPRS_HEURSEARCHBACKGROUNDSELECT;

	/* attributes for XPRSprob */
	/* String attributes */
	XPRS.attr("MATRIXNAME") = POI_XPRS_MATRIXNAME;
	XPRS.attr("BOUNDNAME") = POI_XPRS_BOUNDNAME;
	XPRS.attr("RHSNAME") = POI_XPRS_RHSNAME;
	XPRS.attr("RANGENAME") = POI_XPRS_RANGENAME;
	XPRS.attr("XPRESSVERSION") = POI_XPRS_XPRESSVERSION;
	XPRS.attr("UUID") = POI_XPRS_UUID;
	/* Double attributes */
	XPRS.attr("MIPSOLTIME") = POI_XPRS_MIPSOLTIME;
	XPRS.attr("TIME") = POI_XPRS_TIME;
	XPRS.attr("LPOBJVAL") = POI_XPRS_LPOBJVAL;
	XPRS.attr("SUMPRIMALINF") = POI_XPRS_SUMPRIMALINF;
	XPRS.attr("MIPOBJVAL") = POI_XPRS_MIPOBJVAL;
	XPRS.attr("BESTBOUND") = POI_XPRS_BESTBOUND;
	XPRS.attr("OBJRHS") = POI_XPRS_OBJRHS;
	XPRS.attr("MIPBESTOBJVAL") = POI_XPRS_MIPBESTOBJVAL;
	XPRS.attr("OBJSENSE") = POI_XPRS_OBJSENSE;
	XPRS.attr("BRANCHVALUE") = POI_XPRS_BRANCHVALUE;
	XPRS.attr("PENALTYVALUE") = POI_XPRS_PENALTYVALUE;
	XPRS.attr("CURRMIPCUTOFF") = POI_XPRS_CURRMIPCUTOFF;
	XPRS.attr("BARCONDA") = POI_XPRS_BARCONDA;
	XPRS.attr("BARCONDD") = POI_XPRS_BARCONDD;
	XPRS.attr("MAXABSPRIMALINFEAS") = POI_XPRS_MAXABSPRIMALINFEAS;
	XPRS.attr("MAXRELPRIMALINFEAS") = POI_XPRS_MAXRELPRIMALINFEAS;
	XPRS.attr("MAXABSDUALINFEAS") = POI_XPRS_MAXABSDUALINFEAS;
	XPRS.attr("MAXRELDUALINFEAS") = POI_XPRS_MAXRELDUALINFEAS;
	XPRS.attr("PRIMALDUALINTEGRAL") = POI_XPRS_PRIMALDUALINTEGRAL;
	XPRS.attr("MAXMIPINFEAS") = POI_XPRS_MAXMIPINFEAS;
	XPRS.attr("ATTENTIONLEVEL") = POI_XPRS_ATTENTIONLEVEL;
	XPRS.attr("MAXKAPPA") = POI_XPRS_MAXKAPPA;
	XPRS.attr("TREECOMPLETION") = POI_XPRS_TREECOMPLETION;
	XPRS.attr("PREDICTEDATTLEVEL") = POI_XPRS_PREDICTEDATTLEVEL;
	XPRS.attr("OBSERVEDPRIMALINTEGRAL") = POI_XPRS_OBSERVEDPRIMALINTEGRAL;
	XPRS.attr("CPISCALEFACTOR") = POI_XPRS_CPISCALEFACTOR;
	XPRS.attr("OBJVAL") = POI_XPRS_OBJVAL;
	XPRS.attr("WORK") = POI_XPRS_WORK;
	XPRS.attr("BARPRIMALOBJ") = POI_XPRS_BARPRIMALOBJ;
	XPRS.attr("BARDUALOBJ") = POI_XPRS_BARDUALOBJ;
	XPRS.attr("BARPRIMALINF") = POI_XPRS_BARPRIMALINF;
	XPRS.attr("BARDUALINF") = POI_XPRS_BARDUALINF;
	XPRS.attr("BARCGAP") = POI_XPRS_BARCGAP;
	/* Integer attributes */
	XPRS.attr("ROWS") = POI_XPRS_ROWS;
	XPRS.attr("SETS") = POI_XPRS_SETS;
	XPRS.attr("PRIMALINFEAS") = POI_XPRS_PRIMALINFEAS;
	XPRS.attr("DUALINFEAS") = POI_XPRS_DUALINFEAS;
	XPRS.attr("SIMPLEXITER") = POI_XPRS_SIMPLEXITER;
	XPRS.attr("LPSTATUS") = POI_XPRS_LPSTATUS;
	XPRS.attr("MIPSTATUS") = POI_XPRS_MIPSTATUS;
	XPRS.attr("CUTS") = POI_XPRS_CUTS;
	XPRS.attr("NODES") = POI_XPRS_NODES;
	XPRS.attr("NODEDEPTH") = POI_XPRS_NODEDEPTH;
	XPRS.attr("ACTIVENODES") = POI_XPRS_ACTIVENODES;
	XPRS.attr("MIPSOLNODE") = POI_XPRS_MIPSOLNODE;
	XPRS.attr("MIPSOLS") = POI_XPRS_MIPSOLS;
	XPRS.attr("COLS") = POI_XPRS_COLS;
	XPRS.attr("SPAREROWS") = POI_XPRS_SPAREROWS;
	XPRS.attr("SPARECOLS") = POI_XPRS_SPARECOLS;
	XPRS.attr("SPAREMIPENTS") = POI_XPRS_SPAREMIPENTS;
	XPRS.attr("ERRORCODE") = POI_XPRS_ERRORCODE;
	XPRS.attr("MIPINFEAS") = POI_XPRS_MIPINFEAS;
	XPRS.attr("PRESOLVESTATE") = POI_XPRS_PRESOLVESTATE;
	XPRS.attr("PARENTNODE") = POI_XPRS_PARENTNODE;
	XPRS.attr("NAMELENGTH") = POI_XPRS_NAMELENGTH;
	XPRS.attr("QELEMS") = POI_XPRS_QELEMS;
	XPRS.attr("NUMIIS") = POI_XPRS_NUMIIS;
	XPRS.attr("MIPENTS") = POI_XPRS_MIPENTS;
	XPRS.attr("BRANCHVAR") = POI_XPRS_BRANCHVAR;
	XPRS.attr("MIPTHREADID") = POI_XPRS_MIPTHREADID;
	XPRS.attr("ALGORITHM") = POI_XPRS_ALGORITHM;
	XPRS.attr("CROSSOVERITER") = POI_XPRS_CROSSOVERITER;
	XPRS.attr("SOLSTATUS") = POI_XPRS_SOLSTATUS;
	XPRS.attr("CUTROUNDS") = POI_XPRS_CUTROUNDS;
	XPRS.attr("ORIGINALROWS") = POI_XPRS_ORIGINALROWS;
	XPRS.attr("CALLBACKCOUNT_OPTNODE") = POI_XPRS_CALLBACKCOUNT_OPTNODE;
	XPRS.attr("ORIGINALQELEMS") = POI_XPRS_ORIGINALQELEMS;
	XPRS.attr("MAXPROBNAMELENGTH") = POI_XPRS_MAXPROBNAMELENGTH;
	XPRS.attr("STOPSTATUS") = POI_XPRS_STOPSTATUS;
	XPRS.attr("ORIGINALMIPENTS") = POI_XPRS_ORIGINALMIPENTS;
	XPRS.attr("ORIGINALSETS") = POI_XPRS_ORIGINALSETS;
	XPRS.attr("SPARESETS") = POI_XPRS_SPARESETS;
	XPRS.attr("CHECKSONMAXTIME") = POI_XPRS_CHECKSONMAXTIME;
	XPRS.attr("CHECKSONMAXCUTTIME") = POI_XPRS_CHECKSONMAXCUTTIME;
	XPRS.attr("ORIGINALCOLS") = POI_XPRS_ORIGINALCOLS;
	XPRS.attr("QCELEMS") = POI_XPRS_QCELEMS;
	XPRS.attr("QCONSTRAINTS") = POI_XPRS_QCONSTRAINTS;
	XPRS.attr("ORIGINALQCELEMS") = POI_XPRS_ORIGINALQCELEMS;
	XPRS.attr("ORIGINALQCONSTRAINTS") = POI_XPRS_ORIGINALQCONSTRAINTS;
	XPRS.attr("PEAKTOTALTREEMEMORYUSAGE") = POI_XPRS_PEAKTOTALTREEMEMORYUSAGE;
	XPRS.attr("CURRENTNODE") = POI_XPRS_CURRENTNODE;
	XPRS.attr("TREEMEMORYUSAGE") = POI_XPRS_TREEMEMORYUSAGE;
	XPRS.attr("TREEFILESIZE") = POI_XPRS_TREEFILESIZE;
	XPRS.attr("TREEFILEUSAGE") = POI_XPRS_TREEFILEUSAGE;
	XPRS.attr("INDICATORS") = POI_XPRS_INDICATORS;
	XPRS.attr("ORIGINALINDICATORS") = POI_XPRS_ORIGINALINDICATORS;
	XPRS.attr("CORESPERCPUDETECTED") = POI_XPRS_CORESPERCPUDETECTED;
	XPRS.attr("CPUSDETECTED") = POI_XPRS_CPUSDETECTED;
	XPRS.attr("CORESDETECTED") = POI_XPRS_CORESDETECTED;
	XPRS.attr("PHYSICALCORESDETECTED") = POI_XPRS_PHYSICALCORESDETECTED;
	XPRS.attr("PHYSICALCORESPERCPUDETECTED") = POI_XPRS_PHYSICALCORESPERCPUDETECTED;
	XPRS.attr("OPTIMIZETYPEUSED") = POI_XPRS_OPTIMIZETYPEUSED;
	XPRS.attr("BARSING") = POI_XPRS_BARSING;
	XPRS.attr("BARSINGR") = POI_XPRS_BARSINGR;
	XPRS.attr("PRESOLVEINDEX") = POI_XPRS_PRESOLVEINDEX;
	XPRS.attr("CONES") = POI_XPRS_CONES;
	XPRS.attr("CONEELEMS") = POI_XPRS_CONEELEMS;
	XPRS.attr("PWLCONS") = POI_XPRS_PWLCONS;
	XPRS.attr("GENCONS") = POI_XPRS_GENCONS;
	XPRS.attr("TREERESTARTS") = POI_XPRS_TREERESTARTS;
	XPRS.attr("ORIGINALPWLS") = POI_XPRS_ORIGINALPWLS;
	XPRS.attr("ORIGINALGENCONS") = POI_XPRS_ORIGINALGENCONS;
	XPRS.attr("COMPUTEEXECUTIONS") = POI_XPRS_COMPUTEEXECUTIONS;
	XPRS.attr("RESTARTS") = POI_XPRS_RESTARTS;
	XPRS.attr("SOLVESTATUS") = POI_XPRS_SOLVESTATUS;
	XPRS.attr("GLOBALBOUNDINGBOXAPPLIED") = POI_XPRS_GLOBALBOUNDINGBOXAPPLIED;
	XPRS.attr("OBJECTIVES") = POI_XPRS_OBJECTIVES;
	XPRS.attr("SOLVEDOBJS") = POI_XPRS_SOLVEDOBJS;
	XPRS.attr("OBJSTOSOLVE") = POI_XPRS_OBJSTOSOLVE;
	XPRS.attr("GLOBALNLPINFEAS") = POI_XPRS_GLOBALNLPINFEAS;
	XPRS.attr("IISSOLSTATUS") = POI_XPRS_IISSOLSTATUS;
	XPRS.attr("INPUTROWS") = POI_XPRS_INPUTROWS;
	XPRS.attr("INPUTCOLS") = POI_XPRS_INPUTCOLS;
	XPRS.attr("BARITER") = POI_XPRS_BARITER;
	XPRS.attr("BARDENSECOL") = POI_XPRS_BARDENSECOL;
	XPRS.attr("BARCROSSOVER") = POI_XPRS_BARCROSSOVER;
	/* Integer attributes that support 64-bit values */
	XPRS.attr("SETMEMBERS") = POI_XPRS_SETMEMBERS;
	XPRS.attr("ELEMS") = POI_XPRS_ELEMS;
	XPRS.attr("SPAREELEMS") = POI_XPRS_SPAREELEMS;
	XPRS.attr("SYSTEMMEMORY") = POI_XPRS_SYSTEMMEMORY;
	XPRS.attr("ORIGINALSETMEMBERS") = POI_XPRS_ORIGINALSETMEMBERS;
	XPRS.attr("SPARESETELEMS") = POI_XPRS_SPARESETELEMS;
	XPRS.attr("CURRENTMEMORY") = POI_XPRS_CURRENTMEMORY;
	XPRS.attr("PEAKMEMORY") = POI_XPRS_PEAKMEMORY;
	XPRS.attr("TOTALMEMORY") = POI_XPRS_TOTALMEMORY;
	XPRS.attr("AVAILABLEMEMORY") = POI_XPRS_AVAILABLEMEMORY;
	XPRS.attr("PWLPOINTS") = POI_XPRS_PWLPOINTS;
	XPRS.attr("GENCONCOLS") = POI_XPRS_GENCONCOLS;
	XPRS.attr("GENCONVALS") = POI_XPRS_GENCONVALS;
	XPRS.attr("ORIGINALPWLPOINTS") = POI_XPRS_ORIGINALPWLPOINTS;
	XPRS.attr("ORIGINALGENCONCOLS") = POI_XPRS_ORIGINALGENCONCOLS;
	XPRS.attr("ORIGINALGENCONVALS") = POI_XPRS_ORIGINALGENCONVALS;
	XPRS.attr("MEMORYLIMITDETECTED") = POI_XPRS_MEMORYLIMITDETECTED;
	XPRS.attr("BARAASIZE") = POI_XPRS_BARAASIZE;
	XPRS.attr("BARLSIZE") = POI_XPRS_BARLSIZE;

	// Nonlinear solver related controls and attributes
	XPRS.attr("NLPFUNCEVAL") = POI_XPRS_NLPFUNCEVAL;
	XPRS.attr("NLPLOG") = POI_XPRS_NLPLOG;
	XPRS.attr("NLPKEEPEQUALSCOLUMN") = POI_XPRS_NLPKEEPEQUALSCOLUMN;
	XPRS.attr("NLPEVALUATE") = POI_XPRS_NLPEVALUATE;
	XPRS.attr("NLPPRESOLVE") = POI_XPRS_NLPPRESOLVE;
	XPRS.attr("SLPLOG") = POI_XPRS_SLPLOG;
	XPRS.attr("LOCALSOLVER") = POI_XPRS_LOCALSOLVER;
	XPRS.attr("NLPSTOPOUTOFRANGE") = POI_XPRS_NLPSTOPOUTOFRANGE;
	XPRS.attr("NLPTHREADSAFEUSERFUNC") = POI_XPRS_NLPTHREADSAFEUSERFUNC;
	XPRS.attr("NLPJACOBIAN") = POI_XPRS_NLPJACOBIAN;
	XPRS.attr("NLPHESSIAN") = POI_XPRS_NLPHESSIAN;
	XPRS.attr("MULTISTART") = POI_XPRS_MULTISTART;
	XPRS.attr("MULTISTART_THREADS") = POI_XPRS_MULTISTART_THREADS;
	XPRS.attr("MULTISTART_MAXSOLVES") = POI_XPRS_MULTISTART_MAXSOLVES;
	XPRS.attr("MULTISTART_MAXTIME") = POI_XPRS_MULTISTART_MAXTIME;
	XPRS.attr("NLPMAXTIME") = POI_XPRS_NLPMAXTIME;
	XPRS.attr("NLPDERIVATIVES") = POI_XPRS_NLPDERIVATIVES;
	XPRS.attr("NLPREFORMULATE") = POI_XPRS_NLPREFORMULATE;
	XPRS.attr("NLPPRESOLVEOPS") = POI_XPRS_NLPPRESOLVEOPS;
	XPRS.attr("MULTISTART_LOG") = POI_XPRS_MULTISTART_LOG;
	XPRS.attr("MULTISTART_SEED") = POI_XPRS_MULTISTART_SEED;
	XPRS.attr("MULTISTART_POOLSIZE") = POI_XPRS_MULTISTART_POOLSIZE;
	XPRS.attr("NLPPOSTSOLVE") = POI_XPRS_NLPPOSTSOLVE;
	XPRS.attr("NLPDETERMINISTIC") = POI_XPRS_NLPDETERMINISTIC;
	XPRS.attr("NLPPRESOLVELEVEL") = POI_XPRS_NLPPRESOLVELEVEL;
	XPRS.attr("NLPPROBING") = POI_XPRS_NLPPROBING;
	XPRS.attr("NLPCALCTHREADS") = POI_XPRS_NLPCALCTHREADS;
	XPRS.attr("NLPTHREADS") = POI_XPRS_NLPTHREADS;
	XPRS.attr("NLPFINDIV") = POI_XPRS_NLPFINDIV;
	XPRS.attr("NLPLINQUADBR") = POI_XPRS_NLPLINQUADBR;
	XPRS.attr("NLPSOLVER") = POI_XPRS_NLPSOLVER;
	// SLP related integer controls
	XPRS.attr("SLPALGORITHM") = POI_XPRS_SLPALGORITHM;
	XPRS.attr("SLPAUGMENTATION") = POI_XPRS_SLPAUGMENTATION;
	XPRS.attr("SLPBARLIMIT") = POI_XPRS_SLPBARLIMIT;
	XPRS.attr("SLPCASCADE") = POI_XPRS_SLPCASCADE;
	XPRS.attr("SLPCASCADENLIMIT") = POI_XPRS_SLPCASCADENLIMIT;
	XPRS.attr("SLPDAMPSTART") = POI_XPRS_SLPDAMPSTART;
	XPRS.attr("SLPCUTSTRATEGY") = POI_XPRS_SLPCUTSTRATEGY;
	XPRS.attr("SLPDELTAZLIMIT") = POI_XPRS_SLPDELTAZLIMIT;
	XPRS.attr("SLPINFEASLIMIT") = POI_XPRS_SLPINFEASLIMIT;
	XPRS.attr("SLPITERLIMIT") = POI_XPRS_SLPITERLIMIT;
	XPRS.attr("SLPSAMECOUNT") = POI_XPRS_SLPSAMECOUNT;
	XPRS.attr("SLPSAMEDAMP") = POI_XPRS_SLPSAMEDAMP;
	XPRS.attr("SLPSBSTART") = POI_XPRS_SLPSBSTART;
	XPRS.attr("SLPXCOUNT") = POI_XPRS_SLPXCOUNT;
	XPRS.attr("SLPXLIMIT") = POI_XPRS_SLPXLIMIT;
	XPRS.attr("SLPDELAYUPDATEROWS") = POI_XPRS_SLPDELAYUPDATEROWS;
	XPRS.attr("SLPAUTOSAVE") = POI_XPRS_SLPAUTOSAVE;
	XPRS.attr("SLPANALYZE") = POI_XPRS_SLPANALYZE;
	XPRS.attr("SLPOCOUNT") = POI_XPRS_SLPOCOUNT;
	XPRS.attr("SLPMIPALGORITHM") = POI_XPRS_SLPMIPALGORITHM;
	XPRS.attr("SLPMIPRELAXSTEPBOUNDS") = POI_XPRS_SLPMIPRELAXSTEPBOUNDS;
	XPRS.attr("SLPMIPFIXSTEPBOUNDS") = POI_XPRS_SLPMIPFIXSTEPBOUNDS;
	XPRS.attr("SLPMIPITERLIMIT") = POI_XPRS_SLPMIPITERLIMIT;
	XPRS.attr("SLPMIPCUTOFFLIMIT") = POI_XPRS_SLPMIPCUTOFFLIMIT;
	XPRS.attr("SLPMIPOCOUNT") = POI_XPRS_SLPMIPOCOUNT;
	XPRS.attr("SLPMIPDEFAULTALGORITHM") = POI_XPRS_SLPMIPDEFAULTALGORITHM;
	XPRS.attr("SLPMIPLOG") = POI_XPRS_SLPMIPLOG;
	XPRS.attr("SLPDELTAOFFSET") = POI_XPRS_SLPDELTAOFFSET;
	XPRS.attr("SLPUPDATEOFFSET") = POI_XPRS_SLPUPDATEOFFSET;
	XPRS.attr("SLPERROROFFSET") = POI_XPRS_SLPERROROFFSET;
	XPRS.attr("SLPSBROWOFFSET") = POI_XPRS_SLPSBROWOFFSET;
	XPRS.attr("SLPVCOUNT") = POI_XPRS_SLPVCOUNT;
	XPRS.attr("SLPVLIMIT") = POI_XPRS_SLPVLIMIT;
	XPRS.attr("SLPSCALE") = POI_XPRS_SLPSCALE;
	XPRS.attr("SLPSCALECOUNT") = POI_XPRS_SLPSCALECOUNT;
	XPRS.attr("SLPECFCHECK") = POI_XPRS_SLPECFCHECK;
	XPRS.attr("SLPMIPCUTOFFCOUNT") = POI_XPRS_SLPMIPCUTOFFCOUNT;
	XPRS.attr("SLPWCOUNT") = POI_XPRS_SLPWCOUNT;
	XPRS.attr("SLPUNFINISHEDLIMIT") = POI_XPRS_SLPUNFINISHEDLIMIT;
	XPRS.attr("SLPCONVERGENCEOPS") = POI_XPRS_SLPCONVERGENCEOPS;
	XPRS.attr("SLPZEROCRITERION") = POI_XPRS_SLPZEROCRITERION;
	XPRS.attr("SLPZEROCRITERIONSTART") = POI_XPRS_SLPZEROCRITERIONSTART;
	XPRS.attr("SLPZEROCRITERIONCOUNT") = POI_XPRS_SLPZEROCRITERIONCOUNT;
	XPRS.attr("SLPLSPATTERNLIMIT") = POI_XPRS_SLPLSPATTERNLIMIT;
	XPRS.attr("SLPLSITERLIMIT") = POI_XPRS_SLPLSITERLIMIT;
	XPRS.attr("SLPLSSTART") = POI_XPRS_SLPLSSTART;
	XPRS.attr("SLPPENALTYINFOSTART") = POI_XPRS_SLPPENALTYINFOSTART;
	XPRS.attr("SLPFILTER") = POI_XPRS_SLPFILTER;
	XPRS.attr("SLPTRACEMASKOPS") = POI_XPRS_SLPTRACEMASKOPS;
	XPRS.attr("SLPLSZEROLIMIT") = POI_XPRS_SLPLSZEROLIMIT;
	XPRS.attr("SLPHEURSTRATEGY") = POI_XPRS_SLPHEURSTRATEGY;
	XPRS.attr("SLPBARCROSSOVERSTART") = POI_XPRS_SLPBARCROSSOVERSTART;
	XPRS.attr("SLPBARSTALLINGLIMIT") = POI_XPRS_SLPBARSTALLINGLIMIT;
	XPRS.attr("SLPBARSTALLINGOBJLIMIT") = POI_XPRS_SLPBARSTALLINGOBJLIMIT;
	XPRS.attr("SLPBARSTARTOPS") = POI_XPRS_SLPBARSTARTOPS;
	XPRS.attr("SLPGRIDHEURSELECT") = POI_XPRS_SLPGRIDHEURSELECT;
	// Nonlinear related double controls
	XPRS.attr("NLPINFINITY") = POI_XPRS_NLPINFINITY;
	XPRS.attr("NLPZERO") = POI_XPRS_NLPZERO;
	XPRS.attr("NLPDEFAULTIV") = POI_XPRS_NLPDEFAULTIV;
	XPRS.attr("NLPOPTTIME") = POI_XPRS_NLPOPTTIME;
	XPRS.attr("NLPVALIDATIONTOL_A") = POI_XPRS_NLPVALIDATIONTOL_A;
	XPRS.attr("NLPVALIDATIONTOL_R") = POI_XPRS_NLPVALIDATIONTOL_R;
	XPRS.attr("NLPVALIDATIONINDEX_A") = POI_XPRS_NLPVALIDATIONINDEX_A;
	XPRS.attr("NLPVALIDATIONINDEX_R") = POI_XPRS_NLPVALIDATIONINDEX_R;
	XPRS.attr("NLPPRIMALINTEGRALREF") = POI_XPRS_NLPPRIMALINTEGRALREF;
	XPRS.attr("NLPPRIMALINTEGRALALPHA") = POI_XPRS_NLPPRIMALINTEGRALALPHA;
	XPRS.attr("NLPOBJVAL") = POI_XPRS_NLPOBJVAL;
	XPRS.attr("NLPPRESOLVEZERO") = POI_XPRS_NLPPRESOLVEZERO;
	XPRS.attr("NLPMERITLAMBDA") = POI_XPRS_NLPMERITLAMBDA;
	XPRS.attr("MSMAXBOUNDRANGE") = POI_XPRS_MSMAXBOUNDRANGE;
	XPRS.attr("NLPVALIDATIONTOL_K") = POI_XPRS_NLPVALIDATIONTOL_K;
	XPRS.attr("NLPPRESOLVE_ELIMTOL") = POI_XPRS_NLPPRESOLVE_ELIMTOL;
	XPRS.attr("NLPVALIDATIONTARGET_R") = POI_XPRS_NLPVALIDATIONTARGET_R;
	XPRS.attr("NLPVALIDATIONTARGET_K") = POI_XPRS_NLPVALIDATIONTARGET_K;
	XPRS.attr("NLPVALIDATIONFACTOR") = POI_XPRS_NLPVALIDATIONFACTOR;
	XPRS.attr("NLPRELTOLBOUNDTHRESHOLD") = POI_XPRS_NLPRELTOLBOUNDTHRESHOLD;
	// SLP related double controls
	XPRS.attr("SLPDAMP") = POI_XPRS_SLPDAMP;
	XPRS.attr("SLPDAMPEXPAND") = POI_XPRS_SLPDAMPEXPAND;
	XPRS.attr("SLPDAMPSHRINK") = POI_XPRS_SLPDAMPSHRINK;
	XPRS.attr("SLPDELTA_A") = POI_XPRS_SLPDELTA_A;
	XPRS.attr("SLPDELTA_R") = POI_XPRS_SLPDELTA_R;
	XPRS.attr("SLPDELTA_Z") = POI_XPRS_SLPDELTA_Z;
	XPRS.attr("SLPDELTACOST") = POI_XPRS_SLPDELTACOST;
	XPRS.attr("SLPDELTAMAXCOST") = POI_XPRS_SLPDELTAMAXCOST;
	XPRS.attr("SLPDJTOL") = POI_XPRS_SLPDJTOL;
	XPRS.attr("SLPERRORCOST") = POI_XPRS_SLPERRORCOST;
	XPRS.attr("SLPERRORMAXCOST") = POI_XPRS_SLPERRORMAXCOST;
	XPRS.attr("SLPERRORTOL_A") = POI_XPRS_SLPERRORTOL_A;
	XPRS.attr("SLPEXPAND") = POI_XPRS_SLPEXPAND;
	XPRS.attr("SLPMAXWEIGHT") = POI_XPRS_SLPMAXWEIGHT;
	XPRS.attr("SLPMINWEIGHT") = POI_XPRS_SLPMINWEIGHT;
	XPRS.attr("SLPSHRINK") = POI_XPRS_SLPSHRINK;
	XPRS.attr("SLPCTOL") = POI_XPRS_SLPCTOL;
	XPRS.attr("SLPATOL_A") = POI_XPRS_SLPATOL_A;
	XPRS.attr("SLPATOL_R") = POI_XPRS_SLPATOL_R;
	XPRS.attr("SLPMTOL_A") = POI_XPRS_SLPMTOL_A;
	XPRS.attr("SLPMTOL_R") = POI_XPRS_SLPMTOL_R;
	XPRS.attr("SLPITOL_A") = POI_XPRS_SLPITOL_A;
	XPRS.attr("SLPITOL_R") = POI_XPRS_SLPITOL_R;
	XPRS.attr("SLPSTOL_A") = POI_XPRS_SLPSTOL_A;
	XPRS.attr("SLPSTOL_R") = POI_XPRS_SLPSTOL_R;
	XPRS.attr("SLPMVTOL") = POI_XPRS_SLPMVTOL;
	XPRS.attr("SLPXTOL_A") = POI_XPRS_SLPXTOL_A;
	XPRS.attr("SLPXTOL_R") = POI_XPRS_SLPXTOL_R;
	XPRS.attr("SLPDEFAULTSTEPBOUND") = POI_XPRS_SLPDEFAULTSTEPBOUND;
	XPRS.attr("SLPDAMPMAX") = POI_XPRS_SLPDAMPMAX;
	XPRS.attr("SLPDAMPMIN") = POI_XPRS_SLPDAMPMIN;
	XPRS.attr("SLPDELTACOSTFACTOR") = POI_XPRS_SLPDELTACOSTFACTOR;
	XPRS.attr("SLPERRORCOSTFACTOR") = POI_XPRS_SLPERRORCOSTFACTOR;
	XPRS.attr("SLPERRORTOL_P") = POI_XPRS_SLPERRORTOL_P;
	XPRS.attr("SLPCASCADETOL_PA") = POI_XPRS_SLPCASCADETOL_PA;
	XPRS.attr("SLPCASCADETOL_PR") = POI_XPRS_SLPCASCADETOL_PR;
	XPRS.attr("SLPCASCADETOL_Z") = POI_XPRS_SLPCASCADETOL_Z;
	XPRS.attr("SLPOTOL_A") = POI_XPRS_SLPOTOL_A;
	XPRS.attr("SLPOTOL_R") = POI_XPRS_SLPOTOL_R;
	XPRS.attr("SLPDELTA_X") = POI_XPRS_SLPDELTA_X;
	XPRS.attr("SLPERRORCOSTS") = POI_XPRS_SLPERRORCOSTS;
	XPRS.attr("SLPGRANULARITY") = POI_XPRS_SLPGRANULARITY;
	XPRS.attr("SLPMIPCUTOFF_A") = POI_XPRS_SLPMIPCUTOFF_A;
	XPRS.attr("SLPMIPCUTOFF_R") = POI_XPRS_SLPMIPCUTOFF_R;
	XPRS.attr("SLPMIPOTOL_A") = POI_XPRS_SLPMIPOTOL_A;
	XPRS.attr("SLPMIPOTOL_R") = POI_XPRS_SLPMIPOTOL_R;
	XPRS.attr("SLPESCALATION") = POI_XPRS_SLPESCALATION;
	XPRS.attr("SLPOBJTOPENALTYCOST") = POI_XPRS_SLPOBJTOPENALTYCOST;
	XPRS.attr("SLPSHRINKBIAS") = POI_XPRS_SLPSHRINKBIAS;
	XPRS.attr("SLPFEASTOLTARGET") = POI_XPRS_SLPFEASTOLTARGET;
	XPRS.attr("SLPOPTIMALITYTOLTARGET") = POI_XPRS_SLPOPTIMALITYTOLTARGET;
	XPRS.attr("SLPDELTA_INFINITY") = POI_XPRS_SLPDELTA_INFINITY;
	XPRS.attr("SLPVTOL_A") = POI_XPRS_SLPVTOL_A;
	XPRS.attr("SLPVTOL_R") = POI_XPRS_SLPVTOL_R;
	XPRS.attr("SLPETOL_A") = POI_XPRS_SLPETOL_A;
	XPRS.attr("SLPETOL_R") = POI_XPRS_SLPETOL_R;
	XPRS.attr("SLPEVTOL_A") = POI_XPRS_SLPEVTOL_A;
	XPRS.attr("SLPEVTOL_R") = POI_XPRS_SLPEVTOL_R;
	XPRS.attr("SLPDELTA_ZERO") = POI_XPRS_SLPDELTA_ZERO;
	XPRS.attr("SLPMINSBFACTOR") = POI_XPRS_SLPMINSBFACTOR;
	XPRS.attr("SLPCLAMPVALIDATIONTOL_A") = POI_XPRS_SLPCLAMPVALIDATIONTOL_A;
	XPRS.attr("SLPCLAMPVALIDATIONTOL_R") = POI_XPRS_SLPCLAMPVALIDATIONTOL_R;
	XPRS.attr("SLPCLAMPSHRINK") = POI_XPRS_SLPCLAMPSHRINK;
	XPRS.attr("SLPECFTOL_A") = POI_XPRS_SLPECFTOL_A;
	XPRS.attr("SLPECFTOL_R") = POI_XPRS_SLPECFTOL_R;
	XPRS.attr("SLPWTOL_A") = POI_XPRS_SLPWTOL_A;
	XPRS.attr("SLPWTOL_R") = POI_XPRS_SLPWTOL_R;
	XPRS.attr("SLPMATRIXTOL") = POI_XPRS_SLPMATRIXTOL;
	XPRS.attr("SLPDRFIXRANGE") = POI_XPRS_SLPDRFIXRANGE;
	XPRS.attr("SLPDRCOLTOL") = POI_XPRS_SLPDRCOLTOL;
	XPRS.attr("SLPMIPERRORTOL_A") = POI_XPRS_SLPMIPERRORTOL_A;
	XPRS.attr("SLPMIPERRORTOL_R") = POI_XPRS_SLPMIPERRORTOL_R;
	XPRS.attr("SLPCDTOL_A") = POI_XPRS_SLPCDTOL_A;
	XPRS.attr("SLPCDTOL_R") = POI_XPRS_SLPCDTOL_R;
	XPRS.attr("SLPENFORCEMAXCOST") = POI_XPRS_SLPENFORCEMAXCOST;
	XPRS.attr("SLPENFORCECOSTSHRINK") = POI_XPRS_SLPENFORCECOSTSHRINK;
	XPRS.attr("SLPDRCOLDJTOL") = POI_XPRS_SLPDRCOLDJTOL;
	XPRS.attr("SLPBARSTALLINGTOL") = POI_XPRS_SLPBARSTALLINGTOL;
	XPRS.attr("SLPOBJTHRESHOLD") = POI_XPRS_SLPOBJTHRESHOLD;
	XPRS.attr("SLPBOUNDTHRESHOLD") = POI_XPRS_SLPBOUNDTHRESHOLD;
	// Nonlinear related string controls
	XPRS.attr("NLPIVNAME") = POI_XPRS_NLPIVNAME;
	// SLP related string controls
	XPRS.attr("SLPDELTAFORMAT") = POI_XPRS_SLPDELTAFORMAT;
	XPRS.attr("SLPMINUSDELTAFORMAT") = POI_XPRS_SLPMINUSDELTAFORMAT;
	XPRS.attr("SLPMINUSERRORFORMAT") = POI_XPRS_SLPMINUSERRORFORMAT;
	XPRS.attr("SLPPLUSDELTAFORMAT") = POI_XPRS_SLPPLUSDELTAFORMAT;
	XPRS.attr("SLPPLUSERRORFORMAT") = POI_XPRS_SLPPLUSERRORFORMAT;
	XPRS.attr("SLPSBNAME") = POI_XPRS_SLPSBNAME;
	XPRS.attr("SLPTOLNAME") = POI_XPRS_SLPTOLNAME;
	XPRS.attr("SLPUPDATEFORMAT") = POI_XPRS_SLPUPDATEFORMAT;
	XPRS.attr("SLPPENALTYROWFORMAT") = POI_XPRS_SLPPENALTYROWFORMAT;
	XPRS.attr("SLPPENALTYCOLFORMAT") = POI_XPRS_SLPPENALTYCOLFORMAT;
	XPRS.attr("SLPSBLOROWFORMAT") = POI_XPRS_SLPSBLOROWFORMAT;
	XPRS.attr("SLPSBUPROWFORMAT") = POI_XPRS_SLPSBUPROWFORMAT;
	XPRS.attr("SLPTRACEMASK") = POI_XPRS_SLPTRACEMASK;
	XPRS.attr("SLPITERFALLBACKOPS") = POI_XPRS_SLPITERFALLBACKOPS;
	// Nonlinear related integer attributes
	XPRS.attr("NLPVALIDATIONSTATUS") = POI_XPRS_NLPVALIDATIONSTATUS;
	XPRS.attr("NLPSOLSTATUS") = POI_XPRS_NLPSOLSTATUS;
	XPRS.attr("NLPORIGINALROWS") = POI_XPRS_NLPORIGINALROWS;
	XPRS.attr("NLPORIGINALCOLS") = POI_XPRS_NLPORIGINALCOLS;
	XPRS.attr("NLPUFS") = POI_XPRS_NLPUFS;
	XPRS.attr("NLPIFS") = POI_XPRS_NLPIFS;
	XPRS.attr("NLPEQUALSCOLUMN") = POI_XPRS_NLPEQUALSCOLUMN;
	XPRS.attr("NLPVARIABLES") = POI_XPRS_NLPVARIABLES;
	XPRS.attr("NLPIMPLICITVARIABLES") = POI_XPRS_NLPIMPLICITVARIABLES;
	XPRS.attr("NONLINEARCONSTRAINTS") = POI_XPRS_NONLINEARCONSTRAINTS;
	XPRS.attr("NLPUSERFUNCCALLS") = POI_XPRS_NLPUSERFUNCCALLS;
	XPRS.attr("NLPUSEDERIVATIVES") = POI_XPRS_NLPUSEDERIVATIVES;
	XPRS.attr("NLPKEEPBESTITER") = POI_XPRS_NLPKEEPBESTITER;
	XPRS.attr("NLPSTATUS") = POI_XPRS_NLPSTATUS;
	XPRS.attr("LOCALSOLVERSELECTED") = POI_XPRS_LOCALSOLVERSELECTED;
	XPRS.attr("NLPMODELROWS") = POI_XPRS_NLPMODELROWS;
	XPRS.attr("NLPMODELCOLS") = POI_XPRS_NLPMODELCOLS;
	XPRS.attr("NLPJOBID") = POI_XPRS_NLPJOBID;
	XPRS.attr("MSJOBS") = POI_XPRS_MSJOBS;
	XPRS.attr("NLPSTOPSTATUS") = POI_XPRS_NLPSTOPSTATUS;
	XPRS.attr("NLPPRESOLVEELIMINATIONS") = POI_XPRS_NLPPRESOLVEELIMINATIONS;
	XPRS.attr("NLPTOTALEVALUATIONERRORS") = POI_XPRS_NLPTOTALEVALUATIONERRORS;
	// SLP related integer attributes
	XPRS.attr("SLPEXPLOREDELTAS") = POI_XPRS_SLPEXPLOREDELTAS;
	XPRS.attr("SLPSEMICONTDELTAS") = POI_XPRS_SLPSEMICONTDELTAS;
	XPRS.attr("SLPINTEGERDELTAS") = POI_XPRS_SLPINTEGERDELTAS;
	XPRS.attr("SLPITER") = POI_XPRS_SLPITER;
	XPRS.attr("SLPSTATUS") = POI_XPRS_SLPSTATUS;
	XPRS.attr("SLPUNCONVERGED") = POI_XPRS_SLPUNCONVERGED;
	XPRS.attr("SLPSBXCONVERGED") = POI_XPRS_SLPSBXCONVERGED;
	XPRS.attr("SLPPENALTYDELTAROW") = POI_XPRS_SLPPENALTYDELTAROW;
	XPRS.attr("SLPPENALTYDELTACOLUMN") = POI_XPRS_SLPPENALTYDELTACOLUMN;
	XPRS.attr("SLPPENALTYERRORROW") = POI_XPRS_SLPPENALTYERRORROW;
	XPRS.attr("SLPPENALTYERRORCOLUMN") = POI_XPRS_SLPPENALTYERRORCOLUMN;
	XPRS.attr("SLPCOEFFICIENTS") = POI_XPRS_SLPCOEFFICIENTS;
	XPRS.attr("SLPPENALTYDELTAS") = POI_XPRS_SLPPENALTYDELTAS;
	XPRS.attr("SLPPENALTYERRORS") = POI_XPRS_SLPPENALTYERRORS;
	XPRS.attr("SLPPLUSPENALTYERRORS") = POI_XPRS_SLPPLUSPENALTYERRORS;
	XPRS.attr("SLPMINUSPENALTYERRORS") = POI_XPRS_SLPMINUSPENALTYERRORS;
	XPRS.attr("SLPUCCONSTRAINEDCOUNT") = POI_XPRS_SLPUCCONSTRAINEDCOUNT;
	XPRS.attr("SLPMIPNODES") = POI_XPRS_SLPMIPNODES;
	XPRS.attr("SLPMIPITER") = POI_XPRS_SLPMIPITER;
	XPRS.attr("SLPTOLSETS") = POI_XPRS_SLPTOLSETS;
	XPRS.attr("SLPECFCOUNT") = POI_XPRS_SLPECFCOUNT;
	XPRS.attr("SLPDELTAS") = POI_XPRS_SLPDELTAS;
	XPRS.attr("SLPZEROESRESET") = POI_XPRS_SLPZEROESRESET;
	XPRS.attr("SLPZEROESTOTAL") = POI_XPRS_SLPZEROESTOTAL;
	XPRS.attr("SLPZEROESRETAINED") = POI_XPRS_SLPZEROESRETAINED;
	XPRS.attr("SLPNONCONSTANTCOEFFS") = POI_XPRS_SLPNONCONSTANTCOEFFS;
	XPRS.attr("SLPMIPSOLS") = POI_XPRS_SLPMIPSOLS;
	// Nonlinear related double attributes
	XPRS.attr("NLPVALIDATIONINDEX_K") = POI_XPRS_NLPVALIDATIONINDEX_K;
	XPRS.attr("NLPVALIDATIONNETOBJ") = POI_XPRS_NLPVALIDATIONNETOBJ;
	XPRS.attr("NLPPRIMALINTEGRAL") = POI_XPRS_NLPPRIMALINTEGRAL;
	// SLP related double attributes
	XPRS.attr("SLPCURRENTDELTACOST") = POI_XPRS_SLPCURRENTDELTACOST;
	XPRS.attr("SLPCURRENTERRORCOST") = POI_XPRS_SLPCURRENTERRORCOST;
	XPRS.attr("SLPPENALTYERRORTOTAL") = POI_XPRS_SLPPENALTYERRORTOTAL;
	XPRS.attr("SLPPENALTYERRORVALUE") = POI_XPRS_SLPPENALTYERRORVALUE;
	XPRS.attr("SLPPENALTYDELTATOTAL") = POI_XPRS_SLPPENALTYDELTATOTAL;
	XPRS.attr("SLPPENALTYDELTAVALUE") = POI_XPRS_SLPPENALTYDELTAVALUE;
	// Nonlinear related string attributes
	// SLP related string attributes
	// Knitro's parameters
	XPRS.attr("KNITRO_PARAM_NEWPOINT") = POI_XPRS_KNITRO_PARAM_NEWPOINT;
	XPRS.attr("KNITRO_PARAM_HONORBNDS") = POI_XPRS_KNITRO_PARAM_HONORBNDS;
	XPRS.attr("KNITRO_PARAM_ALGORITHM") = POI_XPRS_KNITRO_PARAM_ALGORITHM;
	XPRS.attr("KNITRO_PARAM_BAR_MURULE") = POI_XPRS_KNITRO_PARAM_BAR_MURULE;
	XPRS.attr("KNITRO_PARAM_BAR_FEASIBLE") = POI_XPRS_KNITRO_PARAM_BAR_FEASIBLE;
	XPRS.attr("KNITRO_PARAM_GRADOPT") = POI_XPRS_KNITRO_PARAM_GRADOPT;
	XPRS.attr("KNITRO_PARAM_HESSOPT") = POI_XPRS_KNITRO_PARAM_HESSOPT;
	XPRS.attr("KNITRO_PARAM_BAR_INITPT") = POI_XPRS_KNITRO_PARAM_BAR_INITPT;
	XPRS.attr("KNITRO_PARAM_MAXCGIT") = POI_XPRS_KNITRO_PARAM_MAXCGIT;
	XPRS.attr("KNITRO_PARAM_MAXIT") = POI_XPRS_KNITRO_PARAM_MAXIT;
	XPRS.attr("KNITRO_PARAM_OUTLEV") = POI_XPRS_KNITRO_PARAM_OUTLEV;
	XPRS.attr("KNITRO_PARAM_SCALE") = POI_XPRS_KNITRO_PARAM_SCALE;
	XPRS.attr("KNITRO_PARAM_SOC") = POI_XPRS_KNITRO_PARAM_SOC;
	XPRS.attr("KNITRO_PARAM_DELTA") = POI_XPRS_KNITRO_PARAM_DELTA;
	XPRS.attr("KNITRO_PARAM_BAR_FEASMODETOL") = POI_XPRS_KNITRO_PARAM_BAR_FEASMODETOL;
	XPRS.attr("KNITRO_PARAM_FEASTOL") = POI_XPRS_KNITRO_PARAM_FEASTOL;
	XPRS.attr("KNITRO_PARAM_FEASTOLABS") = POI_XPRS_KNITRO_PARAM_FEASTOLABS;
	XPRS.attr("KNITRO_PARAM_BAR_INITMU") = POI_XPRS_KNITRO_PARAM_BAR_INITMU;
	XPRS.attr("KNITRO_PARAM_OBJRANGE") = POI_XPRS_KNITRO_PARAM_OBJRANGE;
	XPRS.attr("KNITRO_PARAM_OPTTOL") = POI_XPRS_KNITRO_PARAM_OPTTOL;
	XPRS.attr("KNITRO_PARAM_OPTTOLABS") = POI_XPRS_KNITRO_PARAM_OPTTOLABS;
	XPRS.attr("KNITRO_PARAM_PIVOT") = POI_XPRS_KNITRO_PARAM_PIVOT;
	XPRS.attr("KNITRO_PARAM_XTOL") = POI_XPRS_KNITRO_PARAM_XTOL;
	XPRS.attr("KNITRO_PARAM_DEBUG") = POI_XPRS_KNITRO_PARAM_DEBUG;
	XPRS.attr("KNITRO_PARAM_MULTISTART") = POI_XPRS_KNITRO_PARAM_MULTISTART;
	XPRS.attr("KNITRO_PARAM_MSMAXSOLVES") = POI_XPRS_KNITRO_PARAM_MSMAXSOLVES;
	XPRS.attr("KNITRO_PARAM_MSMAXBNDRANGE") = POI_XPRS_KNITRO_PARAM_MSMAXBNDRANGE;
	XPRS.attr("KNITRO_PARAM_LMSIZE") = POI_XPRS_KNITRO_PARAM_LMSIZE;
	XPRS.attr("KNITRO_PARAM_BAR_MAXCROSSIT") = POI_XPRS_KNITRO_PARAM_BAR_MAXCROSSIT;
	XPRS.attr("KNITRO_PARAM_BLASOPTION") = POI_XPRS_KNITRO_PARAM_BLASOPTION;
	XPRS.attr("KNITRO_PARAM_BAR_MAXREFACTOR") = POI_XPRS_KNITRO_PARAM_BAR_MAXREFACTOR;
	XPRS.attr("KNITRO_PARAM_BAR_MAXBACKTRACK") = POI_XPRS_KNITRO_PARAM_BAR_MAXBACKTRACK;
	XPRS.attr("KNITRO_PARAM_BAR_PENRULE") = POI_XPRS_KNITRO_PARAM_BAR_PENRULE;
	XPRS.attr("KNITRO_PARAM_BAR_PENCONS") = POI_XPRS_KNITRO_PARAM_BAR_PENCONS;
	XPRS.attr("KNITRO_PARAM_MSNUMTOSAVE") = POI_XPRS_KNITRO_PARAM_MSNUMTOSAVE;
	XPRS.attr("KNITRO_PARAM_MSSAVETOL") = POI_XPRS_KNITRO_PARAM_MSSAVETOL;
	XPRS.attr("KNITRO_PARAM_MSTERMINATE") = POI_XPRS_KNITRO_PARAM_MSTERMINATE;
	XPRS.attr("KNITRO_PARAM_MSSTARTPTRANGE") = POI_XPRS_KNITRO_PARAM_MSSTARTPTRANGE;
	XPRS.attr("KNITRO_PARAM_INFEASTOL") = POI_XPRS_KNITRO_PARAM_INFEASTOL;
	XPRS.attr("KNITRO_PARAM_LINSOLVER") = POI_XPRS_KNITRO_PARAM_LINSOLVER;
	XPRS.attr("KNITRO_PARAM_BAR_DIRECTINTERVAL") = POI_XPRS_KNITRO_PARAM_BAR_DIRECTINTERVAL;
	XPRS.attr("KNITRO_PARAM_PRESOLVE") = POI_XPRS_KNITRO_PARAM_PRESOLVE;
	XPRS.attr("KNITRO_PARAM_PRESOLVE_TOL") = POI_XPRS_KNITRO_PARAM_PRESOLVE_TOL;
	XPRS.attr("KNITRO_PARAM_BAR_SWITCHRULE") = POI_XPRS_KNITRO_PARAM_BAR_SWITCHRULE;
	XPRS.attr("KNITRO_PARAM_MA_TERMINATE") = POI_XPRS_KNITRO_PARAM_MA_TERMINATE;
	XPRS.attr("KNITRO_PARAM_MSSEED") = POI_XPRS_KNITRO_PARAM_MSSEED;
	XPRS.attr("KNITRO_PARAM_BAR_RELAXCONS") = POI_XPRS_KNITRO_PARAM_BAR_RELAXCONS;
	XPRS.attr("KNITRO_PARAM_SOLTYPE") = POI_XPRS_KNITRO_PARAM_SOLTYPE;
	XPRS.attr("KNITRO_PARAM_MIP_METHOD") = POI_XPRS_KNITRO_PARAM_MIP_METHOD;
	XPRS.attr("KNITRO_PARAM_MIP_BRANCHRULE") = POI_XPRS_KNITRO_PARAM_MIP_BRANCHRULE;
	XPRS.attr("KNITRO_PARAM_MIP_SELECTRULE") = POI_XPRS_KNITRO_PARAM_MIP_SELECTRULE;
	XPRS.attr("KNITRO_PARAM_MIP_INTGAPABS") = POI_XPRS_KNITRO_PARAM_MIP_INTGAPABS;
	XPRS.attr("KNITRO_PARAM_MIP_INTGAPREL") = POI_XPRS_KNITRO_PARAM_MIP_INTGAPREL;
	XPRS.attr("KNITRO_PARAM_MIP_OUTLEVEL") = POI_XPRS_KNITRO_PARAM_MIP_OUTLEVEL;
	XPRS.attr("KNITRO_PARAM_MIP_OUTINTERVAL") = POI_XPRS_KNITRO_PARAM_MIP_OUTINTERVAL;
	XPRS.attr("KNITRO_PARAM_MIP_DEBUG") = POI_XPRS_KNITRO_PARAM_MIP_DEBUG;
	XPRS.attr("KNITRO_PARAM_MIP_IMPLICATNS") = POI_XPRS_KNITRO_PARAM_MIP_IMPLICATNS;
	XPRS.attr("KNITRO_PARAM_MIP_GUB_BRANCH") = POI_XPRS_KNITRO_PARAM_MIP_GUB_BRANCH;
	XPRS.attr("KNITRO_PARAM_MIP_KNAPSACK") = POI_XPRS_KNITRO_PARAM_MIP_KNAPSACK;
	XPRS.attr("KNITRO_PARAM_MIP_ROUNDING") = POI_XPRS_KNITRO_PARAM_MIP_ROUNDING;
	XPRS.attr("KNITRO_PARAM_MIP_ROOTALG") = POI_XPRS_KNITRO_PARAM_MIP_ROOTALG;
	XPRS.attr("KNITRO_PARAM_MIP_LPALG") = POI_XPRS_KNITRO_PARAM_MIP_LPALG;
	XPRS.attr("KNITRO_PARAM_MIP_MAXNODES") = POI_XPRS_KNITRO_PARAM_MIP_MAXNODES;
	XPRS.attr("KNITRO_PARAM_MIP_HEURISTIC") = POI_XPRS_KNITRO_PARAM_MIP_HEURISTIC;
	XPRS.attr("KNITRO_PARAM_MIP_HEUR_MAXIT") = POI_XPRS_KNITRO_PARAM_MIP_HEUR_MAXIT;
	XPRS.attr("KNITRO_PARAM_MIP_PSEUDOINIT") = POI_XPRS_KNITRO_PARAM_MIP_PSEUDOINIT;
	XPRS.attr("KNITRO_PARAM_MIP_STRONG_MAXIT") = POI_XPRS_KNITRO_PARAM_MIP_STRONG_MAXIT;
	XPRS.attr("KNITRO_PARAM_MIP_STRONG_CANDLIM") = POI_XPRS_KNITRO_PARAM_MIP_STRONG_CANDLIM;
	XPRS.attr("KNITRO_PARAM_MIP_STRONG_LEVEL") = POI_XPRS_KNITRO_PARAM_MIP_STRONG_LEVEL;
	XPRS.attr("KNITRO_PARAM_PAR_NUMTHREADS") = POI_XPRS_KNITRO_PARAM_PAR_NUMTHREADS;

	nb::enum_<SOLSTATUS>(XPRS, "SOLSTATUS")
	    .value("NOTFOUND", SOLSTATUS::NOTFOUND)
	    .value("OPTIMAL", SOLSTATUS::OPTIMAL)
	    .value("FEASIBLE", SOLSTATUS::FEASIBLE)
	    .value("INFEASIBLE", SOLSTATUS::INFEASIBLE)
	    .value("UNBOUNDED", SOLSTATUS::UNBOUNDED);

	nb::enum_<SOLVESTATUS>(XPRS, "SOLVESTATUS")
	    .value("UNSTARTED", SOLVESTATUS::UNSTARTED)
	    .value("STOPPED", SOLVESTATUS::STOPPED)
	    .value("FAILED", SOLVESTATUS::FAILED)
	    .value("COMPLETED", SOLVESTATUS::COMPLETED);

	nb::enum_<LPSTATUS>(XPRS, "LPSTATUS")
	    .value("UNSTARTED", LPSTATUS::UNSTARTED)
	    .value("OPTIMAL", LPSTATUS::OPTIMAL)
	    .value("INFEAS", LPSTATUS::INFEAS)
	    .value("CUTOFF", LPSTATUS::CUTOFF)
	    .value("UNFINISHED", LPSTATUS::UNFINISHED)
	    .value("UNBOUNDED", LPSTATUS::UNBOUNDED)
	    .value("CUTOFF_IN_DUAL", LPSTATUS::CUTOFF_IN_DUAL)
	    .value("UNSOLVED", LPSTATUS::UNSOLVED)
	    .value("NONCONVEX", LPSTATUS::NONCONVEX);

	nb::enum_<MIPSTATUS>(XPRS, "MIPSTATUS")
	    .value("NOT_LOADED", MIPSTATUS::NOT_LOADED)
	    .value("LP_NOT_OPTIMAL", MIPSTATUS::LP_NOT_OPTIMAL)
	    .value("LP_OPTIMAL", MIPSTATUS::LP_OPTIMAL)
	    .value("NO_SOL_FOUND", MIPSTATUS::NO_SOL_FOUND)
	    .value("SOLUTION", MIPSTATUS::SOLUTION)
	    .value("INFEAS", MIPSTATUS::INFEAS)
	    .value("OPTIMAL", MIPSTATUS::OPTIMAL)
	    .value("UNBOUNDED", MIPSTATUS::UNBOUNDED);

	nb::enum_<NLPSTATUS>(XPRS, "NLPSTATUS")
	    .value("UNSTARTED", NLPSTATUS::UNSTARTED)
	    .value("SOLUTION", NLPSTATUS::SOLUTION)
	    .value("LOCALLY_OPTIMAL", NLPSTATUS::LOCALLY_OPTIMAL)
	    .value("OPTIMAL", NLPSTATUS::OPTIMAL)
	    .value("NOSOLUTION", NLPSTATUS::NOSOLUTION)
	    .value("LOCALLY_INFEASIBLE", NLPSTATUS::LOCALLY_INFEASIBLE)
	    .value("INFEASIBLE", NLPSTATUS::INFEASIBLE)
	    .value("UNBOUNDED", NLPSTATUS::UNBOUNDED)
	    .value("UNFINISHED", NLPSTATUS::UNFINISHED)
	    .value("UNSOLVED", NLPSTATUS::UNSOLVED);

	nb::enum_<IISSOLSTATUS>(XPRS, "IISSOLSTATUS")
	    .value("UNSTARTED", IISSOLSTATUS::UNSTARTED)
	    .value("FEASIBLE", IISSOLSTATUS::FEASIBLE)
	    .value("COMPLETED", IISSOLSTATUS::COMPLETED)
	    .value("UNFINISHED", IISSOLSTATUS::UNFINISHED);

	nb::enum_<SOLAVAILABLE>(XPRS, "SOLAVAILABLE")
	    .value("NOTFOUND", SOLAVAILABLE::NOTFOUND)
	    .value("OPTIMAL", SOLAVAILABLE::OPTIMAL)
	    .value("FEASIBLE", SOLAVAILABLE::FEASIBLE);

	nb::enum_<OPTIMIZETYPE>(XPRS, "OPTIMIZETYPE")
	    .value("NONE", OPTIMIZETYPE::NONE)
	    .value("LP", OPTIMIZETYPE::LP)
	    .value("MIP", OPTIMIZETYPE::MIP)
	    .value("LOCAL", OPTIMIZETYPE::LOCAL)
	    .value("GLOBAL", OPTIMIZETYPE::GLOBAL);

	// Define Callbacks context enum
	auto to_upper = [](char const *name) {
		std::string res(name);
		for (char &c : res)
			c = std::toupper(c);
		return res;
	};
	nb::enum_<CB_CONTEXT>(XPRS, "CB_CONTEXT", nb::is_arithmetic())
	// Use the callback list to define a value for each callback
#define XPRSCB_NB_ENUM(ID, NAME, ...) .value(to_upper(#NAME).c_str(), CB_CONTEXT::NAME)
	    XPRSCB_LIST(XPRSCB_NB_ENUM, XPRSCB_ARG_IGNORE);
#undef XPRSCB_NB_ENUM
}
