#include <nanobind/nanobind.h>

#include "pyoptinterface/xpress_model.hpp"

namespace nb = nanobind;
using namespace xpress;

void bind_xpress_constants(nb::module_ &m)
{
	nb::module_ XPRS = m.def_submodule("XPRS");
	/* useful constants */
	XPRS.attr("PLUSINFINITY") = XPRS_PLUSINFINITY;
	XPRS.attr("MINUSINFINITY") = XPRS_MINUSINFINITY;
	XPRS.attr("MAXINT") = XPRS_MAXINT;
	XPRS.attr("MAXBANNERLENGTH") = XPRS_MAXBANNERLENGTH;
	XPRS.attr("VERSION") = XPVERSION;
	XPRS.attr("VERSION_MAJOR") = XPVERSION_FULL;
	XPRS.attr("VERSION_MINOR") = XPVERSION_BUILD;
	XPRS.attr("VERSION_BUILD") = XPVERSION_MINOR;
	XPRS.attr("VERSION_FULL") = XPVERSION_MAJOR;
	XPRS.attr("MAXMESSAGELENGTH") = XPRS_MAXMESSAGELENGTH;

	/* control parameters for XPRSprob */
	/* String control parameters */
	XPRS.attr("MPSRHSNAME") = XPRS_MPSRHSNAME;
	XPRS.attr("MPSOBJNAME") = XPRS_MPSOBJNAME;
	XPRS.attr("MPSRANGENAME") = XPRS_MPSRANGENAME;
	XPRS.attr("MPSBOUNDNAME") = XPRS_MPSBOUNDNAME;
	XPRS.attr("OUTPUTMASK") = XPRS_OUTPUTMASK;
	XPRS.attr("TUNERMETHODFILE") = XPRS_TUNERMETHODFILE;
	XPRS.attr("TUNEROUTPUTPATH") = XPRS_TUNEROUTPUTPATH;
	XPRS.attr("TUNERSESSIONNAME") = XPRS_TUNERSESSIONNAME;
	XPRS.attr("COMPUTEEXECSERVICE") = XPRS_COMPUTEEXECSERVICE;
	/* Double control parameters */
	XPRS.attr("MAXCUTTIME") = XPRS_MAXCUTTIME;
	XPRS.attr("MAXSTALLTIME") = XPRS_MAXSTALLTIME;
	XPRS.attr("TUNERMAXTIME") = XPRS_TUNERMAXTIME;
	XPRS.attr("MATRIXTOL") = XPRS_MATRIXTOL;
	XPRS.attr("PIVOTTOL") = XPRS_PIVOTTOL;
	XPRS.attr("FEASTOL") = XPRS_FEASTOL;
	XPRS.attr("OUTPUTTOL") = XPRS_OUTPUTTOL;
	XPRS.attr("SOSREFTOL") = XPRS_SOSREFTOL;
	XPRS.attr("OPTIMALITYTOL") = XPRS_OPTIMALITYTOL;
	XPRS.attr("ETATOL") = XPRS_ETATOL;
	XPRS.attr("RELPIVOTTOL") = XPRS_RELPIVOTTOL;
	XPRS.attr("MIPTOL") = XPRS_MIPTOL;
	XPRS.attr("MIPTOLTARGET") = XPRS_MIPTOLTARGET;
	XPRS.attr("BARPERTURB") = XPRS_BARPERTURB;
	XPRS.attr("MIPADDCUTOFF") = XPRS_MIPADDCUTOFF;
	XPRS.attr("MIPABSCUTOFF") = XPRS_MIPABSCUTOFF;
	XPRS.attr("MIPRELCUTOFF") = XPRS_MIPRELCUTOFF;
	XPRS.attr("PSEUDOCOST") = XPRS_PSEUDOCOST;
	XPRS.attr("PENALTY") = XPRS_PENALTY;
	XPRS.attr("BIGM") = XPRS_BIGM;
	XPRS.attr("MIPABSSTOP") = XPRS_MIPABSSTOP;
	XPRS.attr("MIPRELSTOP") = XPRS_MIPRELSTOP;
	XPRS.attr("CROSSOVERACCURACYTOL") = XPRS_CROSSOVERACCURACYTOL;
	XPRS.attr("PRIMALPERTURB") = XPRS_PRIMALPERTURB;
	XPRS.attr("DUALPERTURB") = XPRS_DUALPERTURB;
	XPRS.attr("BAROBJSCALE") = XPRS_BAROBJSCALE;
	XPRS.attr("BARRHSSCALE") = XPRS_BARRHSSCALE;
	XPRS.attr("CHOLESKYTOL") = XPRS_CHOLESKYTOL;
	XPRS.attr("BARGAPSTOP") = XPRS_BARGAPSTOP;
	XPRS.attr("BARDUALSTOP") = XPRS_BARDUALSTOP;
	XPRS.attr("BARPRIMALSTOP") = XPRS_BARPRIMALSTOP;
	XPRS.attr("BARSTEPSTOP") = XPRS_BARSTEPSTOP;
	XPRS.attr("ELIMTOL") = XPRS_ELIMTOL;
	XPRS.attr("MARKOWITZTOL") = XPRS_MARKOWITZTOL;
	XPRS.attr("MIPABSGAPNOTIFY") = XPRS_MIPABSGAPNOTIFY;
	XPRS.attr("MIPRELGAPNOTIFY") = XPRS_MIPRELGAPNOTIFY;
	XPRS.attr("BARLARGEBOUND") = XPRS_BARLARGEBOUND;
	XPRS.attr("PPFACTOR") = XPRS_PPFACTOR;
	XPRS.attr("REPAIRINDEFINITEQMAX") = XPRS_REPAIRINDEFINITEQMAX;
	XPRS.attr("BARGAPTARGET") = XPRS_BARGAPTARGET;
	XPRS.attr("DUMMYCONTROL") = XPRS_DUMMYCONTROL;
	XPRS.attr("BARSTARTWEIGHT") = XPRS_BARSTARTWEIGHT;
	XPRS.attr("BARFREESCALE") = XPRS_BARFREESCALE;
	XPRS.attr("SBEFFORT") = XPRS_SBEFFORT;
	XPRS.attr("HEURDIVERANDOMIZE") = XPRS_HEURDIVERANDOMIZE;
	XPRS.attr("HEURSEARCHEFFORT") = XPRS_HEURSEARCHEFFORT;
	XPRS.attr("CUTFACTOR") = XPRS_CUTFACTOR;
	XPRS.attr("EIGENVALUETOL") = XPRS_EIGENVALUETOL;
	XPRS.attr("INDLINBIGM") = XPRS_INDLINBIGM;
	XPRS.attr("TREEMEMORYSAVINGTARGET") = XPRS_TREEMEMORYSAVINGTARGET;
	XPRS.attr("INDPRELINBIGM") = XPRS_INDPRELINBIGM;
	XPRS.attr("RELAXTREEMEMORYLIMIT") = XPRS_RELAXTREEMEMORYLIMIT;
	XPRS.attr("MIPABSGAPNOTIFYOBJ") = XPRS_MIPABSGAPNOTIFYOBJ;
	XPRS.attr("MIPABSGAPNOTIFYBOUND") = XPRS_MIPABSGAPNOTIFYBOUND;
	XPRS.attr("PRESOLVEMAXGROW") = XPRS_PRESOLVEMAXGROW;
	XPRS.attr("HEURSEARCHTARGETSIZE") = XPRS_HEURSEARCHTARGETSIZE;
	XPRS.attr("CROSSOVERRELPIVOTTOL") = XPRS_CROSSOVERRELPIVOTTOL;
	XPRS.attr("CROSSOVERRELPIVOTTOLSAFE") = XPRS_CROSSOVERRELPIVOTTOLSAFE;
	XPRS.attr("DETLOGFREQ") = XPRS_DETLOGFREQ;
	XPRS.attr("MAXIMPLIEDBOUND") = XPRS_MAXIMPLIEDBOUND;
	XPRS.attr("FEASTOLTARGET") = XPRS_FEASTOLTARGET;
	XPRS.attr("OPTIMALITYTOLTARGET") = XPRS_OPTIMALITYTOLTARGET;
	XPRS.attr("PRECOMPONENTSEFFORT") = XPRS_PRECOMPONENTSEFFORT;
	XPRS.attr("LPLOGDELAY") = XPRS_LPLOGDELAY;
	XPRS.attr("HEURDIVEITERLIMIT") = XPRS_HEURDIVEITERLIMIT;
	XPRS.attr("BARKERNEL") = XPRS_BARKERNEL;
	XPRS.attr("FEASTOLPERTURB") = XPRS_FEASTOLPERTURB;
	XPRS.attr("CROSSOVERFEASWEIGHT") = XPRS_CROSSOVERFEASWEIGHT;
	XPRS.attr("LUPIVOTTOL") = XPRS_LUPIVOTTOL;
	XPRS.attr("MIPRESTARTGAPTHRESHOLD") = XPRS_MIPRESTARTGAPTHRESHOLD;
	XPRS.attr("NODEPROBINGEFFORT") = XPRS_NODEPROBINGEFFORT;
	XPRS.attr("INPUTTOL") = XPRS_INPUTTOL;
	XPRS.attr("MIPRESTARTFACTOR") = XPRS_MIPRESTARTFACTOR;
	XPRS.attr("BAROBJPERTURB") = XPRS_BAROBJPERTURB;
	XPRS.attr("CPIALPHA") = XPRS_CPIALPHA;
	XPRS.attr("GLOBALSPATIALBRANCHPROPAGATIONEFFORT") = XPRS_GLOBALSPATIALBRANCHPROPAGATIONEFFORT;
	XPRS.attr("GLOBALSPATIALBRANCHCUTTINGEFFORT") = XPRS_GLOBALSPATIALBRANCHCUTTINGEFFORT;
	XPRS.attr("GLOBALBOUNDINGBOX") = XPRS_GLOBALBOUNDINGBOX;
	XPRS.attr("TIMELIMIT") = XPRS_TIMELIMIT;
	XPRS.attr("SOLTIMELIMIT") = XPRS_SOLTIMELIMIT;
	XPRS.attr("REPAIRINFEASTIMELIMIT") = XPRS_REPAIRINFEASTIMELIMIT;
	XPRS.attr("BARHGEXTRAPOLATE") = XPRS_BARHGEXTRAPOLATE;
	XPRS.attr("WORKLIMIT") = XPRS_WORKLIMIT;
	XPRS.attr("CALLBACKCHECKTIMEWORKDELAY") = XPRS_CALLBACKCHECKTIMEWORKDELAY;
	XPRS.attr("PREROOTWORKLIMIT") = XPRS_PREROOTWORKLIMIT;
	XPRS.attr("PREROOTEFFORT") = XPRS_PREROOTEFFORT;
	/* Integer control parameters */
	XPRS.attr("EXTRAROWS") = XPRS_EXTRAROWS;
	XPRS.attr("EXTRACOLS") = XPRS_EXTRACOLS;
	XPRS.attr("LPITERLIMIT") = XPRS_LPITERLIMIT;
	XPRS.attr("LPLOG") = XPRS_LPLOG;
	XPRS.attr("SCALING") = XPRS_SCALING;
	XPRS.attr("PRESOLVE") = XPRS_PRESOLVE;
	XPRS.attr("CRASH") = XPRS_CRASH;
	XPRS.attr("PRICINGALG") = XPRS_PRICINGALG;
	XPRS.attr("INVERTFREQ") = XPRS_INVERTFREQ;
	XPRS.attr("INVERTMIN") = XPRS_INVERTMIN;
	XPRS.attr("MAXNODE") = XPRS_MAXNODE;
	XPRS.attr("MAXMIPSOL") = XPRS_MAXMIPSOL;
	XPRS.attr("SIFTPASSES") = XPRS_SIFTPASSES;
	XPRS.attr("DEFAULTALG") = XPRS_DEFAULTALG;
	XPRS.attr("VARSELECTION") = XPRS_VARSELECTION;
	XPRS.attr("NODESELECTION") = XPRS_NODESELECTION;
	XPRS.attr("BACKTRACK") = XPRS_BACKTRACK;
	XPRS.attr("MIPLOG") = XPRS_MIPLOG;
	XPRS.attr("KEEPNROWS") = XPRS_KEEPNROWS;
	XPRS.attr("MPSECHO") = XPRS_MPSECHO;
	XPRS.attr("MAXPAGELINES") = XPRS_MAXPAGELINES;
	XPRS.attr("OUTPUTLOG") = XPRS_OUTPUTLOG;
	XPRS.attr("BARSOLUTION") = XPRS_BARSOLUTION;
	XPRS.attr("CROSSOVER") = XPRS_CROSSOVER;
	XPRS.attr("BARITERLIMIT") = XPRS_BARITERLIMIT;
	XPRS.attr("CHOLESKYALG") = XPRS_CHOLESKYALG;
	XPRS.attr("BAROUTPUT") = XPRS_BAROUTPUT;
	XPRS.attr("EXTRAMIPENTS") = XPRS_EXTRAMIPENTS;
	XPRS.attr("REFACTOR") = XPRS_REFACTOR;
	XPRS.attr("BARTHREADS") = XPRS_BARTHREADS;
	XPRS.attr("KEEPBASIS") = XPRS_KEEPBASIS;
	XPRS.attr("CROSSOVEROPS") = XPRS_CROSSOVEROPS;
	XPRS.attr("VERSION") = XPRS_VERSION;
	XPRS.attr("CROSSOVERTHREADS") = XPRS_CROSSOVERTHREADS;
	XPRS.attr("BIGMMETHOD") = XPRS_BIGMMETHOD;
	XPRS.attr("MPSNAMELENGTH") = XPRS_MPSNAMELENGTH;
	XPRS.attr("ELIMFILLIN") = XPRS_ELIMFILLIN;
	XPRS.attr("PRESOLVEOPS") = XPRS_PRESOLVEOPS;
	XPRS.attr("MIPPRESOLVE") = XPRS_MIPPRESOLVE;
	XPRS.attr("MIPTHREADS") = XPRS_MIPTHREADS;
	XPRS.attr("BARORDER") = XPRS_BARORDER;
	XPRS.attr("BREADTHFIRST") = XPRS_BREADTHFIRST;
	XPRS.attr("AUTOPERTURB") = XPRS_AUTOPERTURB;
	XPRS.attr("DENSECOLLIMIT") = XPRS_DENSECOLLIMIT;
	XPRS.attr("CALLBACKFROMMASTERTHREAD") = XPRS_CALLBACKFROMMASTERTHREAD;
	XPRS.attr("MAXMCOEFFBUFFERELEMS") = XPRS_MAXMCOEFFBUFFERELEMS;
	XPRS.attr("REFINEOPS") = XPRS_REFINEOPS;
	XPRS.attr("LPREFINEITERLIMIT") = XPRS_LPREFINEITERLIMIT;
	XPRS.attr("MIPREFINEITERLIMIT") = XPRS_MIPREFINEITERLIMIT;
	XPRS.attr("DUALIZEOPS") = XPRS_DUALIZEOPS;
	XPRS.attr("CROSSOVERITERLIMIT") = XPRS_CROSSOVERITERLIMIT;
	XPRS.attr("PREBASISRED") = XPRS_PREBASISRED;
	XPRS.attr("PRESORT") = XPRS_PRESORT;
	XPRS.attr("PREPERMUTE") = XPRS_PREPERMUTE;
	XPRS.attr("PREPERMUTESEED") = XPRS_PREPERMUTESEED;
	XPRS.attr("MAXMEMORYSOFT") = XPRS_MAXMEMORYSOFT;
	XPRS.attr("CUTFREQ") = XPRS_CUTFREQ;
	XPRS.attr("SYMSELECT") = XPRS_SYMSELECT;
	XPRS.attr("SYMMETRY") = XPRS_SYMMETRY;
	XPRS.attr("MAXMEMORYHARD") = XPRS_MAXMEMORYHARD;
	XPRS.attr("MIQCPALG") = XPRS_MIQCPALG;
	XPRS.attr("QCCUTS") = XPRS_QCCUTS;
	XPRS.attr("QCROOTALG") = XPRS_QCROOTALG;
	XPRS.attr("PRECONVERTSEPARABLE") = XPRS_PRECONVERTSEPARABLE;
	XPRS.attr("ALGAFTERNETWORK") = XPRS_ALGAFTERNETWORK;
	XPRS.attr("TRACE") = XPRS_TRACE;
	XPRS.attr("MAXIIS") = XPRS_MAXIIS;
	XPRS.attr("CPUTIME") = XPRS_CPUTIME;
	XPRS.attr("COVERCUTS") = XPRS_COVERCUTS;
	XPRS.attr("GOMCUTS") = XPRS_GOMCUTS;
	XPRS.attr("LPFOLDING") = XPRS_LPFOLDING;
	XPRS.attr("MPSFORMAT") = XPRS_MPSFORMAT;
	XPRS.attr("CUTSTRATEGY") = XPRS_CUTSTRATEGY;
	XPRS.attr("CUTDEPTH") = XPRS_CUTDEPTH;
	XPRS.attr("TREECOVERCUTS") = XPRS_TREECOVERCUTS;
	XPRS.attr("TREEGOMCUTS") = XPRS_TREEGOMCUTS;
	XPRS.attr("CUTSELECT") = XPRS_CUTSELECT;
	XPRS.attr("TREECUTSELECT") = XPRS_TREECUTSELECT;
	XPRS.attr("DUALIZE") = XPRS_DUALIZE;
	XPRS.attr("DUALGRADIENT") = XPRS_DUALGRADIENT;
	XPRS.attr("SBITERLIMIT") = XPRS_SBITERLIMIT;
	XPRS.attr("SBBEST") = XPRS_SBBEST;
	XPRS.attr("BARINDEFLIMIT") = XPRS_BARINDEFLIMIT;
	XPRS.attr("HEURFREQ") = XPRS_HEURFREQ;
	XPRS.attr("HEURDEPTH") = XPRS_HEURDEPTH;
	XPRS.attr("HEURMAXSOL") = XPRS_HEURMAXSOL;
	XPRS.attr("HEURNODES") = XPRS_HEURNODES;
	XPRS.attr("LNPBEST") = XPRS_LNPBEST;
	XPRS.attr("LNPITERLIMIT") = XPRS_LNPITERLIMIT;
	XPRS.attr("BRANCHCHOICE") = XPRS_BRANCHCHOICE;
	XPRS.attr("BARREGULARIZE") = XPRS_BARREGULARIZE;
	XPRS.attr("SBSELECT") = XPRS_SBSELECT;
	XPRS.attr("IISLOG") = XPRS_IISLOG;
	XPRS.attr("LOCALCHOICE") = XPRS_LOCALCHOICE;
	XPRS.attr("LOCALBACKTRACK") = XPRS_LOCALBACKTRACK;
	XPRS.attr("DUALSTRATEGY") = XPRS_DUALSTRATEGY;
	XPRS.attr("HEURDIVESTRATEGY") = XPRS_HEURDIVESTRATEGY;
	XPRS.attr("HEURSELECT") = XPRS_HEURSELECT;
	XPRS.attr("BARSTART") = XPRS_BARSTART;
	XPRS.attr("PRESOLVEPASSES") = XPRS_PRESOLVEPASSES;
	XPRS.attr("BARORDERTHREADS") = XPRS_BARORDERTHREADS;
	XPRS.attr("EXTRASETS") = XPRS_EXTRASETS;
	XPRS.attr("FEASIBILITYPUMP") = XPRS_FEASIBILITYPUMP;
	XPRS.attr("PRECOEFELIM") = XPRS_PRECOEFELIM;
	XPRS.attr("PREDOMCOL") = XPRS_PREDOMCOL;
	XPRS.attr("HEURSEARCHFREQ") = XPRS_HEURSEARCHFREQ;
	XPRS.attr("HEURDIVESPEEDUP") = XPRS_HEURDIVESPEEDUP;
	XPRS.attr("SBESTIMATE") = XPRS_SBESTIMATE;
	XPRS.attr("BARCORES") = XPRS_BARCORES;
	XPRS.attr("MAXCHECKSONMAXTIME") = XPRS_MAXCHECKSONMAXTIME;
	XPRS.attr("MAXCHECKSONMAXCUTTIME") = XPRS_MAXCHECKSONMAXCUTTIME;
	XPRS.attr("HISTORYCOSTS") = XPRS_HISTORYCOSTS;
	XPRS.attr("ALGAFTERCROSSOVER") = XPRS_ALGAFTERCROSSOVER;
	XPRS.attr("MUTEXCALLBACKS") = XPRS_MUTEXCALLBACKS;
	XPRS.attr("BARCRASH") = XPRS_BARCRASH;
	XPRS.attr("HEURDIVESOFTROUNDING") = XPRS_HEURDIVESOFTROUNDING;
	XPRS.attr("HEURSEARCHROOTSELECT") = XPRS_HEURSEARCHROOTSELECT;
	XPRS.attr("HEURSEARCHTREESELECT") = XPRS_HEURSEARCHTREESELECT;
	XPRS.attr("MPS18COMPATIBLE") = XPRS_MPS18COMPATIBLE;
	XPRS.attr("ROOTPRESOLVE") = XPRS_ROOTPRESOLVE;
	XPRS.attr("CROSSOVERDRP") = XPRS_CROSSOVERDRP;
	XPRS.attr("FORCEOUTPUT") = XPRS_FORCEOUTPUT;
	XPRS.attr("PRIMALOPS") = XPRS_PRIMALOPS;
	XPRS.attr("DETERMINISTIC") = XPRS_DETERMINISTIC;
	XPRS.attr("PREPROBING") = XPRS_PREPROBING;
	XPRS.attr("TREEMEMORYLIMIT") = XPRS_TREEMEMORYLIMIT;
	XPRS.attr("TREECOMPRESSION") = XPRS_TREECOMPRESSION;
	XPRS.attr("TREEDIAGNOSTICS") = XPRS_TREEDIAGNOSTICS;
	XPRS.attr("MAXTREEFILESIZE") = XPRS_MAXTREEFILESIZE;
	XPRS.attr("PRECLIQUESTRATEGY") = XPRS_PRECLIQUESTRATEGY;
	XPRS.attr("IFCHECKCONVEXITY") = XPRS_IFCHECKCONVEXITY;
	XPRS.attr("PRIMALUNSHIFT") = XPRS_PRIMALUNSHIFT;
	XPRS.attr("REPAIRINDEFINITEQ") = XPRS_REPAIRINDEFINITEQ;
	XPRS.attr("MIPRAMPUP") = XPRS_MIPRAMPUP;
	XPRS.attr("MAXLOCALBACKTRACK") = XPRS_MAXLOCALBACKTRACK;
	XPRS.attr("USERSOLHEURISTIC") = XPRS_USERSOLHEURISTIC;
	XPRS.attr("PRECONVERTOBJTOCONS") = XPRS_PRECONVERTOBJTOCONS;
	XPRS.attr("FORCEPARALLELDUAL") = XPRS_FORCEPARALLELDUAL;
	XPRS.attr("BACKTRACKTIE") = XPRS_BACKTRACKTIE;
	XPRS.attr("BRANCHDISJ") = XPRS_BRANCHDISJ;
	XPRS.attr("MIPFRACREDUCE") = XPRS_MIPFRACREDUCE;
	XPRS.attr("CONCURRENTTHREADS") = XPRS_CONCURRENTTHREADS;
	XPRS.attr("MAXSCALEFACTOR") = XPRS_MAXSCALEFACTOR;
	XPRS.attr("HEURTHREADS") = XPRS_HEURTHREADS;
	XPRS.attr("THREADS") = XPRS_THREADS;
	XPRS.attr("HEURBEFORELP") = XPRS_HEURBEFORELP;
	XPRS.attr("PREDOMROW") = XPRS_PREDOMROW;
	XPRS.attr("BRANCHSTRUCTURAL") = XPRS_BRANCHSTRUCTURAL;
	XPRS.attr("QUADRATICUNSHIFT") = XPRS_QUADRATICUNSHIFT;
	XPRS.attr("BARPRESOLVEOPS") = XPRS_BARPRESOLVEOPS;
	XPRS.attr("QSIMPLEXOPS") = XPRS_QSIMPLEXOPS;
	XPRS.attr("MIPRESTART") = XPRS_MIPRESTART;
	XPRS.attr("CONFLICTCUTS") = XPRS_CONFLICTCUTS;
	XPRS.attr("PREPROTECTDUAL") = XPRS_PREPROTECTDUAL;
	XPRS.attr("CORESPERCPU") = XPRS_CORESPERCPU;
	XPRS.attr("RESOURCESTRATEGY") = XPRS_RESOURCESTRATEGY;
	XPRS.attr("CLAMPING") = XPRS_CLAMPING;
	XPRS.attr("PREDUPROW") = XPRS_PREDUPROW;
	XPRS.attr("CPUPLATFORM") = XPRS_CPUPLATFORM;
	XPRS.attr("BARALG") = XPRS_BARALG;
	XPRS.attr("SIFTING") = XPRS_SIFTING;
	XPRS.attr("BARKEEPLASTSOL") = XPRS_BARKEEPLASTSOL;
	XPRS.attr("LPLOGSTYLE") = XPRS_LPLOGSTYLE;
	XPRS.attr("RANDOMSEED") = XPRS_RANDOMSEED;
	XPRS.attr("TREEQCCUTS") = XPRS_TREEQCCUTS;
	XPRS.attr("PRELINDEP") = XPRS_PRELINDEP;
	XPRS.attr("DUALTHREADS") = XPRS_DUALTHREADS;
	XPRS.attr("PREOBJCUTDETECT") = XPRS_PREOBJCUTDETECT;
	XPRS.attr("PREBNDREDQUAD") = XPRS_PREBNDREDQUAD;
	XPRS.attr("PREBNDREDCONE") = XPRS_PREBNDREDCONE;
	XPRS.attr("PRECOMPONENTS") = XPRS_PRECOMPONENTS;
	XPRS.attr("MAXMIPTASKS") = XPRS_MAXMIPTASKS;
	XPRS.attr("MIPTERMINATIONMETHOD") = XPRS_MIPTERMINATIONMETHOD;
	XPRS.attr("PRECONEDECOMP") = XPRS_PRECONEDECOMP;
	XPRS.attr("HEURFORCESPECIALOBJ") = XPRS_HEURFORCESPECIALOBJ;
	XPRS.attr("HEURSEARCHROOTCUTFREQ") = XPRS_HEURSEARCHROOTCUTFREQ;
	XPRS.attr("PREELIMQUAD") = XPRS_PREELIMQUAD;
	XPRS.attr("PREIMPLICATIONS") = XPRS_PREIMPLICATIONS;
	XPRS.attr("TUNERMODE") = XPRS_TUNERMODE;
	XPRS.attr("TUNERMETHOD") = XPRS_TUNERMETHOD;
	XPRS.attr("TUNERTARGET") = XPRS_TUNERTARGET;
	XPRS.attr("TUNERTHREADS") = XPRS_TUNERTHREADS;
	XPRS.attr("TUNERHISTORY") = XPRS_TUNERHISTORY;
	XPRS.attr("TUNERPERMUTE") = XPRS_TUNERPERMUTE;
	XPRS.attr("TUNERVERBOSE") = XPRS_TUNERVERBOSE;
	XPRS.attr("TUNEROUTPUT") = XPRS_TUNEROUTPUT;
	XPRS.attr("PREANALYTICCENTER") = XPRS_PREANALYTICCENTER;
	XPRS.attr("LPFLAGS") = XPRS_LPFLAGS;
	XPRS.attr("MIPKAPPAFREQ") = XPRS_MIPKAPPAFREQ;
	XPRS.attr("OBJSCALEFACTOR") = XPRS_OBJSCALEFACTOR;
	XPRS.attr("TREEFILELOGINTERVAL") = XPRS_TREEFILELOGINTERVAL;
	XPRS.attr("IGNORECONTAINERCPULIMIT") = XPRS_IGNORECONTAINERCPULIMIT;
	XPRS.attr("IGNORECONTAINERMEMORYLIMIT") = XPRS_IGNORECONTAINERMEMORYLIMIT;
	XPRS.attr("MIPDUALREDUCTIONS") = XPRS_MIPDUALREDUCTIONS;
	XPRS.attr("GENCONSDUALREDUCTIONS") = XPRS_GENCONSDUALREDUCTIONS;
	XPRS.attr("PWLDUALREDUCTIONS") = XPRS_PWLDUALREDUCTIONS;
	XPRS.attr("BARFAILITERLIMIT") = XPRS_BARFAILITERLIMIT;
	XPRS.attr("AUTOSCALING") = XPRS_AUTOSCALING;
	XPRS.attr("GENCONSABSTRANSFORMATION") = XPRS_GENCONSABSTRANSFORMATION;
	XPRS.attr("COMPUTEJOBPRIORITY") = XPRS_COMPUTEJOBPRIORITY;
	XPRS.attr("PREFOLDING") = XPRS_PREFOLDING;
	XPRS.attr("COMPUTE") = XPRS_COMPUTE;
	XPRS.attr("NETSTALLLIMIT") = XPRS_NETSTALLLIMIT;
	XPRS.attr("SERIALIZEPREINTSOL") = XPRS_SERIALIZEPREINTSOL;
	XPRS.attr("NUMERICALEMPHASIS") = XPRS_NUMERICALEMPHASIS;
	XPRS.attr("PWLNONCONVEXTRANSFORMATION") = XPRS_PWLNONCONVEXTRANSFORMATION;
	XPRS.attr("MIPCOMPONENTS") = XPRS_MIPCOMPONENTS;
	XPRS.attr("MIPCONCURRENTNODES") = XPRS_MIPCONCURRENTNODES;
	XPRS.attr("MIPCONCURRENTSOLVES") = XPRS_MIPCONCURRENTSOLVES;
	XPRS.attr("OUTPUTCONTROLS") = XPRS_OUTPUTCONTROLS;
	XPRS.attr("SIFTSWITCH") = XPRS_SIFTSWITCH;
	XPRS.attr("HEUREMPHASIS") = XPRS_HEUREMPHASIS;
	XPRS.attr("BARREFITER") = XPRS_BARREFITER;
	XPRS.attr("COMPUTELOG") = XPRS_COMPUTELOG;
	XPRS.attr("SIFTPRESOLVEOPS") = XPRS_SIFTPRESOLVEOPS;
	XPRS.attr("CHECKINPUTDATA") = XPRS_CHECKINPUTDATA;
	XPRS.attr("ESCAPENAMES") = XPRS_ESCAPENAMES;
	XPRS.attr("IOTIMEOUT") = XPRS_IOTIMEOUT;
	XPRS.attr("AUTOCUTTING") = XPRS_AUTOCUTTING;
	XPRS.attr("GLOBALNUMINITNLPCUTS") = XPRS_GLOBALNUMINITNLPCUTS;
	XPRS.attr("CALLBACKCHECKTIMEDELAY") = XPRS_CALLBACKCHECKTIMEDELAY;
	XPRS.attr("MULTIOBJOPS") = XPRS_MULTIOBJOPS;
	XPRS.attr("MULTIOBJLOG") = XPRS_MULTIOBJLOG;
	XPRS.attr("BACKGROUNDMAXTHREADS") = XPRS_BACKGROUNDMAXTHREADS;
	XPRS.attr("GLOBALLSHEURSTRATEGY") = XPRS_GLOBALLSHEURSTRATEGY;
	XPRS.attr("GLOBALSPATIALBRANCHIFPREFERORIG") = XPRS_GLOBALSPATIALBRANCHIFPREFERORIG;
	XPRS.attr("PRECONFIGURATION") = XPRS_PRECONFIGURATION;
	XPRS.attr("FEASIBILITYJUMP") = XPRS_FEASIBILITYJUMP;
	XPRS.attr("IISOPS") = XPRS_IISOPS;
	XPRS.attr("RLTCUTS") = XPRS_RLTCUTS;
	XPRS.attr("ALTERNATIVEREDCOSTS") = XPRS_ALTERNATIVEREDCOSTS;
	XPRS.attr("HEURSHIFTPROP") = XPRS_HEURSHIFTPROP;
	XPRS.attr("HEURSEARCHCOPYCONTROLS") = XPRS_HEURSEARCHCOPYCONTROLS;
	XPRS.attr("GLOBALNLPCUTS") = XPRS_GLOBALNLPCUTS;
	XPRS.attr("GLOBALTREENLPCUTS") = XPRS_GLOBALTREENLPCUTS;
	XPRS.attr("BARHGOPS") = XPRS_BARHGOPS;
	XPRS.attr("BARHGMAXRESTARTS") = XPRS_BARHGMAXRESTARTS;
	XPRS.attr("MCFCUTSTRATEGY") = XPRS_MCFCUTSTRATEGY;
	XPRS.attr("PREROOTTHREADS") = XPRS_PREROOTTHREADS;
	XPRS.attr("BARITERATIVE") = XPRS_BARITERATIVE;
	/* Integer control parameters that support 64-bit values  */
	XPRS.attr("EXTRAELEMS") = XPRS_EXTRAELEMS;
	XPRS.attr("EXTRASETELEMS") = XPRS_EXTRASETELEMS;
	XPRS.attr("BACKGROUNDSELECT") = XPRS_BACKGROUNDSELECT;
	XPRS.attr("HEURSEARCHBACKGROUNDSELECT") = XPRS_HEURSEARCHBACKGROUNDSELECT;

	/* attributes for XPRSprob */
	/* String attributes */
	XPRS.attr("MATRIXNAME") = XPRS_MATRIXNAME;
	XPRS.attr("BOUNDNAME") = XPRS_BOUNDNAME;
	XPRS.attr("RHSNAME") = XPRS_RHSNAME;
	XPRS.attr("RANGENAME") = XPRS_RANGENAME;
	XPRS.attr("XPRESSVERSION") = XPRS_XPRESSVERSION;
	XPRS.attr("UUID") = XPRS_UUID;
	/* Double attributes */
	XPRS.attr("MIPSOLTIME") = XPRS_MIPSOLTIME;
	XPRS.attr("TIME") = XPRS_TIME;
	XPRS.attr("LPOBJVAL") = XPRS_LPOBJVAL;
	XPRS.attr("SUMPRIMALINF") = XPRS_SUMPRIMALINF;
	XPRS.attr("MIPOBJVAL") = XPRS_MIPOBJVAL;
	XPRS.attr("BESTBOUND") = XPRS_BESTBOUND;
	XPRS.attr("OBJRHS") = XPRS_OBJRHS;
	XPRS.attr("MIPBESTOBJVAL") = XPRS_MIPBESTOBJVAL;
	XPRS.attr("OBJSENSE") = XPRS_OBJSENSE;
	XPRS.attr("BRANCHVALUE") = XPRS_BRANCHVALUE;
	XPRS.attr("PENALTYVALUE") = XPRS_PENALTYVALUE;
	XPRS.attr("CURRMIPCUTOFF") = XPRS_CURRMIPCUTOFF;
	XPRS.attr("BARCONDA") = XPRS_BARCONDA;
	XPRS.attr("BARCONDD") = XPRS_BARCONDD;
	XPRS.attr("MAXABSPRIMALINFEAS") = XPRS_MAXABSPRIMALINFEAS;
	XPRS.attr("MAXRELPRIMALINFEAS") = XPRS_MAXRELPRIMALINFEAS;
	XPRS.attr("MAXABSDUALINFEAS") = XPRS_MAXABSDUALINFEAS;
	XPRS.attr("MAXRELDUALINFEAS") = XPRS_MAXRELDUALINFEAS;
	XPRS.attr("PRIMALDUALINTEGRAL") = XPRS_PRIMALDUALINTEGRAL;
	XPRS.attr("MAXMIPINFEAS") = XPRS_MAXMIPINFEAS;
	XPRS.attr("ATTENTIONLEVEL") = XPRS_ATTENTIONLEVEL;
	XPRS.attr("MAXKAPPA") = XPRS_MAXKAPPA;
	XPRS.attr("TREECOMPLETION") = XPRS_TREECOMPLETION;
	XPRS.attr("PREDICTEDATTLEVEL") = XPRS_PREDICTEDATTLEVEL;
	XPRS.attr("OBSERVEDPRIMALINTEGRAL") = XPRS_OBSERVEDPRIMALINTEGRAL;
	XPRS.attr("CPISCALEFACTOR") = XPRS_CPISCALEFACTOR;
	XPRS.attr("OBJVAL") = XPRS_OBJVAL;
	XPRS.attr("WORK") = XPRS_WORK;
	XPRS.attr("BARPRIMALOBJ") = XPRS_BARPRIMALOBJ;
	XPRS.attr("BARDUALOBJ") = XPRS_BARDUALOBJ;
	XPRS.attr("BARPRIMALINF") = XPRS_BARPRIMALINF;
	XPRS.attr("BARDUALINF") = XPRS_BARDUALINF;
	XPRS.attr("BARCGAP") = XPRS_BARCGAP;
	/* Integer attributes */
	XPRS.attr("ROWS") = XPRS_ROWS;
	XPRS.attr("SETS") = XPRS_SETS;
	XPRS.attr("PRIMALINFEAS") = XPRS_PRIMALINFEAS;
	XPRS.attr("DUALINFEAS") = XPRS_DUALINFEAS;
	XPRS.attr("SIMPLEXITER") = XPRS_SIMPLEXITER;
	XPRS.attr("LPSTATUS") = XPRS_LPSTATUS;
	XPRS.attr("MIPSTATUS") = XPRS_MIPSTATUS;
	XPRS.attr("CUTS") = XPRS_CUTS;
	XPRS.attr("NODES") = XPRS_NODES;
	XPRS.attr("NODEDEPTH") = XPRS_NODEDEPTH;
	XPRS.attr("ACTIVENODES") = XPRS_ACTIVENODES;
	XPRS.attr("MIPSOLNODE") = XPRS_MIPSOLNODE;
	XPRS.attr("MIPSOLS") = XPRS_MIPSOLS;
	XPRS.attr("COLS") = XPRS_COLS;
	XPRS.attr("SPAREROWS") = XPRS_SPAREROWS;
	XPRS.attr("SPARECOLS") = XPRS_SPARECOLS;
	XPRS.attr("SPAREMIPENTS") = XPRS_SPAREMIPENTS;
	XPRS.attr("ERRORCODE") = XPRS_ERRORCODE;
	XPRS.attr("MIPINFEAS") = XPRS_MIPINFEAS;
	XPRS.attr("PRESOLVESTATE") = XPRS_PRESOLVESTATE;
	XPRS.attr("PARENTNODE") = XPRS_PARENTNODE;
	XPRS.attr("NAMELENGTH") = XPRS_NAMELENGTH;
	XPRS.attr("QELEMS") = XPRS_QELEMS;
	XPRS.attr("NUMIIS") = XPRS_NUMIIS;
	XPRS.attr("MIPENTS") = XPRS_MIPENTS;
	XPRS.attr("BRANCHVAR") = XPRS_BRANCHVAR;
	XPRS.attr("MIPTHREADID") = XPRS_MIPTHREADID;
	XPRS.attr("ALGORITHM") = XPRS_ALGORITHM;
	XPRS.attr("CROSSOVERITER") = XPRS_CROSSOVERITER;
	XPRS.attr("SOLSTATUS") = XPRS_SOLSTATUS;
	XPRS.attr("CUTROUNDS") = XPRS_CUTROUNDS;
	XPRS.attr("ORIGINALROWS") = XPRS_ORIGINALROWS;
	XPRS.attr("CALLBACKCOUNT_OPTNODE") = XPRS_CALLBACKCOUNT_OPTNODE;
	XPRS.attr("ORIGINALQELEMS") = XPRS_ORIGINALQELEMS;
	XPRS.attr("MAXPROBNAMELENGTH") = XPRS_MAXPROBNAMELENGTH;
	XPRS.attr("STOPSTATUS") = XPRS_STOPSTATUS;
	XPRS.attr("ORIGINALMIPENTS") = XPRS_ORIGINALMIPENTS;
	XPRS.attr("ORIGINALSETS") = XPRS_ORIGINALSETS;
	XPRS.attr("SPARESETS") = XPRS_SPARESETS;
	XPRS.attr("CHECKSONMAXTIME") = XPRS_CHECKSONMAXTIME;
	XPRS.attr("CHECKSONMAXCUTTIME") = XPRS_CHECKSONMAXCUTTIME;
	XPRS.attr("ORIGINALCOLS") = XPRS_ORIGINALCOLS;
	XPRS.attr("QCELEMS") = XPRS_QCELEMS;
	XPRS.attr("QCONSTRAINTS") = XPRS_QCONSTRAINTS;
	XPRS.attr("ORIGINALQCELEMS") = XPRS_ORIGINALQCELEMS;
	XPRS.attr("ORIGINALQCONSTRAINTS") = XPRS_ORIGINALQCONSTRAINTS;
	XPRS.attr("PEAKTOTALTREEMEMORYUSAGE") = XPRS_PEAKTOTALTREEMEMORYUSAGE;
	XPRS.attr("CURRENTNODE") = XPRS_CURRENTNODE;
	XPRS.attr("TREEMEMORYUSAGE") = XPRS_TREEMEMORYUSAGE;
	XPRS.attr("TREEFILESIZE") = XPRS_TREEFILESIZE;
	XPRS.attr("TREEFILEUSAGE") = XPRS_TREEFILEUSAGE;
	XPRS.attr("INDICATORS") = XPRS_INDICATORS;
	XPRS.attr("ORIGINALINDICATORS") = XPRS_ORIGINALINDICATORS;
	XPRS.attr("CORESPERCPUDETECTED") = XPRS_CORESPERCPUDETECTED;
	XPRS.attr("CPUSDETECTED") = XPRS_CPUSDETECTED;
	XPRS.attr("CORESDETECTED") = XPRS_CORESDETECTED;
	XPRS.attr("PHYSICALCORESDETECTED") = XPRS_PHYSICALCORESDETECTED;
	XPRS.attr("PHYSICALCORESPERCPUDETECTED") = XPRS_PHYSICALCORESPERCPUDETECTED;
	XPRS.attr("OPTIMIZETYPEUSED") = XPRS_OPTIMIZETYPEUSED;
	XPRS.attr("BARSING") = XPRS_BARSING;
	XPRS.attr("BARSINGR") = XPRS_BARSINGR;
	XPRS.attr("PRESOLVEINDEX") = XPRS_PRESOLVEINDEX;
	XPRS.attr("CONES") = XPRS_CONES;
	XPRS.attr("CONEELEMS") = XPRS_CONEELEMS;
	XPRS.attr("PWLCONS") = XPRS_PWLCONS;
	XPRS.attr("GENCONS") = XPRS_GENCONS;
	XPRS.attr("TREERESTARTS") = XPRS_TREERESTARTS;
	XPRS.attr("ORIGINALPWLS") = XPRS_ORIGINALPWLS;
	XPRS.attr("ORIGINALGENCONS") = XPRS_ORIGINALGENCONS;
	XPRS.attr("COMPUTEEXECUTIONS") = XPRS_COMPUTEEXECUTIONS;
	XPRS.attr("RESTARTS") = XPRS_RESTARTS;
	XPRS.attr("SOLVESTATUS") = XPRS_SOLVESTATUS;
	XPRS.attr("GLOBALBOUNDINGBOXAPPLIED") = XPRS_GLOBALBOUNDINGBOXAPPLIED;
	XPRS.attr("OBJECTIVES") = XPRS_OBJECTIVES;
	XPRS.attr("SOLVEDOBJS") = XPRS_SOLVEDOBJS;
	XPRS.attr("OBJSTOSOLVE") = XPRS_OBJSTOSOLVE;
	XPRS.attr("GLOBALNLPINFEAS") = XPRS_GLOBALNLPINFEAS;
	XPRS.attr("IISSOLSTATUS") = XPRS_IISSOLSTATUS;
	XPRS.attr("INPUTROWS") = XPRS_INPUTROWS;
	XPRS.attr("INPUTCOLS") = XPRS_INPUTCOLS;
	XPRS.attr("BARITER") = XPRS_BARITER;
	XPRS.attr("BARDENSECOL") = XPRS_BARDENSECOL;
	XPRS.attr("BARCROSSOVER") = XPRS_BARCROSSOVER;
	/* Integer attributes that support 64-bit values */
	XPRS.attr("SETMEMBERS") = XPRS_SETMEMBERS;
	XPRS.attr("ELEMS") = XPRS_ELEMS;
	XPRS.attr("SPAREELEMS") = XPRS_SPAREELEMS;
	XPRS.attr("SYSTEMMEMORY") = XPRS_SYSTEMMEMORY;
	XPRS.attr("ORIGINALSETMEMBERS") = XPRS_ORIGINALSETMEMBERS;
	XPRS.attr("SPARESETELEMS") = XPRS_SPARESETELEMS;
	XPRS.attr("CURRENTMEMORY") = XPRS_CURRENTMEMORY;
	XPRS.attr("PEAKMEMORY") = XPRS_PEAKMEMORY;
	XPRS.attr("TOTALMEMORY") = XPRS_TOTALMEMORY;
	XPRS.attr("AVAILABLEMEMORY") = XPRS_AVAILABLEMEMORY;
	XPRS.attr("PWLPOINTS") = XPRS_PWLPOINTS;
	XPRS.attr("GENCONCOLS") = XPRS_GENCONCOLS;
	XPRS.attr("GENCONVALS") = XPRS_GENCONVALS;
	XPRS.attr("ORIGINALPWLPOINTS") = XPRS_ORIGINALPWLPOINTS;
	XPRS.attr("ORIGINALGENCONCOLS") = XPRS_ORIGINALGENCONCOLS;
	XPRS.attr("ORIGINALGENCONVALS") = XPRS_ORIGINALGENCONVALS;
	XPRS.attr("MEMORYLIMITDETECTED") = XPRS_MEMORYLIMITDETECTED;
	XPRS.attr("BARAASIZE") = XPRS_BARAASIZE;
	XPRS.attr("BARLSIZE") = XPRS_BARLSIZE;

	// Nonlinear solver related controls and attributes
	XPRS.attr("NLPFUNCEVAL") = XPRS_NLPFUNCEVAL;
	XPRS.attr("NLPLOG") = XPRS_NLPLOG;
	XPRS.attr("NLPKEEPEQUALSCOLUMN") = XPRS_NLPKEEPEQUALSCOLUMN;
	XPRS.attr("NLPEVALUATE") = XPRS_NLPEVALUATE;
	XPRS.attr("NLPPRESOLVE") = XPRS_NLPPRESOLVE;
	XPRS.attr("SLPLOG") = XPRS_SLPLOG;
	XPRS.attr("LOCALSOLVER") = XPRS_LOCALSOLVER;
	XPRS.attr("NLPSTOPOUTOFRANGE") = XPRS_NLPSTOPOUTOFRANGE;
	XPRS.attr("NLPTHREADSAFEUSERFUNC") = XPRS_NLPTHREADSAFEUSERFUNC;
	XPRS.attr("NLPJACOBIAN") = XPRS_NLPJACOBIAN;
	XPRS.attr("NLPHESSIAN") = XPRS_NLPHESSIAN;
	XPRS.attr("MULTISTART") = XPRS_MULTISTART;
	XPRS.attr("MULTISTART_THREADS") = XPRS_MULTISTART_THREADS;
	XPRS.attr("MULTISTART_MAXSOLVES") = XPRS_MULTISTART_MAXSOLVES;
	XPRS.attr("MULTISTART_MAXTIME") = XPRS_MULTISTART_MAXTIME;
	XPRS.attr("NLPMAXTIME") = XPRS_NLPMAXTIME;
	XPRS.attr("NLPDERIVATIVES") = XPRS_NLPDERIVATIVES;
	XPRS.attr("NLPREFORMULATE") = XPRS_NLPREFORMULATE;
	XPRS.attr("NLPPRESOLVEOPS") = XPRS_NLPPRESOLVEOPS;
	XPRS.attr("MULTISTART_LOG") = XPRS_MULTISTART_LOG;
	XPRS.attr("MULTISTART_SEED") = XPRS_MULTISTART_SEED;
	XPRS.attr("MULTISTART_POOLSIZE") = XPRS_MULTISTART_POOLSIZE;
	XPRS.attr("NLPPOSTSOLVE") = XPRS_NLPPOSTSOLVE;
	XPRS.attr("NLPDETERMINISTIC") = XPRS_NLPDETERMINISTIC;
	XPRS.attr("NLPPRESOLVELEVEL") = XPRS_NLPPRESOLVELEVEL;
	XPRS.attr("NLPPROBING") = XPRS_NLPPROBING;
	XPRS.attr("NLPCALCTHREADS") = XPRS_NLPCALCTHREADS;
	XPRS.attr("NLPTHREADS") = XPRS_NLPTHREADS;
	XPRS.attr("NLPFINDIV") = XPRS_NLPFINDIV;
	XPRS.attr("NLPLINQUADBR") = XPRS_NLPLINQUADBR;
	XPRS.attr("NLPSOLVER") = XPRS_NLPSOLVER;
	// SLP related integer controls
	XPRS.attr("SLPALGORITHM") = XPRS_SLPALGORITHM;
	XPRS.attr("SLPAUGMENTATION") = XPRS_SLPAUGMENTATION;
	XPRS.attr("SLPBARLIMIT") = XPRS_SLPBARLIMIT;
	XPRS.attr("SLPCASCADE") = XPRS_SLPCASCADE;
	XPRS.attr("SLPCASCADENLIMIT") = XPRS_SLPCASCADENLIMIT;
	XPRS.attr("SLPDAMPSTART") = XPRS_SLPDAMPSTART;
	XPRS.attr("SLPCUTSTRATEGY") = XPRS_SLPCUTSTRATEGY;
	XPRS.attr("SLPDELTAZLIMIT") = XPRS_SLPDELTAZLIMIT;
	XPRS.attr("SLPINFEASLIMIT") = XPRS_SLPINFEASLIMIT;
	XPRS.attr("SLPITERLIMIT") = XPRS_SLPITERLIMIT;
	XPRS.attr("SLPSAMECOUNT") = XPRS_SLPSAMECOUNT;
	XPRS.attr("SLPSAMEDAMP") = XPRS_SLPSAMEDAMP;
	XPRS.attr("SLPSBSTART") = XPRS_SLPSBSTART;
	XPRS.attr("SLPXCOUNT") = XPRS_SLPXCOUNT;
	XPRS.attr("SLPXLIMIT") = XPRS_SLPXLIMIT;
	XPRS.attr("SLPDELAYUPDATEROWS") = XPRS_SLPDELAYUPDATEROWS;
	XPRS.attr("SLPAUTOSAVE") = XPRS_SLPAUTOSAVE;
	XPRS.attr("SLPANALYZE") = XPRS_SLPANALYZE;
	XPRS.attr("SLPOCOUNT") = XPRS_SLPOCOUNT;
	XPRS.attr("SLPMIPALGORITHM") = XPRS_SLPMIPALGORITHM;
	XPRS.attr("SLPMIPRELAXSTEPBOUNDS") = XPRS_SLPMIPRELAXSTEPBOUNDS;
	XPRS.attr("SLPMIPFIXSTEPBOUNDS") = XPRS_SLPMIPFIXSTEPBOUNDS;
	XPRS.attr("SLPMIPITERLIMIT") = XPRS_SLPMIPITERLIMIT;
	XPRS.attr("SLPMIPCUTOFFLIMIT") = XPRS_SLPMIPCUTOFFLIMIT;
	XPRS.attr("SLPMIPOCOUNT") = XPRS_SLPMIPOCOUNT;
	XPRS.attr("SLPMIPDEFAULTALGORITHM") = XPRS_SLPMIPDEFAULTALGORITHM;
	XPRS.attr("SLPMIPLOG") = XPRS_SLPMIPLOG;
	XPRS.attr("SLPDELTAOFFSET") = XPRS_SLPDELTAOFFSET;
	XPRS.attr("SLPUPDATEOFFSET") = XPRS_SLPUPDATEOFFSET;
	XPRS.attr("SLPERROROFFSET") = XPRS_SLPERROROFFSET;
	XPRS.attr("SLPSBROWOFFSET") = XPRS_SLPSBROWOFFSET;
	XPRS.attr("SLPVCOUNT") = XPRS_SLPVCOUNT;
	XPRS.attr("SLPVLIMIT") = XPRS_SLPVLIMIT;
	XPRS.attr("SLPSCALE") = XPRS_SLPSCALE;
	XPRS.attr("SLPSCALECOUNT") = XPRS_SLPSCALECOUNT;
	XPRS.attr("SLPECFCHECK") = XPRS_SLPECFCHECK;
	XPRS.attr("SLPMIPCUTOFFCOUNT") = XPRS_SLPMIPCUTOFFCOUNT;
	XPRS.attr("SLPWCOUNT") = XPRS_SLPWCOUNT;
	XPRS.attr("SLPUNFINISHEDLIMIT") = XPRS_SLPUNFINISHEDLIMIT;
	XPRS.attr("SLPCONVERGENCEOPS") = XPRS_SLPCONVERGENCEOPS;
	XPRS.attr("SLPZEROCRITERION") = XPRS_SLPZEROCRITERION;
	XPRS.attr("SLPZEROCRITERIONSTART") = XPRS_SLPZEROCRITERIONSTART;
	XPRS.attr("SLPZEROCRITERIONCOUNT") = XPRS_SLPZEROCRITERIONCOUNT;
	XPRS.attr("SLPLSPATTERNLIMIT") = XPRS_SLPLSPATTERNLIMIT;
	XPRS.attr("SLPLSITERLIMIT") = XPRS_SLPLSITERLIMIT;
	XPRS.attr("SLPLSSTART") = XPRS_SLPLSSTART;
	XPRS.attr("SLPPENALTYINFOSTART") = XPRS_SLPPENALTYINFOSTART;
	XPRS.attr("SLPFILTER") = XPRS_SLPFILTER;
	XPRS.attr("SLPTRACEMASKOPS") = XPRS_SLPTRACEMASKOPS;
	XPRS.attr("SLPLSZEROLIMIT") = XPRS_SLPLSZEROLIMIT;
	XPRS.attr("SLPHEURSTRATEGY") = XPRS_SLPHEURSTRATEGY;
	XPRS.attr("SLPBARCROSSOVERSTART") = XPRS_SLPBARCROSSOVERSTART;
	XPRS.attr("SLPBARSTALLINGLIMIT") = XPRS_SLPBARSTALLINGLIMIT;
	XPRS.attr("SLPBARSTALLINGOBJLIMIT") = XPRS_SLPBARSTALLINGOBJLIMIT;
	XPRS.attr("SLPBARSTARTOPS") = XPRS_SLPBARSTARTOPS;
	XPRS.attr("SLPGRIDHEURSELECT") = XPRS_SLPGRIDHEURSELECT;
	// Nonlinear related double controls
	XPRS.attr("NLPINFINITY") = XPRS_NLPINFINITY;
	XPRS.attr("NLPZERO") = XPRS_NLPZERO;
	XPRS.attr("NLPDEFAULTIV") = XPRS_NLPDEFAULTIV;
	XPRS.attr("NLPOPTTIME") = XPRS_NLPOPTTIME;
	XPRS.attr("NLPVALIDATIONTOL_A") = XPRS_NLPVALIDATIONTOL_A;
	XPRS.attr("NLPVALIDATIONTOL_R") = XPRS_NLPVALIDATIONTOL_R;
	XPRS.attr("NLPVALIDATIONINDEX_A") = XPRS_NLPVALIDATIONINDEX_A;
	XPRS.attr("NLPVALIDATIONINDEX_R") = XPRS_NLPVALIDATIONINDEX_R;
	XPRS.attr("NLPPRIMALINTEGRALREF") = XPRS_NLPPRIMALINTEGRALREF;
	XPRS.attr("NLPPRIMALINTEGRALALPHA") = XPRS_NLPPRIMALINTEGRALALPHA;
	XPRS.attr("NLPOBJVAL") = XPRS_NLPOBJVAL;
	XPRS.attr("NLPPRESOLVEZERO") = XPRS_NLPPRESOLVEZERO;
	XPRS.attr("NLPMERITLAMBDA") = XPRS_NLPMERITLAMBDA;
	XPRS.attr("MSMAXBOUNDRANGE") = XPRS_MSMAXBOUNDRANGE;
	XPRS.attr("NLPVALIDATIONTOL_K") = XPRS_NLPVALIDATIONTOL_K;
	XPRS.attr("NLPPRESOLVE_ELIMTOL") = XPRS_NLPPRESOLVE_ELIMTOL;
	XPRS.attr("NLPVALIDATIONTARGET_R") = XPRS_NLPVALIDATIONTARGET_R;
	XPRS.attr("NLPVALIDATIONTARGET_K") = XPRS_NLPVALIDATIONTARGET_K;
	XPRS.attr("NLPVALIDATIONFACTOR") = XPRS_NLPVALIDATIONFACTOR;
	XPRS.attr("NLPRELTOLBOUNDTHRESHOLD") = XPRS_NLPRELTOLBOUNDTHRESHOLD;
	// SLP related double controls
	XPRS.attr("SLPDAMP") = XPRS_SLPDAMP;
	XPRS.attr("SLPDAMPEXPAND") = XPRS_SLPDAMPEXPAND;
	XPRS.attr("SLPDAMPSHRINK") = XPRS_SLPDAMPSHRINK;
	XPRS.attr("SLPDELTA_A") = XPRS_SLPDELTA_A;
	XPRS.attr("SLPDELTA_R") = XPRS_SLPDELTA_R;
	XPRS.attr("SLPDELTA_Z") = XPRS_SLPDELTA_Z;
	XPRS.attr("SLPDELTACOST") = XPRS_SLPDELTACOST;
	XPRS.attr("SLPDELTAMAXCOST") = XPRS_SLPDELTAMAXCOST;
	XPRS.attr("SLPDJTOL") = XPRS_SLPDJTOL;
	XPRS.attr("SLPERRORCOST") = XPRS_SLPERRORCOST;
	XPRS.attr("SLPERRORMAXCOST") = XPRS_SLPERRORMAXCOST;
	XPRS.attr("SLPERRORTOL_A") = XPRS_SLPERRORTOL_A;
	XPRS.attr("SLPEXPAND") = XPRS_SLPEXPAND;
	XPRS.attr("SLPMAXWEIGHT") = XPRS_SLPMAXWEIGHT;
	XPRS.attr("SLPMINWEIGHT") = XPRS_SLPMINWEIGHT;
	XPRS.attr("SLPSHRINK") = XPRS_SLPSHRINK;
	XPRS.attr("SLPCTOL") = XPRS_SLPCTOL;
	XPRS.attr("SLPATOL_A") = XPRS_SLPATOL_A;
	XPRS.attr("SLPATOL_R") = XPRS_SLPATOL_R;
	XPRS.attr("SLPMTOL_A") = XPRS_SLPMTOL_A;
	XPRS.attr("SLPMTOL_R") = XPRS_SLPMTOL_R;
	XPRS.attr("SLPITOL_A") = XPRS_SLPITOL_A;
	XPRS.attr("SLPITOL_R") = XPRS_SLPITOL_R;
	XPRS.attr("SLPSTOL_A") = XPRS_SLPSTOL_A;
	XPRS.attr("SLPSTOL_R") = XPRS_SLPSTOL_R;
	XPRS.attr("SLPMVTOL") = XPRS_SLPMVTOL;
	XPRS.attr("SLPXTOL_A") = XPRS_SLPXTOL_A;
	XPRS.attr("SLPXTOL_R") = XPRS_SLPXTOL_R;
	XPRS.attr("SLPDEFAULTSTEPBOUND") = XPRS_SLPDEFAULTSTEPBOUND;
	XPRS.attr("SLPDAMPMAX") = XPRS_SLPDAMPMAX;
	XPRS.attr("SLPDAMPMIN") = XPRS_SLPDAMPMIN;
	XPRS.attr("SLPDELTACOSTFACTOR") = XPRS_SLPDELTACOSTFACTOR;
	XPRS.attr("SLPERRORCOSTFACTOR") = XPRS_SLPERRORCOSTFACTOR;
	XPRS.attr("SLPERRORTOL_P") = XPRS_SLPERRORTOL_P;
	XPRS.attr("SLPCASCADETOL_PA") = XPRS_SLPCASCADETOL_PA;
	XPRS.attr("SLPCASCADETOL_PR") = XPRS_SLPCASCADETOL_PR;
	XPRS.attr("SLPCASCADETOL_Z") = XPRS_SLPCASCADETOL_Z;
	XPRS.attr("SLPOTOL_A") = XPRS_SLPOTOL_A;
	XPRS.attr("SLPOTOL_R") = XPRS_SLPOTOL_R;
	XPRS.attr("SLPDELTA_X") = XPRS_SLPDELTA_X;
	XPRS.attr("SLPERRORCOSTS") = XPRS_SLPERRORCOSTS;
	XPRS.attr("SLPGRANULARITY") = XPRS_SLPGRANULARITY;
	XPRS.attr("SLPMIPCUTOFF_A") = XPRS_SLPMIPCUTOFF_A;
	XPRS.attr("SLPMIPCUTOFF_R") = XPRS_SLPMIPCUTOFF_R;
	XPRS.attr("SLPMIPOTOL_A") = XPRS_SLPMIPOTOL_A;
	XPRS.attr("SLPMIPOTOL_R") = XPRS_SLPMIPOTOL_R;
	XPRS.attr("SLPESCALATION") = XPRS_SLPESCALATION;
	XPRS.attr("SLPOBJTOPENALTYCOST") = XPRS_SLPOBJTOPENALTYCOST;
	XPRS.attr("SLPSHRINKBIAS") = XPRS_SLPSHRINKBIAS;
	XPRS.attr("SLPFEASTOLTARGET") = XPRS_SLPFEASTOLTARGET;
	XPRS.attr("SLPOPTIMALITYTOLTARGET") = XPRS_SLPOPTIMALITYTOLTARGET;
	XPRS.attr("SLPDELTA_INFINITY") = XPRS_SLPDELTA_INFINITY;
	XPRS.attr("SLPVTOL_A") = XPRS_SLPVTOL_A;
	XPRS.attr("SLPVTOL_R") = XPRS_SLPVTOL_R;
	XPRS.attr("SLPETOL_A") = XPRS_SLPETOL_A;
	XPRS.attr("SLPETOL_R") = XPRS_SLPETOL_R;
	XPRS.attr("SLPEVTOL_A") = XPRS_SLPEVTOL_A;
	XPRS.attr("SLPEVTOL_R") = XPRS_SLPEVTOL_R;
	XPRS.attr("SLPDELTA_ZERO") = XPRS_SLPDELTA_ZERO;
	XPRS.attr("SLPMINSBFACTOR") = XPRS_SLPMINSBFACTOR;
	XPRS.attr("SLPCLAMPVALIDATIONTOL_A") = XPRS_SLPCLAMPVALIDATIONTOL_A;
	XPRS.attr("SLPCLAMPVALIDATIONTOL_R") = XPRS_SLPCLAMPVALIDATIONTOL_R;
	XPRS.attr("SLPCLAMPSHRINK") = XPRS_SLPCLAMPSHRINK;
	XPRS.attr("SLPECFTOL_A") = XPRS_SLPECFTOL_A;
	XPRS.attr("SLPECFTOL_R") = XPRS_SLPECFTOL_R;
	XPRS.attr("SLPWTOL_A") = XPRS_SLPWTOL_A;
	XPRS.attr("SLPWTOL_R") = XPRS_SLPWTOL_R;
	XPRS.attr("SLPMATRIXTOL") = XPRS_SLPMATRIXTOL;
	XPRS.attr("SLPDRFIXRANGE") = XPRS_SLPDRFIXRANGE;
	XPRS.attr("SLPDRCOLTOL") = XPRS_SLPDRCOLTOL;
	XPRS.attr("SLPMIPERRORTOL_A") = XPRS_SLPMIPERRORTOL_A;
	XPRS.attr("SLPMIPERRORTOL_R") = XPRS_SLPMIPERRORTOL_R;
	XPRS.attr("SLPCDTOL_A") = XPRS_SLPCDTOL_A;
	XPRS.attr("SLPCDTOL_R") = XPRS_SLPCDTOL_R;
	XPRS.attr("SLPENFORCEMAXCOST") = XPRS_SLPENFORCEMAXCOST;
	XPRS.attr("SLPENFORCECOSTSHRINK") = XPRS_SLPENFORCECOSTSHRINK;
	XPRS.attr("SLPDRCOLDJTOL") = XPRS_SLPDRCOLDJTOL;
	XPRS.attr("SLPBARSTALLINGTOL") = XPRS_SLPBARSTALLINGTOL;
	XPRS.attr("SLPOBJTHRESHOLD") = XPRS_SLPOBJTHRESHOLD;
	XPRS.attr("SLPBOUNDTHRESHOLD") = XPRS_SLPBOUNDTHRESHOLD;
	// Nonlinear related string controls
	XPRS.attr("NLPIVNAME") = XPRS_NLPIVNAME;
	// SLP related string controls
	XPRS.attr("SLPDELTAFORMAT") = XPRS_SLPDELTAFORMAT;
	XPRS.attr("SLPMINUSDELTAFORMAT") = XPRS_SLPMINUSDELTAFORMAT;
	XPRS.attr("SLPMINUSERRORFORMAT") = XPRS_SLPMINUSERRORFORMAT;
	XPRS.attr("SLPPLUSDELTAFORMAT") = XPRS_SLPPLUSDELTAFORMAT;
	XPRS.attr("SLPPLUSERRORFORMAT") = XPRS_SLPPLUSERRORFORMAT;
	XPRS.attr("SLPSBNAME") = XPRS_SLPSBNAME;
	XPRS.attr("SLPTOLNAME") = XPRS_SLPTOLNAME;
	XPRS.attr("SLPUPDATEFORMAT") = XPRS_SLPUPDATEFORMAT;
	XPRS.attr("SLPPENALTYROWFORMAT") = XPRS_SLPPENALTYROWFORMAT;
	XPRS.attr("SLPPENALTYCOLFORMAT") = XPRS_SLPPENALTYCOLFORMAT;
	XPRS.attr("SLPSBLOROWFORMAT") = XPRS_SLPSBLOROWFORMAT;
	XPRS.attr("SLPSBUPROWFORMAT") = XPRS_SLPSBUPROWFORMAT;
	XPRS.attr("SLPTRACEMASK") = XPRS_SLPTRACEMASK;
	XPRS.attr("SLPITERFALLBACKOPS") = XPRS_SLPITERFALLBACKOPS;
	// Nonlinear related integer attributes
	XPRS.attr("NLPVALIDATIONSTATUS") = XPRS_NLPVALIDATIONSTATUS;
	XPRS.attr("NLPSOLSTATUS") = XPRS_NLPSOLSTATUS;
	XPRS.attr("NLPORIGINALROWS") = XPRS_NLPORIGINALROWS;
	XPRS.attr("NLPORIGINALCOLS") = XPRS_NLPORIGINALCOLS;
	XPRS.attr("NLPUFS") = XPRS_NLPUFS;
	XPRS.attr("NLPIFS") = XPRS_NLPIFS;
	XPRS.attr("NLPEQUALSCOLUMN") = XPRS_NLPEQUALSCOLUMN;
	XPRS.attr("NLPVARIABLES") = XPRS_NLPVARIABLES;
	XPRS.attr("NLPIMPLICITVARIABLES") = XPRS_NLPIMPLICITVARIABLES;
	XPRS.attr("NONLINEARCONSTRAINTS") = XPRS_NONLINEARCONSTRAINTS;
	XPRS.attr("NLPUSERFUNCCALLS") = XPRS_NLPUSERFUNCCALLS;
	XPRS.attr("NLPUSEDERIVATIVES") = XPRS_NLPUSEDERIVATIVES;
	XPRS.attr("NLPKEEPBESTITER") = XPRS_NLPKEEPBESTITER;
	XPRS.attr("NLPSTATUS") = XPRS_NLPSTATUS;
	XPRS.attr("LOCALSOLVERSELECTED") = XPRS_LOCALSOLVERSELECTED;
	XPRS.attr("NLPMODELROWS") = XPRS_NLPMODELROWS;
	XPRS.attr("NLPMODELCOLS") = XPRS_NLPMODELCOLS;
	XPRS.attr("NLPJOBID") = XPRS_NLPJOBID;
	XPRS.attr("MSJOBS") = XPRS_MSJOBS;
	XPRS.attr("NLPSTOPSTATUS") = XPRS_NLPSTOPSTATUS;
	XPRS.attr("NLPPRESOLVEELIMINATIONS") = XPRS_NLPPRESOLVEELIMINATIONS;
	XPRS.attr("NLPTOTALEVALUATIONERRORS") = XPRS_NLPTOTALEVALUATIONERRORS;
	// SLP related integer attributes
	XPRS.attr("SLPEXPLOREDELTAS") = XPRS_SLPEXPLOREDELTAS;
	XPRS.attr("SLPSEMICONTDELTAS") = XPRS_SLPSEMICONTDELTAS;
	XPRS.attr("SLPINTEGERDELTAS") = XPRS_SLPINTEGERDELTAS;
	XPRS.attr("SLPITER") = XPRS_SLPITER;
	XPRS.attr("SLPSTATUS") = XPRS_SLPSTATUS;
	XPRS.attr("SLPUNCONVERGED") = XPRS_SLPUNCONVERGED;
	XPRS.attr("SLPSBXCONVERGED") = XPRS_SLPSBXCONVERGED;
	XPRS.attr("SLPPENALTYDELTAROW") = XPRS_SLPPENALTYDELTAROW;
	XPRS.attr("SLPPENALTYDELTACOLUMN") = XPRS_SLPPENALTYDELTACOLUMN;
	XPRS.attr("SLPPENALTYERRORROW") = XPRS_SLPPENALTYERRORROW;
	XPRS.attr("SLPPENALTYERRORCOLUMN") = XPRS_SLPPENALTYERRORCOLUMN;
	XPRS.attr("SLPCOEFFICIENTS") = XPRS_SLPCOEFFICIENTS;
	XPRS.attr("SLPPENALTYDELTAS") = XPRS_SLPPENALTYDELTAS;
	XPRS.attr("SLPPENALTYERRORS") = XPRS_SLPPENALTYERRORS;
	XPRS.attr("SLPPLUSPENALTYERRORS") = XPRS_SLPPLUSPENALTYERRORS;
	XPRS.attr("SLPMINUSPENALTYERRORS") = XPRS_SLPMINUSPENALTYERRORS;
	XPRS.attr("SLPUCCONSTRAINEDCOUNT") = XPRS_SLPUCCONSTRAINEDCOUNT;
	XPRS.attr("SLPMIPNODES") = XPRS_SLPMIPNODES;
	XPRS.attr("SLPMIPITER") = XPRS_SLPMIPITER;
	XPRS.attr("SLPTOLSETS") = XPRS_SLPTOLSETS;
	XPRS.attr("SLPECFCOUNT") = XPRS_SLPECFCOUNT;
	XPRS.attr("SLPDELTAS") = XPRS_SLPDELTAS;
	XPRS.attr("SLPZEROESRESET") = XPRS_SLPZEROESRESET;
	XPRS.attr("SLPZEROESTOTAL") = XPRS_SLPZEROESTOTAL;
	XPRS.attr("SLPZEROESRETAINED") = XPRS_SLPZEROESRETAINED;
	XPRS.attr("SLPNONCONSTANTCOEFFS") = XPRS_SLPNONCONSTANTCOEFFS;
	XPRS.attr("SLPMIPSOLS") = XPRS_SLPMIPSOLS;
	// Nonlinear related double attributes
	XPRS.attr("NLPVALIDATIONINDEX_K") = XPRS_NLPVALIDATIONINDEX_K;
	XPRS.attr("NLPVALIDATIONNETOBJ") = XPRS_NLPVALIDATIONNETOBJ;
	XPRS.attr("NLPPRIMALINTEGRAL") = XPRS_NLPPRIMALINTEGRAL;
	// SLP related double attributes
	XPRS.attr("SLPCURRENTDELTACOST") = XPRS_SLPCURRENTDELTACOST;
	XPRS.attr("SLPCURRENTERRORCOST") = XPRS_SLPCURRENTERRORCOST;
	XPRS.attr("SLPPENALTYERRORTOTAL") = XPRS_SLPPENALTYERRORTOTAL;
	XPRS.attr("SLPPENALTYERRORVALUE") = XPRS_SLPPENALTYERRORVALUE;
	XPRS.attr("SLPPENALTYDELTATOTAL") = XPRS_SLPPENALTYDELTATOTAL;
	XPRS.attr("SLPPENALTYDELTAVALUE") = XPRS_SLPPENALTYDELTAVALUE;
	// Nonlinear related string attributes
	// SLP related string attributes
	// Knitro's parameters
	XPRS.attr("KNITRO_PARAM_NEWPOINT") = XPRS_KNITRO_PARAM_NEWPOINT;
	XPRS.attr("KNITRO_PARAM_HONORBNDS") = XPRS_KNITRO_PARAM_HONORBNDS;
	XPRS.attr("KNITRO_PARAM_ALGORITHM") = XPRS_KNITRO_PARAM_ALGORITHM;
	XPRS.attr("KNITRO_PARAM_BAR_MURULE") = XPRS_KNITRO_PARAM_BAR_MURULE;
	XPRS.attr("KNITRO_PARAM_BAR_FEASIBLE") = XPRS_KNITRO_PARAM_BAR_FEASIBLE;
	XPRS.attr("KNITRO_PARAM_GRADOPT") = XPRS_KNITRO_PARAM_GRADOPT;
	XPRS.attr("KNITRO_PARAM_HESSOPT") = XPRS_KNITRO_PARAM_HESSOPT;
	XPRS.attr("KNITRO_PARAM_BAR_INITPT") = XPRS_KNITRO_PARAM_BAR_INITPT;
	XPRS.attr("KNITRO_PARAM_MAXCGIT") = XPRS_KNITRO_PARAM_MAXCGIT;
	XPRS.attr("KNITRO_PARAM_MAXIT") = XPRS_KNITRO_PARAM_MAXIT;
	XPRS.attr("KNITRO_PARAM_OUTLEV") = XPRS_KNITRO_PARAM_OUTLEV;
	XPRS.attr("KNITRO_PARAM_SCALE") = XPRS_KNITRO_PARAM_SCALE;
	XPRS.attr("KNITRO_PARAM_SOC") = XPRS_KNITRO_PARAM_SOC;
	XPRS.attr("KNITRO_PARAM_DELTA") = XPRS_KNITRO_PARAM_DELTA;
	XPRS.attr("KNITRO_PARAM_BAR_FEASMODETOL") = XPRS_KNITRO_PARAM_BAR_FEASMODETOL;
	XPRS.attr("KNITRO_PARAM_FEASTOL") = XPRS_KNITRO_PARAM_FEASTOL;
	XPRS.attr("KNITRO_PARAM_FEASTOLABS") = XPRS_KNITRO_PARAM_FEASTOLABS;
	XPRS.attr("KNITRO_PARAM_BAR_INITMU") = XPRS_KNITRO_PARAM_BAR_INITMU;
	XPRS.attr("KNITRO_PARAM_OBJRANGE") = XPRS_KNITRO_PARAM_OBJRANGE;
	XPRS.attr("KNITRO_PARAM_OPTTOL") = XPRS_KNITRO_PARAM_OPTTOL;
	XPRS.attr("KNITRO_PARAM_OPTTOLABS") = XPRS_KNITRO_PARAM_OPTTOLABS;
	XPRS.attr("KNITRO_PARAM_PIVOT") = XPRS_KNITRO_PARAM_PIVOT;
	XPRS.attr("KNITRO_PARAM_XTOL") = XPRS_KNITRO_PARAM_XTOL;
	XPRS.attr("KNITRO_PARAM_DEBUG") = XPRS_KNITRO_PARAM_DEBUG;
	XPRS.attr("KNITRO_PARAM_MULTISTART") = XPRS_KNITRO_PARAM_MULTISTART;
	XPRS.attr("KNITRO_PARAM_MSMAXSOLVES") = XPRS_KNITRO_PARAM_MSMAXSOLVES;
	XPRS.attr("KNITRO_PARAM_MSMAXBNDRANGE") = XPRS_KNITRO_PARAM_MSMAXBNDRANGE;
	XPRS.attr("KNITRO_PARAM_LMSIZE") = XPRS_KNITRO_PARAM_LMSIZE;
	XPRS.attr("KNITRO_PARAM_BAR_MAXCROSSIT") = XPRS_KNITRO_PARAM_BAR_MAXCROSSIT;
	XPRS.attr("KNITRO_PARAM_BLASOPTION") = XPRS_KNITRO_PARAM_BLASOPTION;
	XPRS.attr("KNITRO_PARAM_BAR_MAXREFACTOR") = XPRS_KNITRO_PARAM_BAR_MAXREFACTOR;
	XPRS.attr("KNITRO_PARAM_BAR_MAXBACKTRACK") = XPRS_KNITRO_PARAM_BAR_MAXBACKTRACK;
	XPRS.attr("KNITRO_PARAM_BAR_PENRULE") = XPRS_KNITRO_PARAM_BAR_PENRULE;
	XPRS.attr("KNITRO_PARAM_BAR_PENCONS") = XPRS_KNITRO_PARAM_BAR_PENCONS;
	XPRS.attr("KNITRO_PARAM_MSNUMTOSAVE") = XPRS_KNITRO_PARAM_MSNUMTOSAVE;
	XPRS.attr("KNITRO_PARAM_MSSAVETOL") = XPRS_KNITRO_PARAM_MSSAVETOL;
	XPRS.attr("KNITRO_PARAM_MSTERMINATE") = XPRS_KNITRO_PARAM_MSTERMINATE;
	XPRS.attr("KNITRO_PARAM_MSSTARTPTRANGE") = XPRS_KNITRO_PARAM_MSSTARTPTRANGE;
	XPRS.attr("KNITRO_PARAM_INFEASTOL") = XPRS_KNITRO_PARAM_INFEASTOL;
	XPRS.attr("KNITRO_PARAM_LINSOLVER") = XPRS_KNITRO_PARAM_LINSOLVER;
	XPRS.attr("KNITRO_PARAM_BAR_DIRECTINTERVAL") = XPRS_KNITRO_PARAM_BAR_DIRECTINTERVAL;
	XPRS.attr("KNITRO_PARAM_PRESOLVE") = XPRS_KNITRO_PARAM_PRESOLVE;
	XPRS.attr("KNITRO_PARAM_PRESOLVE_TOL") = XPRS_KNITRO_PARAM_PRESOLVE_TOL;
	XPRS.attr("KNITRO_PARAM_BAR_SWITCHRULE") = XPRS_KNITRO_PARAM_BAR_SWITCHRULE;
	XPRS.attr("KNITRO_PARAM_MA_TERMINATE") = XPRS_KNITRO_PARAM_MA_TERMINATE;
	XPRS.attr("KNITRO_PARAM_MSSEED") = XPRS_KNITRO_PARAM_MSSEED;
	XPRS.attr("KNITRO_PARAM_BAR_RELAXCONS") = XPRS_KNITRO_PARAM_BAR_RELAXCONS;
	XPRS.attr("KNITRO_PARAM_SOLTYPE") = XPRS_KNITRO_PARAM_SOLTYPE;
	XPRS.attr("KNITRO_PARAM_MIP_METHOD") = XPRS_KNITRO_PARAM_MIP_METHOD;
	XPRS.attr("KNITRO_PARAM_MIP_BRANCHRULE") = XPRS_KNITRO_PARAM_MIP_BRANCHRULE;
	XPRS.attr("KNITRO_PARAM_MIP_SELECTRULE") = XPRS_KNITRO_PARAM_MIP_SELECTRULE;
	XPRS.attr("KNITRO_PARAM_MIP_INTGAPABS") = XPRS_KNITRO_PARAM_MIP_INTGAPABS;
	XPRS.attr("KNITRO_PARAM_MIP_INTGAPREL") = XPRS_KNITRO_PARAM_MIP_INTGAPREL;
	XPRS.attr("KNITRO_PARAM_MIP_OUTLEVEL") = XPRS_KNITRO_PARAM_MIP_OUTLEVEL;
	XPRS.attr("KNITRO_PARAM_MIP_OUTINTERVAL") = XPRS_KNITRO_PARAM_MIP_OUTINTERVAL;
	XPRS.attr("KNITRO_PARAM_MIP_DEBUG") = XPRS_KNITRO_PARAM_MIP_DEBUG;
	XPRS.attr("KNITRO_PARAM_MIP_IMPLICATNS") = XPRS_KNITRO_PARAM_MIP_IMPLICATNS;
	XPRS.attr("KNITRO_PARAM_MIP_GUB_BRANCH") = XPRS_KNITRO_PARAM_MIP_GUB_BRANCH;
	XPRS.attr("KNITRO_PARAM_MIP_KNAPSACK") = XPRS_KNITRO_PARAM_MIP_KNAPSACK;
	XPRS.attr("KNITRO_PARAM_MIP_ROUNDING") = XPRS_KNITRO_PARAM_MIP_ROUNDING;
	XPRS.attr("KNITRO_PARAM_MIP_ROOTALG") = XPRS_KNITRO_PARAM_MIP_ROOTALG;
	XPRS.attr("KNITRO_PARAM_MIP_LPALG") = XPRS_KNITRO_PARAM_MIP_LPALG;
	XPRS.attr("KNITRO_PARAM_MIP_MAXNODES") = XPRS_KNITRO_PARAM_MIP_MAXNODES;
	XPRS.attr("KNITRO_PARAM_MIP_HEURISTIC") = XPRS_KNITRO_PARAM_MIP_HEURISTIC;
	XPRS.attr("KNITRO_PARAM_MIP_HEUR_MAXIT") = XPRS_KNITRO_PARAM_MIP_HEUR_MAXIT;
	XPRS.attr("KNITRO_PARAM_MIP_PSEUDOINIT") = XPRS_KNITRO_PARAM_MIP_PSEUDOINIT;
	XPRS.attr("KNITRO_PARAM_MIP_STRONG_MAXIT") = XPRS_KNITRO_PARAM_MIP_STRONG_MAXIT;
	XPRS.attr("KNITRO_PARAM_MIP_STRONG_CANDLIM") = XPRS_KNITRO_PARAM_MIP_STRONG_CANDLIM;
	XPRS.attr("KNITRO_PARAM_MIP_STRONG_LEVEL") = XPRS_KNITRO_PARAM_MIP_STRONG_LEVEL;
	XPRS.attr("KNITRO_PARAM_PAR_NUMTHREADS") = XPRS_KNITRO_PARAM_PAR_NUMTHREADS;

	nb::enum_<SOLSTATUS>(XPRS, "SOLSTATUS")
	    .value("NOTFOUND", SOLSTATUS::NOTFOUND)
	    .value("OPTIMAL", SOLSTATUS::OPTIMAL)
	    .value("FEASIBLE", SOLSTATUS::FEASIBLE)
	    .value("INFEASIBLE", SOLSTATUS::INFEASIBLE)
	    .value("UNBOUNDED", SOLSTATUS::UNBOUNDED);

	nb::enum_<SOLVESTATUS>(XPRS, "SOLVESTATUS")
	    .value("UNSTARTED", SOLVESTATUS::UNSTARTED)
	    .value("STOPPED", SOLVESTATUS::STOPPED)
	    .value("FAILED", SOLVESTATUS::FAILED)
	    .value("COMPLETED", SOLVESTATUS::COMPLETED);

	nb::enum_<LPSTATUS>(XPRS, "LPSTATUS")
	    .value("UNSTARTED", LPSTATUS::UNSTARTED)
	    .value("OPTIMAL", LPSTATUS::OPTIMAL)
	    .value("INFEAS", LPSTATUS::INFEAS)
	    .value("CUTOFF", LPSTATUS::CUTOFF)
	    .value("UNFINISHED", LPSTATUS::UNFINISHED)
	    .value("UNBOUNDED", LPSTATUS::UNBOUNDED)
	    .value("CUTOFF_IN_DUAL", LPSTATUS::CUTOFF_IN_DUAL)
	    .value("UNSOLVED", LPSTATUS::UNSOLVED)
	    .value("NONCONVEX", LPSTATUS::NONCONVEX);

	nb::enum_<MIPSTATUS>(XPRS, "MIPSTATUS")
	    .value("NOT_LOADED", MIPSTATUS::NOT_LOADED)
	    .value("LP_NOT_OPTIMAL", MIPSTATUS::LP_NOT_OPTIMAL)
	    .value("LP_OPTIMAL", MIPSTATUS::LP_OPTIMAL)
	    .value("NO_SOL_FOUND", MIPSTATUS::NO_SOL_FOUND)
	    .value("SOLUTION", MIPSTATUS::SOLUTION)
	    .value("INFEAS", MIPSTATUS::INFEAS)
	    .value("OPTIMAL", MIPSTATUS::OPTIMAL)
	    .value("UNBOUNDED", MIPSTATUS::UNBOUNDED);

	nb::enum_<NLPSTATUS>(XPRS, "NLPSTATUS")
	    .value("UNSTARTED", NLPSTATUS::UNSTARTED)
	    .value("SOLUTION", NLPSTATUS::SOLUTION)
	    .value("LOCALLY_OPTIMAL", NLPSTATUS::LOCALLY_OPTIMAL)
	    .value("OPTIMAL", NLPSTATUS::OPTIMAL)
	    .value("NOSOLUTION", NLPSTATUS::NOSOLUTION)
	    .value("LOCALLY_INFEASIBLE", NLPSTATUS::LOCALLY_INFEASIBLE)
	    .value("INFEASIBLE", NLPSTATUS::INFEASIBLE)
	    .value("UNBOUNDED", NLPSTATUS::UNBOUNDED)
	    .value("UNFINISHED", NLPSTATUS::UNFINISHED)
	    .value("UNSOLVED", NLPSTATUS::UNSOLVED);

	nb::enum_<IISSOLSTATUS>(XPRS, "IISSOLSTATUS")
	    .value("UNSTARTED", IISSOLSTATUS::UNSTARTED)
	    .value("FEASIBLE", IISSOLSTATUS::FEASIBLE)
	    .value("COMPLETED", IISSOLSTATUS::COMPLETED)
	    .value("UNFINISHED", IISSOLSTATUS::UNFINISHED);

	nb::enum_<SOLAVAILABLE>(XPRS, "SOLAVAILABLE")
	    .value("NOTFOUND", SOLAVAILABLE::NOTFOUND)
	    .value("OPTIMAL", SOLAVAILABLE::OPTIMAL)
	    .value("FEASIBLE", SOLAVAILABLE::FEASIBLE);

	nb::enum_<OPTIMIZETYPE>(XPRS, "OPTIMIZETYPE")
	    .value("NONE", OPTIMIZETYPE::NONE)
	    .value("LP", OPTIMIZETYPE::LP)
	    .value("MIP", OPTIMIZETYPE::MIP)
	    .value("LOCAL", OPTIMIZETYPE::LOCAL)
	    .value("GLOBAL", OPTIMIZETYPE::GLOBAL);

	// Define Callbacks context enum
	auto to_upper = [](char const *name) {
		std::string res(name);
		for (char &c : res)
			c = std::toupper(c);
		return res;
	};
	nb::enum_<CB_CONTEXT>(XPRS, "CB_CONTEXT", nb::is_arithmetic())
	// Use the callback list to define a value for each callback
#define XPRSCB_NB_ENUM(ID, NAME, ...) .value(to_upper(#NAME).c_str(), CB_CONTEXT::NAME)
	    XPRSCB_LIST(XPRSCB_NB_ENUM, XPRSCB_ARG_IGNORE);
#undef XPRSCB_NB_ENUM
}
