#include <nanobind/nanobind.h>
#include "copt.h"

namespace nb = nanobind;

void bind_copt_constants(nb::module_ &m)
{
	nb::module_ c = m.def_submodule("Constants");

	c.attr("COPT_MINIMIZE") = COPT_MINIMIZE;
	c.attr("COPT_MAXIMIZE") = COPT_MAXIMIZE;
	c.attr("COPT_INFINITY") = COPT_INFINITY;
	c.attr("COPT_UNDEFINED") = COPT_UNDEFINED;
	c.attr("COPT_BUFFSIZE") = COPT_BUFFSIZE;
	c.attr("COPT_LESS_EQUAL") = COPT_LESS_EQUAL;
	c.attr("COPT_GREATER_EQUAL") = COPT_GREATER_EQUAL;
	c.attr("COPT_EQUAL") = COPT_EQUAL;
	c.attr("COPT_FREE") = COPT_FREE;
	c.attr("COPT_RANGE") = COPT_RANGE;
	c.attr("COPT_CONTINUOUS") = COPT_CONTINUOUS;
	c.attr("COPT_BINARY") = COPT_BINARY;
	c.attr("COPT_INTEGER") = COPT_INTEGER;
	c.attr("COPT_SOS_TYPE1") = COPT_SOS_TYPE1;
	c.attr("COPT_SOS_TYPE2") = COPT_SOS_TYPE2;
	c.attr("COPT_CONE_QUAD") = COPT_CONE_QUAD;
	c.attr("COPT_CONE_RQUAD") = COPT_CONE_RQUAD;
	c.attr("COPT_RETCODE_OK") = COPT_RETCODE_OK;
	c.attr("COPT_RETCODE_MEMORY") = COPT_RETCODE_MEMORY;
	c.attr("COPT_RETCODE_FILE") = COPT_RETCODE_FILE;
	c.attr("COPT_RETCODE_INVALID") = COPT_RETCODE_INVALID;
	c.attr("COPT_RETCODE_LICENSE") = COPT_RETCODE_LICENSE;
	c.attr("COPT_RETCODE_INTERNAL") = COPT_RETCODE_INTERNAL;
	c.attr("COPT_RETCODE_THREAD") = COPT_RETCODE_THREAD;
	c.attr("COPT_RETCODE_SERVER") = COPT_RETCODE_SERVER;
	c.attr("COPT_RETCODE_NONCONVEX") = COPT_RETCODE_NONCONVEX;
	c.attr("COPT_BASIS_LOWER") = COPT_BASIS_LOWER;
	c.attr("COPT_BASIS_BASIC") = COPT_BASIS_BASIC;
	c.attr("COPT_BASIS_UPPER") = COPT_BASIS_UPPER;
	c.attr("COPT_BASIS_SUPERBASIC") = COPT_BASIS_SUPERBASIC;
	c.attr("COPT_BASIS_FIXED") = COPT_BASIS_FIXED;
	c.attr("COPT_LPSTATUS_UNSTARTED") = COPT_LPSTATUS_UNSTARTED;
	c.attr("COPT_LPSTATUS_OPTIMAL") = COPT_LPSTATUS_OPTIMAL;
	c.attr("COPT_LPSTATUS_INFEASIBLE") = COPT_LPSTATUS_INFEASIBLE;
	c.attr("COPT_LPSTATUS_UNBOUNDED") = COPT_LPSTATUS_UNBOUNDED;
	c.attr("COPT_LPSTATUS_NUMERICAL") = COPT_LPSTATUS_NUMERICAL;
	c.attr("COPT_LPSTATUS_IMPRECISE") = COPT_LPSTATUS_IMPRECISE;
	c.attr("COPT_LPSTATUS_TIMEOUT") = COPT_LPSTATUS_TIMEOUT;
	c.attr("COPT_LPSTATUS_UNFINISHED") = COPT_LPSTATUS_UNFINISHED;
	c.attr("COPT_LPSTATUS_INTERRUPTED") = COPT_LPSTATUS_INTERRUPTED;
	c.attr("COPT_MIPSTATUS_UNSTARTED") = COPT_MIPSTATUS_UNSTARTED;
	c.attr("COPT_MIPSTATUS_OPTIMAL") = COPT_MIPSTATUS_OPTIMAL;
	c.attr("COPT_MIPSTATUS_INFEASIBLE") = COPT_MIPSTATUS_INFEASIBLE;
	c.attr("COPT_MIPSTATUS_UNBOUNDED") = COPT_MIPSTATUS_UNBOUNDED;
	c.attr("COPT_MIPSTATUS_INF_OR_UNB") = COPT_MIPSTATUS_INF_OR_UNB;
	c.attr("COPT_MIPSTATUS_NODELIMIT") = COPT_MIPSTATUS_NODELIMIT;
	c.attr("COPT_MIPSTATUS_TIMEOUT") = COPT_MIPSTATUS_TIMEOUT;
	c.attr("COPT_MIPSTATUS_UNFINISHED") = COPT_MIPSTATUS_UNFINISHED;
	c.attr("COPT_MIPSTATUS_INTERRUPTED") = COPT_MIPSTATUS_INTERRUPTED;
	c.attr("COPT_CBCONTEXT_MIPRELAX") = COPT_CBCONTEXT_MIPRELAX;
	c.attr("COPT_CBCONTEXT_MIPSOL") = COPT_CBCONTEXT_MIPSOL;
	c.attr("COPT_CBCONTEXT_MIPNODE") = COPT_CBCONTEXT_MIPNODE;
	c.attr("COPT_CBINFO_BESTOBJ") = COPT_CBINFO_BESTOBJ;
	c.attr("COPT_CBINFO_BESTBND") = COPT_CBINFO_BESTBND;
	c.attr("COPT_CBINFO_HASINCUMBENT") = COPT_CBINFO_HASINCUMBENT;
	c.attr("COPT_CBINFO_INCUMBENT") = COPT_CBINFO_INCUMBENT;
	c.attr("COPT_CBINFO_MIPCANDIDATE") = COPT_CBINFO_MIPCANDIDATE;
	c.attr("COPT_CBINFO_MIPCANDOBJ") = COPT_CBINFO_MIPCANDOBJ;
	c.attr("COPT_CBINFO_RELAXSOLUTION") = COPT_CBINFO_RELAXSOLUTION;
	c.attr("COPT_CBINFO_RELAXSOLOBJ") = COPT_CBINFO_RELAXSOLOBJ;
	c.attr("COPT_CBINFO_NODESTATUS") = COPT_CBINFO_NODESTATUS;
}
