param t0;
param t1;

model facility.mod;

option solver_msg 0;
option presolve 0;
option solver 'gurobi';
option gurobi_options 'outlev=0 timelim=0 presolve=0';

for {n in {25, 50, 75, 100}} {
    let G := n;
    let F := n;
    let t0 := _ampl_elapsed_time + _total_shell_elapsed_time + _total_solve_elapsed_time;
    solve >NUL;
    let t1 := _ampl_elapsed_time + _total_shell_elapsed_time + _total_solve_elapsed_time;
    printf "n=%d, time=%.3f\n", n, t1-t0;
}
