param t0;
param t1;

model lqcp.mod;

option solver_msg 0;
option presolve 0;
option solver 'gurobi';
option gurobi_options 'outlev=0 timelim=0 presolve=0';

for {n_value in {500, 1000, 1500, 2000}} {
    let n := n_value;
    let t0 := _ampl_elapsed_time + _total_shell_elapsed_time + _total_solve_elapsed_time;
    solve >NUL;
    let t1 := _ampl_elapsed_time + _total_shell_elapsed_time + _total_solve_elapsed_time;
    printf "n=%d, time=%.3f\n", n, t1-t0;
}
